OfficeForProductSafetyAndStandards/product-safety-database

- psd-web/test/controllers/investigations_controller_test.rb
> Refactor InvestigationController tests to make use of already instantiated investigations.
Copied over from https://github.com/UKGovernmentBEIS/beis-opss/pull/1346
> Make use of the already instantiated investigations

- psd-web/config/environments/production.rb
Currently we are extending logit quota, and we don't really need to log sql queries.
> Use log level info so we don't log sql queries

- psd-web/app/controllers/investigations/correspondence_controller.rb
- psd-web/app/controllers/investigations/emails_controller.rb
Copied from https://github.com/UKGovernmentBEIS/beis-opss/pull/1319.
Ticket: https://trello.com/c/XQGnlDyl
This problem was caused by the `date_received` being blank in old Enquiries (it's now mandatory). But it was difficult to diagnose. Better log messages have been put in so that this kind of problem will be easier to diagnose in the future.
> Better logging around creating correspondence

- psd-web/test/controllers/teams_controller_test.rb
This fixes a dodgy test which either provides a potential false positive, or fails depending on the test run order because the expectation match count is carried over from previous tests.
> Fix dodgy test

- docker-compose.yml
This fixes the following error when trying to run Keycloak locally via `docker-compose`:
```
keycloak_1       | 18:58:45,779 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "keycloak-server.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"keycloak-server.war\".undertow-deployment" => "java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak_1       |     Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext …
```
> Fix Keycloak service not starting in docker-compose context

- psd-web/app/assets/application/javascripts/autocomplete.js
- psd-web/app/views/investigations/assign.html.slim
- psd-web/app/views/investigations/assign/choose.html.slim
https://trello.com/c/Dw7hYef1/151-dropdown-fields-clear-x-is-not-working-as-expected
Remove .focus().blur() as it sets dropdown input to first entry 
There are still some weird quirks going on with it, but this is a small fix to actually help clear the autocomplete.
We need to update the autocomplete, and in future dig deeper into why setting the value to '', opens the autocomplete.
ALSO ++
https://trello.com/c/gCjcxrW9/145-missing-space-on-error-message
Adding missing space
> Dropdown autocomplete bug

- psd-web/app/jobs/application_job.rb
- psd-web/config/application.rb
- psd-web/config/initializers/sidekiq.rb
- psd-web/config/initializers/storage.rb
- psd-web/config/sidekiq.yml
- psd-web/deploy-review.sh
Currently all review app workers are sharing the same queue, so it is not possible to segregate them.
An immediately obvious example would be if you create a new scheduled job another review app worker can pick it up, but immediately fail because it doesn't have that job class available.
Other problems could occur when app logic is modified and it will not be possible to tell which review app processed the job.
This change separates the queues based on the review instance name, e.g. `pr-XX`.
> Allow Sidekiq queue name to be specified - especially to segregate review apps

- psd-web/app/views/teams/show.html.slim
- psd-web/manifest.prod.yml
For accessibility, I was previously applying aria-label to the link_to
Now it has a span in the link_to text, so that screen readers read out "Resend invitation to #{user.email}"
Before it could miss the aria-label, as well as reading out "Resend invitation, Resend invitation to #{user.email}"
> Resend account invite govuk visually hidden

- psd-web/app/controllers/application_controller.rb
- psd-web/app/controllers/errors_controller.rb
This fixes the page layout not being rendered on error pages.
Before:
After (logged out):
After (logged in)
> Fix page layout on error pages not being rendered

- psd-web/app/assets/application/stylesheets/documents.scss
Our current 'Processing image' placeholder doesn't specify a font and is too distracting on the page.
Changes:
* Explicitly set font and size
* Change to dashed border
* Give it padding and margin
> Improve styling of placeholder graphic

- psd-web/app/assets/stylesheets/documents.scss
There's no font set on the text content of the document thumbnail - so it renders with whatever the system font is.
Before:
After:
> Set font on thumbnail text

- psd-web/app/models/investigation.rb
- psd-web/spec/factories/investigations.rb
- psd-web/spec/models/investigation_spec.rb
This fixes a regression [introduced recently](https://github.com/UKGovernmentBEIS/beis-opss-psd/commit/c78dd635bff891bb8a4834221326b492d74ca9ee#diff-c573245a97e3475b3a065cd10502cd47L14) which prevented e-mails from being sent on case creation. It also adds a new test to prevent future regressions.
I have not attempted to improve the implementation which is pretty nasty with callbacks and dependency on `User.current`, the purpose of this is to fix the regression only and prevent it happening again.
It does also provide a starting point to build up test coverage of the `Investigation` model and subclasses.
> Fix e-mail not being sent when creating a case

- psd-web/spec/decorators/investigation_decorator_spec.rb
This addresses a flaky RSpec spec which could fail, depending on the order in which the two associated products were returned. The existing test only matched against the first returned product, but in some cases where the other product was returned first the matcher would fail because it was being compared case-sensitively. The [decorator modifies the case of the text](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/psd-web/app/decorators/investigation_decorator.rb#L127) on the page from the raw database value.
This change simply modifies the test to compare case insensitively, and also adds some regex escaping to guard against potential failures in future where the data might contain special characters, which might not be spotted or provide false positives.
> Fix flaky RSpec spec

- psd-web/app/views/products/_product_card.html.slim
Removes the `govuk-body` class from the product list view.
This class:
* Is unnecessary as `.psd-product-card` already defines the font and size
* Is not appropriate as the contents aren't body.
* Conflicts with #71 which sets a max width on `govuk-body`
> Remove unnecessary class

- psd-web/spec/factories/organisations.rb
- psd-web/spec/factories/teams.rb
- psd-web/spec/factories/users.rb
- psd-web/spec/models/team_spec.rb
The previous implementation of this spec was incorrect and giving false positives because the factories of different classes had the same `name` value. This fixes the test and also ensures factories have unique names.
> Fix incorrect test, caused by factories having common names

- psd-web/test/models/notification_test.rb
This fixes another intermittent test failure caused by the order in which associated records are returned sometimes being different to that assumed.
In this case, the second record would have a `team_recipient_email` property which altered the behaviour of the tested functionality, adding an extra email recipient to the list who should receive the notification of the assignment change.
This change fixes the team and I also ensured it was the one with the recipient email in order to test that it was included in the list of recipients.
> Fix intermittently failing test on update assignee notifications

- psd-web/app/views/investigations/_highlight_card.html.slim
In #88 I missed that search results use a different template. This adds the status tags to the search results.
> Show case status on search results cards

- psd-web/app/helpers/investigations/user_filters_helper.rb
- psd-web/app/models/team.rb
- psd-web/app/models/user.rb
- psd-web/spec/models/team_spec.rb
- psd-web/spec/models/user_spec.rb
- psd-web/spec/support/not_talk_to_db_matcher.rb
In Scout we are seeing ([example here](https://scoutapm.com/apps/156303/endpoints/Q29udHJvbGxlci9pbnZlc3RpZ2F0aW9ucy9pbmRleA==/trace/1704969432)) over 1,300 database queries taking over 450ms, on the case overview page. The Scout backtrace shows this is coming from rendering the list of users in the 'assigned to' filter list. There are a lot of n+1 database queries created by calling the `display_name` method on the lists of users and teams to render these forms.
The number of database queries is similar to the number of users +teams in the database, so the problem is getting worse as we add more users:
```
irb(main):001:0> User.count
=> 1084
irb(main):002:0> Team.count
=> 217
```
This change uses eager loading to eliminate most of those extra database queries and hopefully significantly …
> Eager load user organisation and teams for assignee filter list to eliminate n+1 database queries

- psd-web/app/assets/stylesheets/autocomplete.scss
- psd-web/app/assets/stylesheets/search-box.scss
Improves the focus styling of our autocompletes to match govuk-frontend.
Before:
After:
> Improve focus styling to match govuk-frontend

- psd-web/spec/factories/corrective_actions.rb
- psd-web/spec/factories/correspondences.rb
This fixes factories which populate a `date_attribute` property. When the date is at the threshold of a year, sometimes the dates produced could be in the future because the day/month/year were generated independently.
> Fix factories which populate date_attribute properties

- psd-web/app/clients/keycloak_client.rb
- psd-web/spec/clients/keycloak_client_spec.rb
- psd-web/spec/decorators/investigation_decorator_spec.rb
- psd-web/spec/features/add_attachment_spec.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/assign_investigation_spec.rb
- psd-web/spec/features/delete_attachment_spec.rb
- psd-web/spec/features/edit_attachment_spec.rb
- psd-web/spec/features/filter_investigations_spec.rb
- psd-web/spec/features/forbidden_spec.rb
- psd-web/spec/features/help_pages_spec.rb
- psd-web/spec/features/home_page_spec.rb
- psd-web/spec/features/report_product_spec.rb
- psd-web/spec/features/send_alert_spec.rb
- psd-web/spec/features/team_spec.rb
- psd-web/spec/models/alert_spec.rb
- psd-web/spec/models/investigation_spec.rb
- psd-web/spec/models/team_spec.rb
- psd-web/spec/models/user_spec.rb
- psd-web/spec/requests/home_page_spec.rb
- psd-web/spec/requests/sign_in_spec.rb
- psd-web/spec/requests/user_declaration_spec.rb
- psd-web/spec/services/user_declaration_spec.rb
- psd-web/spec/support/keycloak.rb
- psd-web/test/test_helper.rb
The `KeycloakClient` singleton class was designed in such a way as state was persisted between tests, and it would also make a request to the OpenID configuration endpoint immediately upon instantiation, which wasn't always necessary.
This manifested in [errors](https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/123/checks?check_run_id=369212250) depending on the spec suite run order if the Keycloak config wasn't stubbed correctly. Sometimes it would give a false positive if a previous test had already stubbed it. There were two model tests which were not stubbing the Keycloak config correctly.
It also meant that you had to stub the endpoint just to create a user with a factory, even if `KeycloakClient` was never called again.
This change ensures that the `KeycloakClient` state can be …
> Fix Keycloak client test isolation

- psd-web/manifest.review.yml
These changes were lost [when migrating to rolling deployments](https://github.com/UKGovernmentBEIS/beis-opss-psd/commit/d38420f9b3d153c9d4b3a194b835e7a29eac9345#diff-ab23bd9f27daaf8761d83809ecc38f46). This meant that background jobs (antivirus scans and emails) were not being processed, and exceptions were being tagged with the `production` environment.
> Fix Sentry and Sidekiq env vars on review apps

- psd-web/app/helpers/url_helper.rb
- psd-web/app/views/documents/edit.html.slim
- psd-web/app/views/documents/remove.html.slim
- psd-web/app/views/documents_flow/metadata.html.slim
- psd-web/app/views/documents_flow/upload.html.slim
- psd-web/spec/factories/documents.rb
- psd-web/spec/factories/investigations.rb
- psd-web/spec/features/add_attachment_spec.rb
- psd-web/spec/features/delete_attachment_spec.rb
- psd-web/spec/features/edit_attachment_spec.rb
- psd-web/spec/helpers/url_helper_spec.rb
This is just a crude sticky plaster solution to fix the back links on the add/edit/remove attachment pages for a case, so that users don't see error messages. It should also resolve some exceptions we're seeing in Sentry due to the links routing to the wrong controller (which is part of the creation flow).
The changed page templates are shared for investigations/businesses/products, but there are big differences in how these three view template groups and routes work.
Businesses/products do not implement proper routes i.e. /products/:id/attachments, instead they implement a Javascript tab only, so the back links go to the overview page instead. It would be possible to add a further sticky plaster for investigations to go to `/attachments`, but I think if we want to go further we should …
> Fix back links on case attachment pages

- psd-web/db/migrate/20200103185949_add_missing_indexes.rb
- psd-web/db/schema.rb
While investigating the broken export functionality, I reviewed the generated SQL statement and identified two missing indexes which would benefit the query. There are multiple joins on the polymorphic `sources` table, and the entire result set is ordered by `updated_at`.
I'm not sure if this will entirely fix the problem; we might have to increase the statement timeout, but hopefully not.
> Add missing database indexes

- psd-web/app/decorators/investigation/allegation_decorator.rb
- psd-web/spec/decorators/investigation/allegation_decorator_spec.rb
- psd-web/spec/features/report_product_spec.rb
Some small tweaks to the allegation title algorithm:
* Use sentence case rather than title case
* append 'hazard' to hazard type
* Include name 'Allegation' for edge case where a case has no products and no product category.
**Electrical appliances and equipment – Fire (no product specified)**
**Electrical appliances and equipment – fire hazard (no product specified)**
**Electric 546 Shaver, Shaver – Other**
**Electric 546 Shaver, Shaver – other hazard**
> Small tweaks to title algorithm

- psd-web/app/controllers/investigations_controller.rb
- psd-web/app/views/investigations/index.xlsx.axlsx
Following the adding of the missing database indexes, we are still getting statement timeouts, albeit the query can be run successfully with one less association eager loaded.
I discovered that a lot of the data being pulled in the controller wasn't actually being rendered in the template; we're just displaying the counts of most associated records. This change makes the database queries much more efficient and should hopefully mean that the export works in production.
I've tested and compared the data output before/after the change is the same using the seed data.
> Fix export

- psd-web/manifest.review.yml
- psd-web/manifest.yml
We do not want e-mail whitelisting enabled on review apps or the staging environment. This has to be explicitly disabled but was not, so it was enabled by default.
I've created new user-provided services to set these variables on these spaces, and this change ensures they are bound to the apps, in the same way as production.
I decided to keep the existing default behaviour whereby it is enabled if the env variable is not set, as it is a useful failsafe.
> Ensure email whitelist is disabled on int and staging environments

- psd-web/app/controllers/businesses_controller.rb
- psd-web/app/controllers/products_controller.rb
- psd-web/app/decorators/businesses_decorator.rb
- psd-web/app/decorators/products_decorator.rb
- psd-web/app/helpers/businesses_helper.rb
- psd-web/app/helpers/products_helper.rb
- psd-web/spec/features/busisnesses_spec.rb
- psd-web/spec/features/products_spec.rb
Fix missing pagination on Business and Product listing pages
https://trello.com/c/1WWJQVmN/266-can-only-view-10-products-on-the-product-page-and-10-businesses-on-the-business-page
> Fix pagination

- README.md
Fixes the link to the antivirus API in the README and points to its new repo.
> Fix link to Antivirus API in README

- psd-web/app/views/documents/_image_tag.html.slim
We've started noticing cases with images with the wrong rotation.
After some investigation it seems to be [related to this issue](https://stackoverflow.com/questions/42401203/chrome-image-exif-orienation-issue), where browsers (Chrome and Safari at least) don't respect the exif image orientation. This will tend to effect images taken with smartphones which are more likely to use this attribute.
As we're using ImageMagic to make previews, we can pass an option to fix this, effectively to ['render out' the rotation](https://imagemagick.org/script/command-line-options.php#auto-orient) in our thumbnails.
Before:
After:
> Render out image rotation rather than using exif

- README.md
While trying to run the project in my machine I noticed that:
- KEYCLOACK_CLIENT_SECRET value is needed in order to correctly run the
service locally without authentication errors against KEYCLOACK.
- The .env.test file needs to be setup in order to successfully run the
tests locally.
This commit documents both processes in the Readme.
> Extend Readme with needed environment vars setup

- psd-web/config/routes.rb
I've been getting a lot of `Forbidden` error messages on Sidekiq web in production when re-queueing failed jobs. The web application log shows errors such as:
```
2020-01-24T14:51:10.36+0000 [APP/PROC/WEB/0] ERR W, [2020-01-24T14:51:10.365192 #17]  WARN -- : attack prevented by Rack::Protection::AuthenticityToken
```
This seems to be related to https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden so I've applied the suggested fix here.
> Fix Sidekiq Web Forbidden errors

- psd-web/manifest.review.yml
- psd-web/manifest.yml
This pins the buildpack version to fix deployments since the new buildpack is failing.
> Pin Ruby buildpack to v1.8.4

- .github/workflows/rspec.yml
- psd-web/Gemfile
- psd-web/Gemfile.lock
- psd-web/spec/features/businesses_spec.rb
- psd-web/spec/support/capybara.rb
Add capybara screenshots to debug upon flaky spec
> Add capybara screenshots on ci failure for flaky spec inspections

- psd-web/Gemfile
- psd-web/Gemfile.lock
This pulls the latest design system gem update to address a bug with the `aria-describedby` attribute as described by https://github.com/UKGovernmentBEIS/govuk-design-system-rails/pull/14
Also resolved a `rubocop` gemfile conflict.
> Bump govuk-design-system-rails to fix checkbox aria attribute

- psd-web/app/assets/javascripts/investigations/attachment_description.js
- psd-web/app/views/application/_related_attachment_fields.html.slim
- psd-web/app/views/documents_flow/upload.html.slim
- psd-web/app/views/investigations/creation_flow/allegation_details.html.slim
- psd-web/app/views/investigations/creation_flow/enquiry_details.html.slim
- psd-web/app/views/investigations/emails/content.html.slim
- psd-web/app/views/investigations/meetings/content.html.slim
- psd-web/app/views/investigations/phone_calls/content.html.slim
- psd-web/app/views/investigations/ts_investigations/_file_page.html.slim
This fixes missing `label` tags for file upload fields. It also corrects the hint text relationship in some instances using the `aria-describedby` attribute.
> Fix file upload field labels and hints

- .dependabot/config.yml
These checks are redundant and causing the dependabot status to show a failure.
> Remove redundant dependabot checks

- README.md
This fixes the broken build status badges following the migration from Travis CI to GitHub Actions.
> Fix build status badges

- psd-web/Gemfile
- psd-web/Gemfile.lock
Removes a deprecation warning: the gem has been renamed to match other gems in the Axlsx community organization.
See https://github.com/caxlsx/caxlsx_rails/blob/master/README.md
> rename axlsx_rails gem to caxlsx_rails

- psd-web/Gemfile
- psd-web/Gemfile.lock
https://github.com/rack/rack/pull/1428 has now been merged and released, so we no longer need to pin to a specific commit.
> switch rack gem to use released 2.1.2 version

- psd-web/app/assets/stylesheets/autocomplete.scss
Removing as the [fix is now in accessible-autocomplete 2.0.2](https://github.com/alphagov/accessible-autocomplete/pull/406).
> Remove padding fix

- psd-web/Gemfile
- psd-web/Gemfile.lock
sassc 2.2.0 includes precompiled binaries which aren’t compatible between different processor architectures, which means that we can't cache the rubygems and reuse them on a different platform. Downgrading to 2.1.0 fixes this, until there’s an alternative solution.
See https://github.com/sass/sassc-ruby/issues/146
> downgrade sassc to 2.1.0

- psd-web/app/assets/javascripts/date_input.js
Previously when the day was the first of the month, clicking "Yesterday" set the date as the 0th of the month. This fix correctly sets it to the last day of the previous month, by using the [`setDate()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate) function on the date object, which if you pass `0`, sets the date object to the last day of the previous month (and previous year, if necessary).
See https://trello.com/c/hpFZ3R5K/170-yesterday-link-doesnt-work-on-1st-of-the-month
> Bugfix: sets yesterday’s date when today is the first of the month

- psd-web/Gemfile
- psd-web/Gemfile.lock
This includes a bugfix for the date component: https://github.com/UKGovernmentBEIS/govuk-design-system-rails/pull/15
See https://trello.com/c/b3N6BwTm/33-date-component-doesnt-have-the-correct-error-styling
> bump govuk-design-system-rails to 0.6.2

- psd-web/app/assets/stylesheets/autocomplete.scss
This is an existing issue from the autocomplete, but I'm confused why it's come up now - I don't know of any changes that might have caused this.
Fix from @nickcolley [here](https://github.com/alphagov/accessible-autocomplete/issues/351#issuecomment-582935867).
> Fix missing arrow

- psd-web/app/jobs/sync_keycloak_user_roles_job.rb
- psd-web/app/models/user.rb
- psd-web/app/models/user_role.rb
- psd-web/config/initializers/sidekiq.rb
- psd-web/db/migrate/20200207112514_create_user_roles.rb
- psd-web/db/schema.rb
- psd-web/spec/factories/users.rb
- psd-web/spec/models/user_role_spec.rb
- psd-web/spec/models/user_spec.rb
- psd-web/spec/support/login_helpers.rb
- psd-web/test/test_helper.rb
This saves the user roles from Keycloak in the application database, introducing a new model `UserRole`, in order to help facilitate the eventual removal of Keycloak from the system.
Previously, roles were cached in Redis for 30 minutes. This change reduces the effective cache delay to up to 10 minutes.
Due to limitations of the Keycloak API it is not possible to get all user roles in one, or even a few, requests. You have to iterate over each user. Currently there are around 1200 users, so that's 1200 extra API requests. To reduce the risk of the whole job failing in the event of a failed request I schedule a new job for each user.
I have increased the cron delay to 10 minutes due to the additional API requests required.
Minimal changes were needed to the existing tests which validates …
> Cache user roles in application database

- psd-web/manifest.review.yml
- psd-web/manifest.yml
Restores the timeout configuration introduced in https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/178, but inadvertently removed in https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/107.
This should prevent deployments reported as failing, e.g. https://github.com/UKGovernmentBEIS/beis-opss-psd/runs/441015017?check_suite_focus=true
> Restore PaaS application start timeout setting to avoid crashing

- psd-web/config/routes.rb
Fix path redirection to `home_page#show` upon omniauth callback failures
> fix ominauth on callback failure

- psd-web/app/controllers/application_controller.rb
As a short term fix to our [broken sign in ](https://trello.com/c/sWxr7Mgh/374-sign-in-links-in-header-no-longer-work)links, make the links point to the homepage. From here the user can use the main 'sign in' button.
> Fix sign-in link in header (short term fix)

- psd-web/config/routes.rb
- psd-web/spec/requests/login_spec.rb
Some user have bookmarks containing old redirect uri that do not exists anymore.
let's redirect those users to the home page
> redirect to root path on old bookmarked url

- README.md
While reading our Readme I noticed several links were broken, so decided to fix them.
Also recorded in the Readme the decision to use ERB instead of Slim.
> Fix Readme broken links

- .github/workflows/deploy.yml
- .github/workflows/review-apps-delete.yml
- .github/workflows/review-apps.yml
- psd-web/deploy-github-functions.sh
This will allow us to track the status and progress of review apps, staging and production deploys.
Github will display a link to the deployed environment or a link to the deployment log when is ongoing or failed.
> Track deploys with Github Deploy statuses API

- .github/workflows/review-apps.yml
- psd-web/app/controllers/users_controller.rb
- psd-web/app/models/user.rb
- psd-web/spec/factories/users.rb
- psd-web/spec/models/user_spec.rb
- psd-web/spec/requests/user_completes_registration_spec.rb
The "activated" flag should only be set after the user has accepted the declaration, so we need a different check within the account setup flow to check that the user hasn't already set up a password and phone number.
> Check whether account has been setup, not activated

- .github/workflows/review-apps.yml
This should be more reliable than parsing the `GITHUB_REF` environment variable, as that variable doesn’t contain the PR number when re-running a failed workflow.
See https://github.community/t5/GitHub-Actions/GITHUB-REF-is-inconsistent/m-p/48129
> Set PR_NUMBER from github event context

- psd-web/spec/features/.rubocop.yml
- psd-web/spec/features/add_attachment_spec.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/assign_investigation_spec.rb
- psd-web/spec/features/businesses_spec.rb
- psd-web/spec/features/delete_attachment_spec.rb
- psd-web/spec/features/edit_attachment_spec.rb
- psd-web/spec/features/filter_investigations_spec.rb
- psd-web/spec/features/forbidden_spec.rb
- psd-web/spec/features/home_page_spec.rb
- psd-web/spec/features/investigation_edit_spec.rb
- psd-web/spec/features/investigations_spec.rb
- psd-web/spec/features/products_spec.rb
- psd-web/spec/features/report_product_spec.rb
- psd-web/spec/features/send_alert_spec.rb
- psd-web/spec/features/sign_in_spec.rb
- psd-web/spec/features/team_spec.rb
Following discussion around the auto-corrected changes to feature spec syntax in https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/321 we have decided to reinstate `feature`/`scenario` methods in feature specs only.
I have therefore replaced the `describe`/`it` method calls so that the tests are written as previously. I have not attempted to correct any semantics in the descriptions.
> Tweak Capybara/FeatureMethods config for feature specs

- README.md
We now rely upon two features which require version 7 (beta) of the Cloud Foundry command line tool (CLI), so this updates the README documentation to reflect this.
The two features requiring the cf7 CLI are:
* Our app manifest includes two separate processes within the same app (`web` and `worker`)
* The deploy script (`deploy.sh`) uses the "rolling deployment" strategy for zero-downtime deploys.
> Update README to use Cloud Foundry v7 CLI

- psd-web/app/controllers/users/passwords_controller.rb
- psd-web/app/jobs/send_user_invitation_job.rb
- psd-web/app/mailers/notify_mailer.rb
- psd-web/spec/jobs/send_user_invitation_job_spec.rb
- psd-web/spec/mailers/notify_mailer_spec.rb
- psd-web/spec/requests/user_requests_password_reset_spec.rb
If a password reset is requested for an e-mail address which has been invited, but hasn't yet set up an account, then we want to send a different e-mail from the regular reset password one, depending on the invitation status.
If the invitation is still valid (within the set time period), then we should re-send the invitation e-mail, allowing the user to continue with setting up their account.
If the invitation has expired, then we should block the password reset process, and instead send a different e-mail asking the user to ask a colleague to re-send their invitation.
Based on a suggestion from @scruti, I've refactored some of the controller conditions into the existing `SendUserInvitationJob` job, in a separate branch (see #347). The only user-facing difference will be _when_ the check …
> Handle requesting a password reset for an invited email

- .github/workflows/review-apps-delete.yml
This is a simpler method of getting the pull request number, rather than having to either parse the `GITHUB_REF` env variable, or query the GitHub API.
See https://github.community/t5/GitHub-Actions/GITHUB-REF-is-inconsistent/m-p/48843#M7301
> Get pull request number from event context

- doc/decisions/0001-use-erb-for-view-templates.md
Following our decision to keep decision records, this adds a brief explanation of our decision to switch from the Slim to ERB templating engines.
This is mainly for the benefit of future developers.
> Add a decision record explaining switch to ERB templates

- psd-web/db/schema.rb
This shouldn't be in the schema, as this table isn't added as a migration but instead these columns were added to the users table in the migration `MoveKeycloakCredentialsToUsers`.
I think this was left in the schema accidentally from another branch.
> Remove keycloak_credentials table from schema

- CHANGELOG.md
- psd-web/app/helpers/businesses_helper.rb
- psd-web/app/models/location.rb
- psd-web/spec/features/add_business_spec.rb
- psd-web/spec/features/report_product_spec.rb
- psd-web/test/system/investigation_business_test.rb
https://trello.com/c/P1g6aPTq/342-town-or-city-does-not-appear-when-added-to-a-case
1. The city params wasn't permitted in strong params
2. The city was simply not used in summary
> Fix bug where city would not appear in summary list

- psd-web/.env.development.example
Fixes "Invalid parameter: redirect_uri" error from Keycloak when attempting to sign in in development mode.
> Fix typo in .env example file

- .github/workflows/minitest.yml
- .github/workflows/rspec.yml
- .github/workflows/system_tests.yml
- psd-web/Gemfile.lock
- psd-web/manifest.review.yml
- psd-web/manifest.yml
- psd-web/package.json
This updates `bundler`, `node` and `yarn` to the new versions supported by the [CloudFoundry Ruby buildpack v1.8.8](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.8). This is due to be rolled out on PaaS "on or after 2020-01-28", according to the post on the paas-announce mailing list. After this time, the current build will break.
**Important: this cannot be merged until the PaaS team have upgraded their buildpack. If it is merged before then deployments will fail. Review app deploy will also fail until the buildpack has been updated**
I've also specified the node and yarn versions in package.json to ensure compatibility.
After running `yarn install` a couple of redundant node dependencies were removed.
> CloudFoundry ruby buildpack update

- .github/workflows/deploy.yml
This should help us become aware of deployment failures faster.
Requires a new `SLACK_WEBHOOK` secret to be added to GitHub.
> Alert team via Slack of deployment failure

- psd-web/Gemfile
- psd-web/Gemfile.lock
Bump the `govuk-design-system-rails` gem to [0.6.3](https://github.com/UKGovernmentBEIS/govuk-design-system-rails/releases/tag/0.6.3).
Includes a bugfix for an ARIA attribute: https://github.com/UKGovernmentBEIS/govuk-design-system-rails/commit/baddb391fd7f684c752e7f6649f142dae51f4210
https://trello.com/c/F2xTxkMv/415-bugfix-typo-in-aria-attribute
> Bump govuk-design-system-rails

- psd-web/app/views/locations/_address_form.html.slim
- psd-web/spec/features/add_business_spec.rb
- psd-web/spec/features/report_product_spec.rb
Updates the address form to follow the [Addresses design pattern](https://design-system.service.gov.uk/patterns/addresses/), which avoids nested fieldsets and uses hidden text to label the first two fields as
Building and street [line 1 of 2]
[Building and street line 2 of 2]
https://trello.com/c/iav7T6JZ/419-bugfix-incorrectly-nested-fieldsets-on-address-form
> Un-nest the fieldset within the address form

- psd-web/Gemfile
- psd-web/Gemfile.lock
Fixes bugs:
* Remove unneeded id and class (https://github.com/UKGovernmentBEIS/govuk-design-system-rails/pull/19)
* Add space before visually hidden text (https://github.com/UKGovernmentBEIS/govuk-design-system-rails/pull/20)
> bump govuk-design-system-rails from 0.6.3 to 0.6.4

- psd-web/app/assets/stylesheets/cookie-banner.scss
- psd-web/app/assets/stylesheets/helpers/js-only.scss
- psd-web/app/assets/stylesheets/main.scss
- psd-web/app/views/layouts/_cookie_banner.html.erb
- psd-web/app/views/layouts/application.html.slim
Fixes 2 accessibility issues within the cookies banner:
* Makes the blue links darker, so that they have higher contrast against the light blue background colour. (See [Trello card](https://trello.com/c/BhpqZVSb/417-accessibility-issue-improve-contrast-of-the-links-in-the-cookies-banner) )
* Adds some visually-hidden text so that the "hide this message" link makes sense when announced out of context. (see [Trello card](https://trello.com/c/xCHsFhOk/418-accessibility-issue-make-the-dismiss-cookies-banner-link-make-sense-of-out-context) )
Also hides the "hide this message" link when javascript disabled, as it requires javascript to work.
Note: I've moved this view from the [shared govuk-design-system-rails repo](https://github.com/UKGovernmentBEIS/govuk-design-system-rails/blob/master/app/vi …
> Update cookies banner to fix accessibility issues

- psd-web/app/views/investigations/_filters.html.slim
- psd-web/app/views/investigations/index.html.slim
- psd-web/app/views/searches/show.html.slim
- psd-web/config/initializers/shared_rails_config.rb
This allows keyboard users to skip past the filters and jump to the search results. The link only appears when tabbing through the page.
See https://trello.com/c/xbKqrrYI/421-add-skip-link-to-pages-with-search-results
> Add "skip to results" link for case searches

- psd-web/app/controllers/comments_controller.rb
- psd-web/app/helpers/application_helper.rb
- psd-web/app/views/comments/new.html.slim
- psd-web/config/initializers/shared_rails_config.rb
- psd-web/config/locales/en.yml
- psd-web/spec/requests/add_comment_spec.rb
The "add comment to a case" flow currently doesn’t use the standard error summary component, and instead uses a flash message. This fixes that.
Also makes sure that `Error: ` is prefixed the the page `<title>` tag.
See https://trello.com/c/S40mJNig/425-add-comment-to-case-doesnt-show-an-error-summary-when-there-are-validation-errors
> Show error summary when adding comment

- .codeclimate.yml
- infrastructure/env/get-env-from-vcap.sh
- psd-web/app/jobs/sync_keycloak_db_job.rb
- psd-web/app/models/keycloak_connector.rb
- psd-web/config/database.yml
- psd-web/config/initializers/sidekiq.rb
- psd-web/db/migrate/20200211150409_add_devise_to_users.rb
- psd-web/db/migrate/20200214155213_add_invitation_token_to_users.rb
- psd-web/db/migrate/20200220142847_add_mobile_number.rb
- psd-web/db/migrate/20200221134756_move_keycloak_credentials_to_users.rb
- psd-web/db/migrate/20200225103836_enable_pgcrypto.rb
- psd-web/db/migrate/20200225103936_generate_uuid_for_organizations_teams_and_users.rb
- psd-web/db/migrate/20200309120706_add_keycloak_import_fields_to_users.rb
- psd-web/db/migrate/20200310170356_trigger_schema_for_review_app.rb
- psd-web/db/schema.rb
- psd-web/manifest.review.yml
- psd-web/manifest.yml
This is first step of rolling out devise to production. This PR:
* backports all database schema changes from `keycloak-replacement` branch to master
* adds code to synchronize keycloak credentials into `users` table
This way we will be able to deploy `keycloak-replacement` branch alongside production to test it. It will assure zero-downtime switch.
It will require running `cf update-service database -c '{"enable_extensions": ["pgcrypto"], "reboot": true}'` on staging and production environemnts
Checks
> Backport all relevant database changes and syncing keycloak db

- psd-web/deploy-review.sh
Review apps DB provisioning is considering only `'create` but should also work after DB is updated
> Fix review db provisioning

- psd-web/db/migrate/20200225163932_remove_path_from_team_and_organisation.rb
- psd-web/db/schema.rb
Removes all db removals so we can use production db with `keycloak-replacement` branch.
> Remove migration which will be moved to different PR

- CHANGELOG.md
- psd-web/app/decorators/investigation/enquiry_decorator.rb
- psd-web/app/decorators/investigation_decorator.rb
- psd-web/app/models/investigation/enquiry.rb
- psd-web/spec/decorators/investigation/enquiry_decorator_spec.rb
- psd-web/spec/decorators/investigation_decorator_spec.rb
**CHANGES:**
Now only enquiries will display received by and received date
> only display Received date and received by for enquiries

- psd-web/app/controllers/investigations/businesses_controller.rb
- psd-web/app/controllers/investigations/products_controller.rb
- psd-web/spec/features/add_business_spec.rb
- psd-web/spec/features/add_product_spec.rb
- psd-web/test/controllers/investigations/products_controller_test.rb
https://trello.com/c/iIJVRNOm/242-links-back-to-case-tabs-are-now-broken
Fixes the redirects after adding a business or product to a case to go to their full paths (e.g. `/cases/1912-0001/products`) instead of the old tab anchor links (e.g. `/cases/1912-0001#products`).
As suggested on the Trello card I checked all other usage of anchor redirects but currently these are the only ones which support full paths.
I also added a missing feature spec to cover adding a product to a case, and corrected a slight problem with the existing add business spec.
> Fix redirects after adding businesses/products to a case and add missing feature spec

- psd-web/app/assets/stylesheets/helpers/password-manager-hidden.scss
- psd-web/app/assets/stylesheets/main.scss
- psd-web/app/views/devise/two_factor_authentication/show.html.erb
- psd-web/app/views/users/complete_registration.html.erb
https://trello.com/c/5qErVTcP/438-improve-chances-of-passwords-getting-saved-correctly-autocomplete
Allows password managers to capture the username when completing registration for an account.
We did not want the username to be visible to the user.
Hidden inputs were ignored, as were elements inside a `govuk-visually-hidden` class. Multiple iterations were made to arrive at this solution, which is tested in Chrome and Firefox with 1Password, OSX Keychain and the Okta Password Manager on a BEIS managed laptop. It is not accessible via keyboard or screen readers.
> Password manager login

- psd-web/app/controllers/users/sessions_controller.rb
- psd-web/app/controllers/users/two_factor_authentication_controller.rb
- psd-web/app/controllers/users_controller.rb
- psd-web/app/models/user.rb
- psd-web/db/migrate/20200320144542_add_mobile_number_verified_to_users.rb
- psd-web/db/schema.rb
- psd-web/spec/factories/users.rb
- psd-web/spec/features/creating_an_account_from_an_invitation_spec.rb
- psd-web/spec/features/sign_in_spec.rb
- psd-web/spec/requests/two_factor_authentication_spec.rb
- psd-web/spec/requests/user_completes_registration_spec.rb
This requires users to complete a mobile phone number verification step (entering a code received via text message) when completing their account details after being invited to use the service.
Because entering name, password and mobile number is a previous step, the user can potentially be left in a state where they have set those details but haven't verified their mobile number. In this (hopefully rare) state, they:
* Can still go back and start their account setup process again (from the link in the e-mail), provided it’s within the expiry period.
* Cannot login - if they do, they get a generic error message (this prevents a user from ending up in a state where they have an active account but can't sign in because their mobile number is invalid).
See …
> Add 2fa to registration flow

- psd-web/app/controllers/users/sessions_controller.rb
- psd-web/app/views/users/missing_mobile_number.html.erb
- psd-web/config/locales/en.yml
- psd-web/config/routes.rb
- psd-web/spec/requests/login_spec.rb
**CHANGES:**
For now display the wrong password or email message when a use logs in but does not have a mobile number associated with their account.
> Fix silent failure with user with no mobile number

- psd-web/app/controllers/users/passwords_controller.rb
- psd-web/app/controllers/users/two_factor_authentication_controller.rb
- psd-web/spec/features/password_reset_spec.rb
- psd-web/spec/requests/user_resets_password_spec.rb
Trello ticket: https://trello.com/c/rwtnglov/427-2fa-on-forgot-password
When an user reaches the reset password page after receiving the link by email, it will be redirected to the 2FA page as a security check before being able to reset its password.
In order to achieve this we use the following process:
1 - Anonymous user lands at "edit password" and its email gets identified.
2 - The user gets signed in based on its email address.
3 - User session gets marked as "needs 2FA".
4 - A 2FA code is sent to the user.
5 - User gets redirected to the 2FA page so can introduce its code.
6 - Once the correct code is introduced, the user gets redirected back to the "Edit password" page keeping the same "reset password token" that had in the reset password email link.
7 - When landing as a …
> Enable 2FA when user attempts to reset password

- psd-web/deploy-review.sh
Increases the app startup timeout during the deploy process for review apps only. This was already proven successfully on prod/staging as per https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/355. The threshold is set lower for review apps as there is only one instance.
> Increase CloudFoundry app start timeout from 5 to 10 minutes on review apps

- psd-web/app/jobs/sync_keycloak_teams_and_users_job.rb
This will be removed later once the `keycloak-replacement` branch is merged.
Merge only after #421 has deployed and run the migration
> Set mobile number as verified during keycloak sync task

- psd-web/app/controllers/users/sessions_controller.rb
- psd-web/spec/features/sign_in_spec.rb
The existing test checked that the user gets an immediate "Enter correct email address and password" error if they try to login after having abandoned the registration flow before verifying their e-mail.
However, if the user subsequently tried to visit another URL, such as the homepage, they were then presented with the 2FA page, as `warden.authenticate(auth_options)` will have signed them in.
This fixes that, but signing the user back out again from within the controller.
> Bugfix ensure user cant sign in with unverified mobile number

- psd-web/app/assets/stylesheets/main.scss
- psd-web/app/controllers/users/passwords_controller.rb
- psd-web/app/views/users/complete_registration.html.erb
- psd-web/app/views/users/passwords/edit.html.erb
- psd-web/spec/features/creating_an_account_from_an_invitation_spec.rb
- psd-web/spec/features/password_reset_spec.rb
https://trello.com/c/FjWmfu1w/453-complete-registration-email-field-is-visible
https://trello.com/c/U4zEMS0p/454-reset-password-form-should-include-user-name-for-password-managers
Fixes missing CSS on the complete registration form, and embeds the username in the forgot password form so that password managers can pick it up when saving the password.
> Forgot password manager

- psd-web/app/controllers/users/sessions_controller.rb
- psd-web/app/controllers/users_controller.rb
- psd-web/spec/features/creating_an_account_from_an_invitation_spec.rb
- psd-web/spec/features/sign_in_spec.rb
If you've completed the first step of registration (adding name, password and mobile number) but didn't complete the 2FA, and then you later go back and attempt to start again using the invite link, it probably makes sense not to prefill the form with your name and mobile number from last time...
See https://trello.com/c/dm7gIfWt/449-account-details-pre-filled-after-abandoning-account-registration
> Bugfix: Don’t prefill name and mobile number after abandoned registration

- psd-web/config/locales/devise.en.yml
We don’t need to see a "You are already signed in." message.
> Remove devise flash message

- psd-web/config/initializers/devise.rb
By always setting these we resolve a bug whereby, if the `TWO_FACTOR_AUTHENTICATION_ENABLED` environment variable is missing, then 2FA is turned on (as the default is true in `application.rb` but the config setting for 2fa weren’t being set in the `devise.rb` initializer.
> Always set the two factor authentication options

- psd-web/app/controllers/users/password_changed_controller.rb
- psd-web/app/controllers/users/passwords_controller.rb
- psd-web/app/views/users/password_changed/show.html.erb
- psd-web/config/routes.rb
- psd-web/spec/features/password_reset_spec.rb
- psd-web/spec/requests/user_resets_password_spec.rb
This should help make it clearer to the user that their password was successfully updated, rather than just redirecting to the homepage.
Screenshot:
> Add interstitial page after changing password

- psd-web/app/controllers/users_controller.rb
- psd-web/spec/requests/user_completes_registration_spec.rb
Does not force 2fa when it is disabled.
https://trello.com/c/vhP7aS87/456-complete-registration-should-respect-twofactorauthenticationenabledfalse
> enforce two factor auth configuration when registering

- psd-web/app/views/products/_form.html.slim
- psd-web/config/constants/product_constants.yml
- psd-web/lib/tasks/update_product_category.rake
This adds two product categories relating to the coronavirus response.
As one of these is a rename (`Protective equipment` -> `Personal protective equipment (PPE)`), this also includes a data migration as a separate rake task to update the existing products and cases (as the categories are stored as strings).
> Add product categories relating to coronavirus

- psd-web/app/controllers/users/sessions_controller.rb
- psd-web/app/views/devise/sessions/new.html.erb
- psd-web/spec/features/sign_in_spec.rb
**CHANGES:**
Upon submitting the wrong credentials twice the form is generated to use PATCH
as the user as an id
https://trello.com/c/8KwrwkSm/472-page-not-found-error-with-half-registered-user
> Fix submitting wrong credentials twice on sign in

- .github/workflows/deploy.yml
- .github/workflows/review-apps.yml
- psd-web/config/database.yml
- psd-web/config/sidekiq.yml
- psd-web/deploy-review.sh
- psd-web/deploy.sh
- psd-web/manifest.review.yml
- psd-web/manifest.yml
This fixes an issue we’ve [seen in production (~4000 times)](https://sentry.io/organizations/beis/issues/1588837243/?project=1329381) whereby a Sidekiq worker process throws a `ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5 seconds)` error.
This happens because currently we’ve set the database connection pool to a fixed size of 5, but the number of Sidekiq threads to 10.
To fix this, the database connection pool size now defaults to the value of `RAILS_MAX_THREADS` if set (or 5 otherwise), and this env var is also used to set the Sidekiq concurrency and the number of Puma threads (which was already the case).
The `RAILS_MAX_THREADS` is set to 5 for Puma (web process) and 10 for Sidekiq (worker process) as currently, with these values fed through …
> Use RAILS_MAX_THREADS env var for db concurrency

- psd-web/.gitignore
- psd-web/deploy-review.sh
This fixes a few issues with the review-app deploy script:
* pgcrypto extension not enabled ([the PaaS docs](https://docs.cloud.service.gov.uk/deploying_services/postgresql/#add-or-remove-extensions-for-a-postgresql-service-instance) state this must be enabled at the time the service is created)
* The script copies files to `psd-web/env` when run, which could be accidentally committed
* Two new env vars `WEB_MAX_THREADS` and `WORKER_MAX_THREADS` introduced in https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/445 had no default value so the deployment would fail if ran outside of the GitHub Actions environment
> Fixes for review app deploy script

- psd-web/db/migrate/20200402142659_add_coronavirus_related_to_investigations.rb
- psd-web/db/schema.rb
https://trello.com/c/b3K7oCvN/466-add-page-asking-if-case-is-related-to-coronavirus-for-trading-standards
Adds the column required to record whether an investigation is related to the 2020 coronavirus pandemic. This is required for several other stories so I have separated it from the above linked story to unblock work on those.
Also contains schema updates missing from https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/444
> Add coronavirus flag to investigations table

- psd-web/app/views/help/privacy_notice.html.slim
Remove reference to the Keycloak cookies, and add reference to the two factor authentication cookie.
> Update privacy policy page to remove reference to keycloak cookies

- psd-web/db/schema.rb
Looks like the schema file was manually edited in #456 when the column was renamed (from `is_coronavirus_related` to `coronavirus_related`).
When running `rake db:migrate:reset`, Rails updates the `schema.rb` so that the columns are in alphabetical order.
> columns within schema should be in alphabetical order

- psd-web/app/controllers/users/sessions_controller.rb
- psd-web/spec/features/sign_in_spec.rb
Trello Card: https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/458
We don't allow to login into the service users who didn't complete the 2FA validation for their mobile phone when completing their registration.
But when they attempt to use their credentials, on top of the login error page, they get a 2FA code in their mobile phone.
This happens because the code send 2FA codes is hooked to warden authentication method. And this method is being called by Devise user helpers that are being invoked by our service in `before_action` `ApplicationController` declarations.
The solution consists in delaying these calls until we effectively want to authorise the user.
We only want to send sms with 2FA code for users that are going to be
redirected to 2FA page in order to fil the form with the …
>  Bugfix: Avoid sending 2FA code when not requesting 2FA

- CHANGELOG.md
- psd-web/app/assets/stylesheets/_summary_list.scss
- psd-web/app/assets/stylesheets/main.scss
- psd-web/app/controllers/account_controller.rb
- psd-web/app/controllers/account_name_controller.rb
- psd-web/app/controllers/application_controller.rb
- psd-web/app/models/user.rb
- psd-web/app/views/account/name.html.erb
- psd-web/app/views/account/show.html.erb
- psd-web/config/initializers/shared_rails_config.rb
- psd-web/config/routes.rb
- psd-web/spec/features/add_test_results_spec.rb
- psd-web/spec/features/your_account_spec.rb
- psd-web/spec/support/matchers/capybara_matchers.rb
This adds a "Your account" screen, and allows users to change their name.
Trello card: https://trello.com/c/FGYrtWv4/332-3-your-account-pages
This was mostly pretty trivial. I've added two controllers, `AccountController` (which renders the account page put doesn't do anything else) and `AccountNameController`, which has `show` and `update` actions. These are named to match the URL paths.
There's one validation on the `name` attribute (a simple `presence` validation), which is also shared by the account setup flow. It seemed simpler to duplicate it though, rather than extract this into a shared concern/method/whatever.
The account page uses a new [`govukSummaryList`](https://github.com/UKGovernmentBEIS/govuk-design-system-rails/blob/master/app/helpers/govuk_design_system/summary_list_helpe …
> Allow users to change their names

- psd-web/app/controllers/users/two_factor_authentication_controller.rb
- psd-web/spec/features/sign_in_spec.rb
This is helpful, as some users may accidentally add a space after the security code (eg from a mobile keyboard).
See https://trello.com/c/RWJ7pENv/492-1-strip-whitespace-on-2fa-codes-before-validating
> Strip whitespace from security code that user enters

- psd-web/app/views/investigations/_coronavirus.html.erb
- psd-web/spec/support/feature_helpers.rb
We've decided the covid banner on the covid question isn't needed
as we have it on the TS homepage.
> Remove covid banner from question page

- psd-web/config/environments/production.rb
https://trello.com/c/n4bJKN2i/486-spike-investigate-intermittent-elastic-search-issues-causing-missing-cases
During a rolling deployment we have noticed a recurring issue with 'no cases' shown in the front end. This also manifests an exception - examples at https://sentry.io/organizations/beis/issues/1615248225/?project=1329381&query=is%3Aunresolved&statsPeriod=14d. It eventually resolves itself after a few minutes when the deployment is complete.
I think this is due to the application re-indexing the models on startup. In our scenario where we presently have scaled to four web instances, this will happen four times. The use of `force: true` causes it to [delete the index first](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/importing …
> Don't re-index models in Elasticsearch on deployment

- psd-web/db/migrate/20181101114717_add_audit_fields_for_activities.rb
- psd-web/db/migrate/20181105134010_add_correspondence_to_activities.rb
Since running these migrations, we must have updated the `strong_migrations` gem, which now complains about these.  This blocks running a `rake db:migrate` locally.
By marking these as "safety assured" we can run the migrations locally. This won't impact production as the migrations have already run there.
> Mark old migrations as safe

- psd-web/app/assets/javascripts/cookie_banner.js
The link in our cookie banner is used to hide the message - however because the default href is `#`, this means the url is changed when the link is clicked. As the link is exclusively for js users and not for navigation, we can prevent the default link behaviour from happening.
Before, clicking `hide this message`:
Would result in:
Now it looks like:
> Prevent default on hide cookie link

- psd-web/app/assets/stylesheets/header.scss
Removes unnecessary margin on the beta tag in our header - which currently makes the link larger than it needs to be.
Current:
Fixed:
> Remove margin from right of tag in header

- psd-web/app/models/audit_activity/investigation/update_assignee.rb
This makes the message more visually distinctive in the email.
Also fixed a bug whereby the lead-in line ("Message from {name}:") wasn't being included, and reworded that slightly.
See https://trello.com/c/sQHypNpr/351-use-inset-style-for-comments-included-with-email-notifications
> Use inset text style for assignment message

- psd-web/app/controllers/users_controller.rb
- psd-web/app/jobs/send_user_invitation_job.rb
- psd-web/app/models/user.rb
- psd-web/app/services/create_organisation_with_team_and_admin_user.rb
- psd-web/db/migrate/20200402142659_init_schema.rb
- psd-web/db/migrate/20200427131227_user_invited_at_not_null.rb
- psd-web/db/schema.rb
- psd-web/db/seeds.rb
- psd-web/spec/factories/users.rb
- psd-web/spec/jobs/send_user_invitation_job_spec.rb
- psd-web/spec/models/user_spec.rb
- psd-web/spec/requests/user_completes_registration_spec.rb
- psd-web/test/fixtures/users.yml
https://trello.com/c/RwQ63f7o/520-bugs-with-invitations-for-users-invited-prior-to-keycloak-migration
Also includes fixes for https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/527 - I've included them here because it's affecting the deployment due to a new migration being added, and in anticipation of it being merged fairly quickly.
This fixes some bugs around the invitation/registration process, particularly for legacy users invited prior to the removal of Keycloak, but not yet registered.
These users were able to attempt to reset their password, and would then receive the invitation email with no `invitation` param in the link in the email. This was because they have no `invitation_token` set. And the form would render because there was no check for this combination of conditions, …
> Fix invitations

- .github/workflows/deploy.yml
- psd-web/manifest.review.yml
Background: we've seen a number of `Exit status 223 (out of memory)` errors when deploying review apps and to staging.
This change increases the available memory to 2GB which matches production. It's the next available increment above 1GB.
> Increase memory on staging and review apps

- psd-web/app/controllers/secondary_authentications_controller.rb
- psd-web/app/forms/secondary_authentication_form.rb
1. Dont' permit all the params, this renders String parameter useless... 
2. Delegate method some methods from the form object to the wrapped secondary
form object. It reduces the knowledge the controller needs to know (Law of Demeter). Basically, it avoids the controller knowing about the internals or the form object.  
3. Upon redirect delete the redirect_to in order not to be accidentally
redirected to it at the next secondary authentication.
4. swap "/" for root_path
> various improvements:

- psd-web/spec/support/mailer.rb
- psd-web/spec/support/user.rb
This fixes a number of flaky tests (example: https://github.com/UKGovernmentBEIS/beis-opss-psd/runs/622461339?check_suite_focus=true) caused by an [ActiveRecord callback](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/psd-web/app/models/investigation.rb#L233-L242) sending an email if `User.current` is set. Tests were not cleaning up `User.current` - a regression introduced by the Keycloak replacement work - so depending on the test order this would sometimes attempt to send an email unexpectedly. This change makes sure `User.current` is cleared after each test.
Also improved the mailer stub so that it does not call the original implementation, which could result in a call to the live Notify API, and added some extra properties to the `delivered_emails` objects so we can …
> Fix mailer stub

- psd-web/app/models/user.rb
- psd-web/spec/features/invite_user_spec.rb
- psd-web/spec/features/team_spec.rb
- psd-web/spec/models/user_spec.rb
- psd-web/test/controllers/teams_controller_test.rb
https://trello.com/c/RwQ63f7o/520-bugs-with-invitations-for-users-invited-prior-to-keycloak-migration
Due to a lack of tests around resending user invitations, https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/531 introduced a bug whereby a user whose invitation was expired could not have their invitation resent. They would instead receive the "invitation expired" email.
The fix is to reset their `invited_at` timestamp when the team admin resends their invitation. This means the job will send the correct invitation email.
I've taken the opportunity to add a spec around this scenario and refactor some of the existing tests, and removed a few redundant Minitest tests.
Thanks to @nasirkhanbeis for spotting this bug.
> Fix invite

- psd-web/app/mailers/notify_mailer.rb
- psd-web/spec/mailers/notify_mailer_spec.rb
Bugfix for https://sentry.io/organizations/beis/issues/1463173953/
Seems that the Notify API requires all personalisation keys to have a value, eg a blank string, rather than being null.
> Bugfix: optional message should be blank, not nil

- psd-web/config/webpacker.yml
This renders css by default rather than doing it client side with javascript.
This fixes an issue where we can't test on dev environment without js as it also stops CSS from rendering.
Suggest testing this locally to check it works sensibly. Unlike master, if you disable javascript you should see a site with css.
> Extract css by defualt rather than rendering with javascript

- psd-web/app/helpers/investigations/display_text_helper.rb
- psd-web/spec/helpers/investigations/display_text_helper_spec.rb
Our assignee section currently shows the assignee and their org. For many users, the org name is the same as the team name.
Where the team is the assignee, this means we show the same text twice.
This pr cleans up the markup a little (no unnecessary divs) and uniques the names.
Before:
After:
Because I'm uniquing the names this means that for opss we'll still show the team name and the org - the same for other orgs where they've got multiple teams.
> Don't output team and org names if they're the same

- .github/workflows/overrides/bugfix-filtering-cases-assigned-to-me.env
- psd-web/app/helpers/investigations_helper.rb
- psd-web/spec/features/filter_investigations_spec.rb
- psd-web/spec/features/investigations_spec.rb
This fixes the bug whereby if you click the "Your cases" link on the homepage, you also see cases assigned to your team.
See https://trello.com/c/5LUydUFA/199-your-cases-link-filter-doesnt-filter-to-users-cases
This was caused because the filter builds the query by assuming that the team ID of your team should be added to the query unless the `assigned_to_team_0` param has the value of `unchecked`. But because the link from the homepage doesn't set this param (it just sets `/cases?assigned_to_me=checked`), the param had the value of nil instead of `unchecked`.
A private `set_default_assignee_filter` sets the params values to `unchecked` if they are missing, but the `assigned_to_team_0` was missing. Adding this fixes the bug.
I've added a feature spec which tests for this bug (if you …
> Bugfix filtering cases assigned to me

- psd-web/spec/features/add_attachment_spec.rb
- psd-web/spec/features/add_business_spec.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/add_product_spec.rb
- psd-web/spec/features/add_test_results_spec.rb
- psd-web/spec/features/case_permissions_management_spec.rb
- psd-web/spec/features/create_allegation_as_opss_user_spec.rb
- psd-web/spec/features/create_enquiry_as_opss_user_spec.rb
- psd-web/spec/features/creating_an_account_from_an_invitation_spec.rb
- psd-web/spec/features/delete_attachment_from_case_spec.rb
- psd-web/spec/features/delete_attachment_from_product_spec.rb
- psd-web/spec/features/edit_attachment_spec.rb
- psd-web/spec/features/invite_user_spec.rb
- psd-web/spec/features/password_reset_spec.rb
- psd-web/spec/features/registration_spec.rb
- psd-web/spec/features/report_product_spec.rb
- psd-web/spec/features/team_spec.rb
- psd-web/spec/features/your_account_spec.rb
- psd-web/spec/rails_helper.rb
- psd-web/spec/support/feature_helpers.rb
- psd-web/spec/support/features/page_expectations.rb
This should help us to avoid duplication of the helper methods across different feature specs.
As part of this, I spotted that we had some identical helper methods, some slight variants, and some which were named the same thing but were asserting different pages (in which case I renamed one of them).
A few of the page expectations are used both within an edit scenario, where the ID of the thing is know as it is set up before the test using a factory, and a creation scenario, where the ID is generated as part of the flow. Rather than having 2 different helpers, I've merged them together and made the ID optional. If missing then the expectations uses a regex for the ID instead.
> Reorganise page expectation helpers into a single support file

- psd-web/test/application_system_test_case.rb
Inadvertent copy/paste error while fixing the foreign key constraint; did not break anything or cause any errors (hence not detected) but fixed it anyway.
> Fix inadvertent error in system test teardown

- psd-web/app/views/searches/show.html.erb
The search results layout is broken:
After fix:
This might not be 100% correct and needs cross browser testing.
> Fix search results layout

- psd-web/app/models/team.rb
- psd-web/config/constants/important_team_names.yml
- psd-web/db/seeds.rb
https://trello.com/c/1RGPhcbs/239-1-rename-the-opss-processing-team
This team is considered 'important' for the purposes of always being displayed on the change owner page for OPSS users, and we also use it for seeds, so I've updated the code accordingly.
When this is deployed I will update the team name manually. Until this is done the team will not be displayed on the change owner page, but there should be no other issues.
Review app seeds have already been updated.
Also removed some related redundant code which appears to no longer be used.
> Change OPSS Processing team name

- psd-web/app/helpers/investigations_helper.rb
- psd-web/app/views/investigations/tabs/_overview.html.erb
This moves the building of the `rows` argument passed to the `govukSummaryList()` helper with the "About the case" section to its own helper.
This is mainly to avoid having a condition within the view template.
See [discussion on parent Pull Request](https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/588#discussion_r423549075).
> Refactor the rows object into a helper

- psd-web/app/forms/edit_investigation_collaborator_form.rb
- psd-web/app/mailers/notify_mailer.rb
- psd-web/spec/features/case_permissions_management_spec.rb
- psd-web/spec/mailers/notify_mailer_spec.rb
https://trello.com/c/eYtohraA/544-refactor-display-names
This fixes a minor bug in the notification emails which are sent when a team is added or removed from a case.
They did not show the team name of the user who added or removed your team. In normal circumstances the recipient would not be in the same team as the person who added or removed, since in that case they would already be a collaborator on the case.
In the case of the team deleted email I have also refactored the interface to the mailer since it depended on being given a serialised form object, which is unnecessary and slightly cumbersome. Passing the individual arguments instead will make it easier to call this method elsewhere if required and makes it easier to test. Since there were no unit tests for the mailer I added …
> Fix name in ownership emails

- doc/deployment.md
- psd-web/deploy-review.sh
This change deletes an existing review app before starting to deploy. This ensures we can push as frequently as we want and the GitHub action should not fail because a previous deployment is still in progress.
I have tested this manually from my machine and it seems to fail the previous deployment immediately no matter where it has got to, which is exactly what we want.
Also tested on CI by pushing a second commit while the first deployment was still working, and then rebasing while the second deployment was working. Example of failure triggered when another deployment starts here: https://github.com/UKGovernmentBEIS/beis-opss-psd/runs/674907421?check_suite_focus=true
This is a simpler solution than the existing workarounds I previously added, which I have now removed.
Also fixed an error …
> Delete existing review app when deploying to prevent deployment errors

- psd-web/app/views/documents/_document_card.html.slim
- psd-web/app/views/investigations/tabs/_businesses.html.slim
- psd-web/app/views/investigations/tabs/_products.html.slim
- psd-web/app/views/link_helper/_link_with_hidden_text_to.html.erb
- psd-web/spec/helpers/link_helper_spec.rb
The hidden link helper was forcing hidden text to be in brackets. This isn't always needed.
I've removed the default text and reapplied where we want it.
Should outwardly look the same to users.
> Remove brackets from link helper

- psd-web/app/controllers/application_controller.rb
- psd-web/spec/requests/invalid_wizard_step_spec.rb
Prevents an invalid URL from throwing a 500 error.
> Render 404 page not found for invalid wizard steps

- psd-web/app/models/secondary_authentication.rb
- psd-web/config/constants/domains_allowing_otp_whitelisting.yml
- psd-web/config/initializers/constants.rb
Extract the regular expressions defining the domains where secondary authentication One Time Password codes can be whitelisted to a constants YAML file.
We do not want to set this in ENV VARS per environment due to strict security requirements. To avoid an easy (and hard to trace) mess up because an env var was incorrectly set.
We neither want urls hardcoded in our business logic.
Extracting these regular expressions defining our urls into a YAML file of constants is a solution that sits in the middle of the mentioned two approaches.
> Extract domains whitelisting OTPs to a yaml file

- psd-web/spec/features/add_business_spec.rb
- psd-web/spec/support/features/page_expectations.rb
Added one test around edit business details in an existing feature spec
Note: This is based on existing pr 606- ( my bad) so dependent on 606 to go first in master before this can be merged.
Just a minor change- added one additional step within existing test to validate edit business
> Extend tests edit business details

- psd-web/spec/features/add_business_spec.rb
- psd-web/spec/features/add_test_results_spec.rb
- psd-web/spec/features/investigation_edit_spec.rb
- psd-web/spec/support/features/page_expectations.rb
added view only tests as another user in existing feature specs
Added  a simple view only tests, this means user who don't have permission won't be able to add product, add test result or edit summary.
> View only permission tests

- psd-web/app/controllers/investigations/activities_controller.rb
- psd-web/app/helpers/activity_helper.rb
- psd-web/app/views/investigations/tabs/_overview.html.erb
- psd-web/spec/features/change_case_visibility_restriction_spec.rb
This adds case restriction status as a row on the case overview, removing the feature from 'add activity'.
I've branched off of #606 to get the new restriction policies for this.
Shows the current restriction status, and if the viewing user has rights to change status, a change link.
Screenshot:
> Add restriction to case overview

- psd-web/spec/features/investigation_edit_spec.rb
1. Monkey patched `should` has been deprecated for years. RSpec 3 has a much better expectation `expect` that does not require monkey patching objects on the fly.
2. Assert content on the page using css selector based `have_link` over `have_content` when we introduced RSpec, it's has been agreed to use specific css selector over `have_content` as they are more robust
> Remove RSpec 2 style expectation

- psd-web/app/models/audit_activity/investigation/update_owner.rb
- psd-web/config/application.rb
- psd-web/spec/requests/health_spec.rb
1. Fix the spec that fails if sidekiq is not running. We want our test suite to avoid depending on other things except databases.
2. Access environment variables configuration via the the standard `Rails.application.config` 
3. Add a spec that was missing.
4. updated `OwnerUpdate#compute_relevant_entities` to avoid lookup into `saved_changes[owner_id]` if it does not exist
> Fix sidekiq healthcheck spec

- psd-web/app/controllers/investigations/ownership_controller.rb
- psd-web/spec/features/change_ownership_for_investigation_spec.rb
The change of owner flash message was showing the previous owner rather than the new owner.
> Fix flash message showing wrong name

- psd-web/app/models/audit_activity/investigation/update_visibility.rb
- psd-web/app/views/investigations/activities/_activity_card.html.erb
- psd-web/app/views/investigations/activities/investigation/_add_allegation.html.erb
- psd-web/app/views/investigations/activities/investigation/_add_enquiry.html.erb
- psd-web/app/views/investigations/activities/investigation/_add_project.html.erb
- psd-web/app/views/investigations/activities/investigation/_complainant.html.erb
- psd-web/app/views/investigations/activities/investigation/_owner.html.erb
- psd-web/spec/features/create_enquiry_as_opss_user_spec.rb
#631 inadvertently changed the styling of activities. This fixes it.
After:
Before:
Other fixes:
* Uses paragraphs where appropriate rather than `<br>`
* Moves complainant type out of restricted area as it's not meant to be hidden.
* Reformats the complainant details to use a single paragraph.
> Fix broken styling on activities

- psd-web/spec/helpers/investigations/display_text_helper_spec.rb
Faker adds HTML characters there are escaped. Such as in this [test](https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/649/checks?check_run_id=708778365).
> Fix flaky test

- psd-web/app/controllers/secondary_authentications_controller.rb
- psd-web/spec/requests/secondary_authentication_spec.rb
[Related errors in our error tracker](https://sentry.io/organizations/beis/issues/1637054689/?environment=prod&project=1329381)
Only users with a secondary authentication user id in their session should be able to access the secondary authentication page.
This restriction aims to avoid the errors being triggered by users/bots directly accession the secondary authentication page instead of being redirected there by an action that required 2FA.
> Restrict secondary authentication page

- psd-web/app/models/audit_activity/investigation/add.rb
- psd-web/app/models/audit_activity/investigation/team_added.rb
- psd-web/app/models/audit_activity/investigation/team_deleted.rb
- psd-web/spec/features/add_activity_entry_spec.rb
- psd-web/spec/forms/edit_investigation_collaborator_form_spec.rb
- psd-web/spec/services/add_team_to_an_investigation_spec.rb
https://trello.com/c/EynEb43M/573-generic-case-updated-emails-incorrectly-being-sent-when-team-added-removed-from-case
Fixes several bugs related to email notifications for a case:
* When a case is created, the [code which creates the audit log activity](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/psd-web/app/models/audit_activity/investigation/base.rb#L4) assumes `User.current` is set, which it is not in our non-feature specs. This set the `source` of that activity to `nil` which meant that the [inherited functionality all the way down in `Activity`](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/psd-web/app/models/activity.rb#L82) would send a 'case updated' email when it never should do. This created false positives in our tests.
* Fixing the above …
> Fix incorrect emails being sent

- .github/workflows/overrides/case_permissions_team.env
- CHANGELOG.md
- psd-web/app/decorators/investigation_decorator.rb
- psd-web/app/policies/investigation_policy.rb
- psd-web/app/views/investigations/tabs/_overview.html.erb
- psd-web/config/locales/en.yml
- psd-web/spec/decorators/investigation_decorator_spec.rb
- psd-web/spec/features/add_activity_entry_spec.rb
- psd-web/spec/features/create_allegation_as_opss_user_spec.rb
- psd-web/spec/features/create_enquiry_as_opss_user_spec.rb
https://trello.com/c/G1tdeHxB/547-2-dont-show-enquiry-contact-details-to-teams-not-involved-in-case
This displays a hint text and conditionally displays the contact details of a complainant only if the user is a member of a team on the case (which may be the owner's team or a collaborating team).
I confirmed with @edwardhorsford that this should also apply to allegations as well as enquiries. The hint text changes accordingly.
There's a bit of existing code duplication on the feature specs which I've made a bit worse - I haven't addressed this as it would need a bit more refactoring of the test and creation of some generic helpers, which wasn't directly related. We can do that in a separate pull request.
> Only display complainant contact details on case summary page to teams added to the case

- psd-web/app/helpers/investigations/visibility_helper.rb
- psd-web/app/models/investigation.rb
- psd-web/app/views/investigations/visibility.html.slim
- psd-web/config/locales/en.yml
This method appears to be unused anywhere and so we can safely remove it.
Also removed the helper it was calling (_in the model_ 😱) by reimplementing functionality with `I18n`.
> Remove redundant method

- psd-web/app/controllers/investigations/ts_investigations_controller.rb
- psd-web/app/models/investigation.rb
- psd-web/spec/factories/collaborations.rb
- psd-web/spec/factories/complainants.rb
- psd-web/spec/factories/corrective_actions.rb
- psd-web/spec/factories/investigations.rb
- psd-web/spec/features/case_permissions_management_spec.rb
- psd-web/spec/helpers/investigations/display_text_helper_spec.rb
- psd-web/spec/models/investigation_spec.rb
- psd-web/spec/requests/add_collaborator_spec.rb
- psd-web/spec/requests/add_comment_spec.rb
- psd-web/spec/requests/edit_collaborator_spec.rb
- psd-web/spec/requests/invalid_wizard_step_spec.rb
- psd-web/spec/requests/investigations/changing_owner_spec.rb
- psd-web/spec/requests/investigations/updating_the_status_of_a_case_spec.rb
- psd-web/spec/requests/investigations/viewing_a_restricted_case_spec.rb
- psd-web/test/controllers/investigations_controller_test.rb
- psd-web/test/fixtures/investigations.yml
- psd-web/test/models/notification_test.rb
This prevents an `Investigation` from being instantiated or saved, since cases should always be an instance of one of its subclasses.
This was primarily to ensure our tests more closely reflect real data; I noticed some slightly odd behaviour when writing a test with an investigation factory rather than an allegation.
This is a small step toward creating a service which is responsible for creating the investigation, setting default data, adding audit log entries and sending emails, rather than callbacks. We can then use that in our tests instead.
> Prevent instantiation of Investigation class

- psd-web/spec/features/record_email_activity_spec.rb
- psd-web/spec/features/record_phone_call_activity_spec.rb
We switched from using `%d %B %Y`  (eg `01 June 2020`) to `'%e %B %Y` (eg ` 1 June 2020`) but forgot to update the tests. This only became apparent on the 1st of the month. :smile:
Had to add an `lstrip` to the tests to strip the leading space, as `%e` uses space-padding, but Capybara collapses multiple whitespaces together.
> Fixes a breaking test caused by a change in date format.

- psd-web/app/views/documents/_document_card.html.erb
We recently seem to have accidentally hardcoded that document previews are *always* restricted. This caused our thumbnail display to break. This fixes it so we pass in using the relevant policies.
> Pass restriction to template

- psd-web/app/views/documents/_document_preview.html.erb
Fix for a bug with missing extension on preview placeholders.
Before:
After:
> Fix for missing extension on placeholder graphic

- psd-web/app/helpers/documents_helper.rb
This improves document link labels, by changing "View XLS document" to "View Excel document", and so on, for known document types.
Also removes some unused helpers.
> Improve document link labels

- psd-web/app/controllers/investigations/view_corrective_actions_controller.rb
- psd-web/app/models/audit_activity/corrective_action/add.rb
- psd-web/app/views/investigations/activities/_activity_card.html.erb
- psd-web/app/views/investigations/corrective_actions/show.html.erb
- psd-web/config/routes.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/support/features/page_expectations.rb
Following on from #668, this adds a new page for viewing "corrective actions" (product recalls, etc). 
This is currently only linked to from the Activity timeline, but will soon be listed and linked to from a "Supporting information" tab, replacing the "Attachments" tab.  Due to existing database model limitations, it is currently only possibly to create the link from the Activity timeline if a file was attached to the corrective action. This can be remedied in a future change.
Activity timeline entry links only to the attachment:
Activity timeline entry links to the corrective action (only if an attachment was added):
New corrective action page:
We have an existing `CorrectiveActionsController` but that uses the `show` action as part of the "add a corrective action" flow. To avoid …
> Page for showing corrective actions

- psd-web/app/validators/phone_validator.rb
- psd-web/spec/features/registration_spec.rb
- psd-web/spec/forms/resend_secondary_authentication_code_form_spec.rb
- psd-web/spec/validators/phone_validator_spec.rb
Numbers with too many digits are being rejected by UK Notify API based in this validation:
https://github.com/alphagov/notifications-utils/blob/652d9bab827238e9fd247bd2d4e273336419d9cd/notifications_utils/recipients.py#L425
Right now these errors are silently happening in the background ([Error tracker issue](https://sentry.io/organizations/beis/issues/1661381821/?project=1329381)) so the user is not aware of them.
This PR will bring a form validation error to the user so the mobile number is rejected in our service form submission instead of being rejected by Notify API in the background.
> Reject mobile phone numbers with too many digits

- psd-web/app/controllers/investigations/supporting_information_controller.rb
- psd-web/app/views/documents/_document_card.html.erb
- psd-web/app/views/documents/_document_card_links.html.erb
- psd-web/app/views/documents/_generic_document_card.html.erb
- psd-web/app/views/documents/_restricted_generic_document_card.html.erb
- psd-web/app/views/investigations/tabs/_supporting_information.erb
- psd-web/config/locales/en.yml
- psd-web/spec/features/supporting_information_tab_spec.rb
[Jira ticket](https://trello.com/c/u4CDPR33/553-3-dont-reveal-generic-attachments-to-teams-not-involved-in-a-case)
Only users belonging to a team that has permissions on the investigation will be able to view the details of the investigation generic attachments when visiting the investigation supporting information tab.
Other users will be aware of the attachment existence but won't be able to view the preview, title or description from them.
(don't mind the preview format showing different extensions, they're different docs):
> Restrict visibility of generic attachments

- psd-web/app/decorators/user_decorator.rb
- psd-web/app/helpers/investigations/user_filters_helper.rb
- psd-web/app/views/investigations/activities/_restricted.html.erb
- psd-web/app/views/investigations/index.xlsx.axlsx
- psd-web/app/views/investigations/ownership/_owner_form.html.slim
- psd-web/app/views/investigations/ownership/_owner_selection.html.slim
- psd-web/app/views/investigations/ownership/confirm.html.erb
- psd-web/app/views/investigations/ownership/select-owner.html.slim
- psd-web/app/views/investigations/show.pdf.slim
- psd-web/app/views/invitations/new.html.erb
- psd-web/app/views/teams/show.html.erb
- psd-web/spec/models/user_spec.rb
This branch is dependent on https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/700 and removes all remaining dependency on `User.current` in calls to `display_name`. Therefore please just look at the last commit in this branch.
> Remove User.current from display name

- psd-web/app/views/investigations/activities/investigation/_automatically_update_owner.html.erb
- psd-web/app/views/investigations/activities/investigation/_update_owner.html.erb
This fixes a missing view template error when trying to show activities of type `AuditActivity::Investigation::AutomaticallyUpdateOwner`.
There's no feature test for the deletion of users (where this activity arises) so we'll need to add one separately. This is a quick fix.
At the moment we need a blank template even if there's nothing to show. Perhaps there is a better way which we can implement later.
> Fix error when trying to display automatically updated case ownership change activity

- CHANGELOG.md
- psd-web/app/helpers/investigations/display_text_helper.rb
- psd-web/app/models/audit_activity/investigation/add.rb
- psd-web/app/models/complainant.rb
- psd-web/app/views/investigations/activities/investigation/_add_project.html.erb
- psd-web/app/views/investigations/activities/investigation/_complainant.html.erb
- psd-web/spec/features/create_allegation_as_opss_user_spec.rb
- psd-web/spec/features/create_enquiry_as_opss_user_spec.rb
- psd-web/spec/support/audit_activity_investigation.rb
https://trello.com/c/3HP9NsVf/554-hide-enquiry-source-contact-details-in-activity-log
This tweaks the logic which determines whether a user can view complainant details on the activity log entry for case created. It now uses the new policy which specifies that the user must be on a team added as a collaborator to the case. Previously, the user had to be in the same team or organisation as the person who created the case.
I've also removed the now-redundant `Complainant#can_be_displayed?` method which was only used elsewhere in the search results text highlighting feature. We are currently discussing how best to improve this feature and the indexing of complainants so I have not changed this.
Note: The copy has not been changed from the existing generic text. I think the copy is probably …
> Only show complainant details on case added activity if user is collaborating on the case

- psd-web/app/helpers/investigations_helper.rb
- psd-web/app/views/investigations/tabs/_activity.html.slim
- psd-web/app/views/investigations/tabs/_supporting_information.erb
- psd-web/spec/features/add_activity_entry_spec.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/add_test_results_spec.rb
- psd-web/spec/features/record_meeting_activity_spec.rb
- psd-web/spec/features/send_alert_spec.rb
- psd-web/test/system/alert_test.rb
Some short term fixes to enable us to deliver this feature branch before the new `Add supporting information` flow is ready.
Changes:
* Link to existing `Add activity` flow from the supporting information tab
* Add link for `Add file attachment` in addition.
* Remove `Add activity` link from `Activity` tab - now always shows `Add comment`
* Change name to `Add supporting information` on case overview tab.
Screenshot:
> Link to add activity flow from add supporting information flow

- psd-web/app/views/documents/_generic_document_card.html.erb
- psd-web/app/views/documents/_restricted_generic_document_card.html.erb
This applies the layout fixes I did in #709 to generic restricted attachments.
After:
Before:
> Apply layout fixes from #709 to restricted attachments too

- psd-web/app/controllers/investigations/corrective_actions_controller.rb
- psd-web/app/decorators/corrective_action_decorator.rb
- psd-web/app/helpers/investigations/corrective_actions_helper.rb
- psd-web/app/views/investigations/corrective_actions/show.html.erb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/case_images_tab_spec.rb
- psd-web/spec/features/supporting_information_tab_spec.rb
- psd-web/spec/helpers/investigations/corrective_actions_helper_spec.rb
- psd-web/spec/models/corrective_action_spec.rb
- psd-web/spec/models/investigation_spec.rb
Ensure that when `CorrectiveAction#measure_type` is `nil` it does not blow up.
1. cleaned up `CorrectiveActionController#show` view by using already existing methods  from the corresponding decorator and added a couple more
2. used a helper to construct the summary list and added test coverage.
> fix corrective action show page

- CHANGELOG.md
- psd-web/app/views/investigations/index.xlsx.axlsx
- psd-web/spec/requests/export_investigations_spec.rb
https://trello.com/c/eHNM3ToZ/588-update-data-export-columns
Removes complainant details and adds owner team/user following recent changes so the owner is correctly represented. If there is no user assigned the column will be empty.
> Change export columns to remove complainant and add case owner team

- psd-web/app/services/change_case_owner.rb
- psd-web/spec/services/change_case_owner_spec.rb
If you change the case owner to a team who were previously added to the case, they currently show up twice, once as the [new] owner and once as a team added to the case.
This fixes that to remove the team as a collaborator when they become an owner.
> Bugfix: remove new owner team as a collaborator if they were one

- psd-web/app/assets/stylesheets/text.scss
- psd-web/app/views/collaborators/index.html.erb
- psd-web/spec/features/case_permissions_management_spec.rb
- psd-web/spec/support/features/page_expectations.rb
https://trello.com/c/cX8VzwTD/532-2-show-label-for-case-creator-if-on-teams-list
Shows a label next to the case owner in the teams list for a case.
> Show a label against the case creator in the case teams list

- .github/workflows/overrides/ add_supporting_information_flow .env
- .github/workflows/review-apps.yml
- doc/deployment.md
Following discussion with the team it was agreed we would change the default behaviour for review apps to use a new isolated database instance. This will increase the time needed to deploy a branch for the first time, but will help resolve issues with data changes in different branches. I have retained the override functionality so that if needed, a shared database instance could be used if one was created or maintained. It also allows us to continue overriding other variables as needed.
> Use isolated database for each review app

- psd-web/app/controllers/investigations/project_controller.rb
This fixes errors caused by `Invalid single-table inheritance type: Investigation::Allegation is not a subclass of Investigation::Project` when attempting to create a project as an OPSS user.
The reason this was happening is because the session key used to store user input in the wizard was shared with that on the Trading Standards creation flow. So if you had previously accessed the Trading Standards creation flow on your browser (regardless of whether this was a different user account or if you completed or abandoned the creation flow) it would fail when accessing the create project flow.
Although the session key was cleared on the `new` action this was too late for the `before_filter :set_investigation`.
The create project flow controller does not inherit from …
> Fix error caused when trying to create a project

- psd-web/app/controllers/investigations/project_controller.rb
- psd-web/app/views/investigations/project/project_details.html.slim
- psd-web/spec/features/create_project_spec.rb
https://trello.com/c/St4Ek73j/642-html-tag-p-showing-up-in-activity-logs-for-opss-projects
Fixes HTML `<p>` tags in the description of the audit activity for project created.
This was caused by what I believe to be unnecessary use of `decorate` on the investigation before it's created. None of the other creation flows use this, and the corresponding feature spec did not check the activity page, so it was not spotted.
I've improved the feature spec to check the activity page.
I have checked on production and the last project was created in April, before metadata was introduced. Therefore there are no affected cases on production, so no data migration is needed to fix anything.
> Fix HTML in project description on case created activity

- CHANGELOG.md
- psd-web/app/models/audit_activity/document/base.rb
- psd-web/app/views/documents/_document_card.html.erb
- psd-web/app/views/documents/_document_preview.html.erb
- psd-web/spec/features/case_images_tab_spec.rb
https://trello.com/c/PZ79IE49/634-images-are-not-supposed-to-be-restricted-for-outside-team-members
Fixes a bug where users on teams not added to the case can't view case images.
The affected template is now only used on case images and business attachments, so there is no need for any access control on the template. Access to restricted cases is already guarded by the controller.
There were no specific tests for this functionality so it was not necessary to modify any existing tests. I don't think we need to add a specific test that the images are visible - generally we only need to add specific tests for things which the user shouldn't be able to see. I added a test for the activity timeline as the behaviour is different depending on whether the attachment is an image or not.
> Allow all users to view case images

- psd-web/app/controllers/investigations_controller.rb
- psd-web/app/policies/investigation_policy.rb
- psd-web/app/policies/user_policy.rb
- psd-web/app/views/investigations/index.html.slim
- psd-web/app/views/searches/show.html.erb
- psd-web/spec/features/invite_user_spec.rb
- psd-web/spec/requests/export_investigations_spec.rb
- psd-web/test/controllers/investigations_controller_test.rb
This change ensures only users with the `psd_admin` role are able to download the cases export spreadsheet. This was always intended by conditionally showing the link, but the actual endpoint was not protected.
> Ensure only admin users can export cases

- psd-web/lib/tasks/add_case_creators_as_collaborators.rake
This updates the data migration task to use the new model for collaborator records.
The data migration adds the team who created the case to the case with edit access, if they’re not currently a collaborator on the case (eg because the owner has been reassigned to another team).
> Update data migration to use new collaborator data model

- psd-web/lib/tasks/add_case_creators_as_collaborators.rake
In theory all cases should have a creator, but this doesn't always seem to be true, at least on staging.
> Fix rake task: Skip cases with no creator team

- CHANGELOG.md
- psd-web/app/models/source.rb
- psd-web/app/models/user.rb
- psd-web/app/models/user_source.rb
- psd-web/app/policies/investigation_policy.rb
- psd-web/spec/requests/investigations/viewing_a_restricted_case_spec.rb
https://trello.com/c/1N8vvk4x/533-2-remove-opss-blanket-ability-to-view-restricted-cases
This removes a user's ability to view a restricted case when their team was not added to the case. Currently a user can view it if they are an OPSS user, or they are in the same organisation as the owner or original creator of the case.
The test coverage for viewing a restricted case was incomplete and didn't cover most of those scenarios; therefore I didn't need to change the tests too much. The current test coverage now accurately reflects the behaviour as implemented.
⚠️ **DO NOT MERGE**: We need to communicate this change to affected users first. Will work with @tobyhughes on this.
> Remove OPSS and creator/owner org users ability to view restricted cases where they are not a collaborator

- psd-web/app/assets/stylesheets/_button.scss
- psd-web/app/assets/stylesheets/_colours.scss
- psd-web/app/assets/stylesheets/_identity-bar.scss
- psd-web/app/assets/stylesheets/main.scss
- psd-web/app/controllers/investigations/actions_controller.rb
- psd-web/app/forms/investigation_actions_form.rb
- psd-web/app/helpers/investigations_helper.rb
- psd-web/app/views/investigations/_pages_top.html.erb
- psd-web/app/views/investigations/actions/index.html.erb
- psd-web/config/locales/en.yml
- psd-web/config/routes.rb
- psd-web/spec/factories/investigations.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/send_alert_spec.rb
- psd-web/spec/forms/investigation_actions_form_spec.rb
- psd-web/spec/support/features/page_expectations.rb
- psd-web/test/controllers/investigations/products_controller_test.rb
- psd-web/test/system/alert_test.rb
This adds some contextual buttons to the case bar. 
The content and destination of these buttons varies according to the status of the case, and the role of the user’s team in relation to it.
A future story will enhance buttons with javascript to a dropdown menu, avoiding the need to visit the second page.
> Add buttons to case bar

- psd-web/app/assets/stylesheets/_form.scss
> Move case action buttons closer together

- psd-web/config/initializers/lograge.rb
Adding `organisation_id` to logs will help us to make aggregation better.
> Add organisation id

- psd-web/app/models/collaboration/access.rb
- psd-web/app/views/collaboration/access/read_onlies/_read_only.erb
- psd-web/spec/factories/investigations.rb
- psd-web/spec/features/add_corrective_action_spec.rb
- psd-web/spec/features/case_permissions_management_spec.rb
- psd-web/spec/features/change_case_visibility_restriction_spec.rb
- psd-web/spec/features/collaborations_spec.rb
- psd-web/spec/features/supporting_information_tab_spec.rb
- psd-web/spec/support/features/page_expectations.rb
- psd-web/spec/support/shared_contexts/read_only_team_and_user.rb
This PR adds a few more test to verify that a team with read only access can view all the details of a case but not edit them.
for testing:
I've added `OPSS Operational support unit` to this case https://psd-pr-753.london.cloudapps.digital/cases/2006-0017 as read only access
> add view to team listing for read only teams

- .github/workflows/review-apps-delete.yml
When deleting the review app, we should also delete its associated database, now that we have a 1 to 1 mapping between review apps and databases.
> Delete database when deleting review app

- psd-web/db/migrate/20200616142120_rename_edit_access_to_access_edit.rb
Fixes a typo in a migration file which has caused a few issues locally and deploying onto staging. I have cleaned up the data manually on staging and production so it's not going to run again, but I'd recommend running it locally again to prevent errors.
> Fix typo in migration

- psd-web/app/controllers/collaborators_controller.rb
- psd-web/app/forms/edit_investigation_collaborator_form.rb
- psd-web/app/models/collaboration.rb
- psd-web/app/models/investigation.rb
- psd-web/app/services/change_case_owner.rb
- psd-web/lib/tasks/add_case_creators_as_collaborators.rake
- psd-web/spec/forms/edit_investigation_collaborator_form_spec.rb
- psd-web/spec/requests/edit_collaborator_spec.rb
This fixes an issue I discovered when refactoring the `EditInvestigationCollaboratorForm` class. It is possible to remove the case owner due to the class inheritance of `Collaboration::Access::Owner` inheriting from `Collaboration::Access::Edit`.
This change ensures that only `Collaboration::Access::Edit` and `Collaboration::Access::Readonly` can be edited/removed.
Previously, `Collaboration::Access::ReadOnly` was not editable or removable, and teams with read-only access were still listed in the 'add collaborator' form. These small fixes are a small step in the related story to implement view-only permissions.
Also removed the duplicate `edit_collaborations` association which was already implemented as `edit_access_collaborations`.
I am in the process of refactoring …
> Prevent removal of case owner

- psd-web/app/forms/risk_assessment_form.rb
- psd-web/app/models/date_parser.rb
- psd-web/config/initializers/active_model_type.rb
- psd-web/lib/active_model/types/govuk_date.rb
This makes it simpler to add the govuk date coming from the govuk multiple input form.
now in form object just declare the type in at the attribute level:
```ruby
class AFormWithAGovUKDate
attribute :date_receive, :govuk_date
end
```
> add a custom ActiveModel::Type::GovUKDate

- psd-web/app/services/update_corrective_action.rb
- psd-web/spec/services/update_corrective_action_spec.rb
When a team other than the case creator team is assigned to the case sending the email would throw an error
> fix update corrective action

- app/controllers/investigations/risk_assessments_controller.rb
- app/controllers/investigations/update_case_risk_level_from_risk_assessment_controller.rb
- app/decorators/investigation_decorator.rb
- app/views/investigations/risk_level/show.html.erb
- config/locales/en.yml
- spec/factories/risk_assessments.rb
- spec/features/set_investigation_risk_level_spec.rb
This adds some additional content to the "Set case risk level" page to remind users about any risk assessments that have been added to the case, and their risk levels.
https://trello.com/c/wOCDXNxu/605-2-add-risk-assessment-content-to-case-risk-level-page
> Add content to set case risk level page

- app/views/investigations/risk_level/show.html.erb
This allows the case tags to appear alongside it on the right.
> <img width="1218" alt="Screenshot 2020-08-14 at 15 46 35" src="https://user-images.githubusercontent.com/30665/90261978-9872ee00-de45-11ea-96c1-904dd60fc741.png">
> <img width="1224" alt="Screenshot 2020-08-14 at 15 46 53" src="https://user-images.githubusercontent.com/30665/90261996-9f016580-de45-11ea-874b-e7f324cfb406.png">
> Move back link within one-half column

- config/webpacker.yml
After the last upgrade webpacker started logging a deprecation warning:
`The resolved_paths option has been deprecated. Use additional_paths instead.`
> Fix webpacker deprecation warning

- app/decorators/investigation_decorator.rb
- app/helpers/investigations_helper.rb
- app/views/investigations/tabs/_overview.html.erb
- config/locales/en.yml
- spec/decorators/investigation_decorator_spec.rb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/features/set_investigation_risk_level_spec.rb
This update adds detail about any risk assessments added to the case to the Overview tab, within the "Risks and issues" section.
Trello card: https://trello.com/c/4A9l6dvg/635-2-add-risk-assessment-to-overview-risk-section
I refactored the `risk_and_issues_list` decorator method to a `risks_and_issues_rows` helper method, to avoid generating HTML from the decorator, and to be more consistent with the existing `about_the_case_rows` helper method. Some of the conditions were also delegated to the locale file lookup using the pluralization feature (where the `count` value is used to map to different keys).
Links to the "Add risk assessment" flow (if you have permission to do so)
> <img width="831" alt="Screenshot 2020-08-19 at 11 44 04" …
> Add risk assessments to case overview

- app/controllers/investigations/risk_assessments_controller.rb
- app/decorators/audit_activity/risk_assessment/risk_assessment_updated_decorator.rb
- app/decorators/corrective_action_decorator.rb
- app/forms/risk_assessment_form.rb
- app/helpers/application_form_builder.rb
- app/helpers/investigations_helper.rb
- app/helpers/risk_assessment_helper.rb
- app/models/audit_activity/risk_assessment/risk_assessment_updated.rb
- app/services/update_risk_assessment.rb
- app/views/investigations/activities/risk_assessment/_risk_assessment_updated.html.erb
- app/views/investigations/risk_assessments/_fields.html.erb
- app/views/investigations/risk_assessments/edit.html.erb
- app/views/investigations/risk_assessments/show.html.erb
- config/routes.rb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/features/edit_a_risk_assessment_spec.rb
- spec/forms/risk_assessment_form_spec.rb
- spec/services/update_risk_assessment_spec.rb
- spec/support/features/page_expectations.rb
This adds ability to edit and update risk assessments.
The form is identical to the "Add risk assessment" form, except for the title, and the file upload, which is contained within a "Replace this file" reveal link.
Upon updating, if the risk level is not the same as the case risk level, the user will be prompted to set (or change) the case risk level.
An activity timeline entry is generated, and notification emails are sent, if any of the of the fields are changed (but not if the form is saved with no changes).
Trello card: https://trello.com/c/BDKhRWce/582-5-edit-risk-assessment
> Edit risk assessments

- app/models/audit_activity/risk_assessment/risk_assessment_updated.rb
- spec/features/edit_a_risk_assessment_spec.rb
- spec/fixtures/files/risk_assessment.txt
- spec/models/audit_activity/risk_assessment/risk_assessment_updated_spec.rb
https://trello.com/c/Zx9Q2pIm/724-edit-risk-assessment-leave-activity-tab-in-error-state
This fixes [an exception](https://sentry.io/organizations/beis/issues/1858324804/?environment=staging&project=1329381&query=is%3Aunresolved) when displaying the audit activity for an updated risk assessment where the assessed on date had changed. The view was expecting a `Date` object but the model was returning a `String`.
Generally we are missing unit test coverage on this activity model which needs further backfilling. I've added unit tests for the relevant method, and modified the feature spec to test changing the date as well.
Steps to reproduce:
1. Add a risk assessment to a case
1. Edit the risk assessment and change the assessed on date
1. Go to the case activity page
> Fix error when displaying activity for risk assessment updated

- .rubocop.yml
- Gemfile
- app/controllers/collaborators_controller.rb
- app/helpers/investigations/user_filters_helper.rb
- app/models/audit_activity/investigation/team_added.rb
- app/models/audit_activity/investigation/team_deleted.rb
- app/models/concerns/deletable.rb
- app/models/team.rb
- app/models/user.rb
- app/services/add_team_to_case.rb
- app/services/change_case_owner.rb
- app/services/delete_team.rb
- app/services/remove_team_from_case.rb
- app/views/investigations/ownership/_owner_form.html.slim
- config/locales/en.yml
- db/migrate/20200911142816_add_deleted_at_to_teams.rb
- db/schema.rb
- doc/tasks.md
- lib/tasks/delete_team.rake
- spec/factories/teams.rb
- spec/features/add_team_to_case_spec.rb
- spec/features/change_ownership_for_investigation_spec.rb
- spec/features/filter_investigations_spec.rb
- spec/models/team_spec.rb
- spec/services/add_team_to_case_spec.rb
- spec/services/change_case_owner_spec.rb
- spec/services/delete_team_spec.rb
- spec/services/remove_team_from_case_spec.rb
https://trello.com/c/FRRtOhuq/668-5-absorb-opss-product-safety-enforcement-into-opss-enforcement
This allows us to delete a team from service.
When a team is deleted:
- all users on that team are transferred to another designated team. Any users that own a case retain ownership. All user roles are transferred to the new team
- all case collaborations for that team are transferred to another designated team. If the team owns any cases, the designated team will inherit ownership.
- audit activity is generated as normal - except when a user on the deleted team is the owner of a case. In this event we add an extra activity showing the team ownership has changed
- no emails are sent
- the team will no longer be in the filter cases list
- the team will no longer appear in the list to transfer …
> Ability to delete a team

- app/services/delete_team.rb
- spec/services/delete_team_spec.rb
https://trello.com/c/FRRtOhuq/668-8-absorb-opss-product-safety-enforcement-into-opss-enforcement
Adds a test and fix for a scenario where a user on the team to be deleted is the owner of a case, and the new team is already a collaborator on that case.
We do already have a similar inverse method [Collaboration::Access::OwnerTeam#swap_to_edit_access!](https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/models/collaboration/access/owner_team.rb#L4). I did consider adding a similar method to `Collaboration::Access::Edit` however normally we would expect any other owner collaborations to be destroyed. In this instance we want to keep the `OwnerUser` as-is and only change the `OwnerTeam`. I felt this was too specific to be useful outside of this service and might be confusing or …
> Fix bug when deleting a team

- db/migrate/20200501105429_rename_update_assigne_activities.rb
This fixes the following error:
```
TypeError: superclass mismatch for class Activity
```
...caused by the redefined `Activity` class having a different superclass from the one defined in `models/activity.rb`.
Not quite sure why this didn't happen before, but presumably it's related to either the Ruby or Rails upgrades.
> Migration fix: superclass should be ApplicationRecord

- app/controllers/investigations_controller.rb
- app/models/investigation.rb
- spec/features/filter_investigations_spec.rb
- spec/support/case_list_matcher.rb
https://trello.com/c/1UONIGDB/757-investigate-indexing-on-most-recently-created-sort
Fixes case ordering on the case list pages. This affected the ordering of all results within a page, forcing them to be reordered by `updated_at` regardless of relevance or other sort options selected. Usage of `default_scope` is generally discouraged because of gotchas like this, and in fact was redundant anyway because of the implementation of search in the controller.
I added some tests around case sorting and fixed the export controller action so that it ordered correctly, removing some redundant code.
> Fix case ordering caused by default_scope override

- app/controllers/investigations/ownership_controller.rb
- app/controllers/investigations_controller.rb
- app/helpers/investigations_helper.rb
- app/models/investigation.rb
- app/models/user.rb
- app/views/investigations/ownership/_owner_form.html.erb
- spec/models/investigation_spec.rb
- spec/models/user_spec.rb
- spec/requests/investigations/changing_owner_spec.rb
Technical debt remediation
Removes some usage of `User.current` which we are actively eliminating due to various unexpected behaviours. This leaves only some of the activity models using it, which are actively being refactored.
Removes some code which is apparently redundant relating to selecting previous owners of a case on the change ownership form. This code does not appear to be integrated anymore (see 4772e88d0f617669fb8204c07b20b522c2575504).
> Refactor owner form

- config/routes.rb
Resolves a long-standing issue with Sidekiq::Web returning `Forbidden` errors when performing operations such as kill/delete.
Our application still uses the outdated secrets approach to storing the secret key, so the previous code always returned `nil`. This is the correct approach to read the secret key as described in the [documentation](https://api.rubyonrails.org/classes/Rails/Application.html#method-i-secret_key_base).
> Fix Sidekiq::Web showing Forbidden errors

- spec/services/change_case_owner_spec.rb
Fixes a flaky spec which I have seen a few times today, for example: https://github.com/UKGovernmentBEIS/beis-opss-psd/runs/1314426997. The issue is that the order of the collection was sometimes different.
> Fix flaky spec

- app/controllers/investigations/ts_investigations_controller.rb
- spec/requests/msa_create_case_wizard_spec.rb
https://trello.com/c/Wyv846Fk/694-interim-journey-urls-when-accessed-directly-without-session-data-then-it-should-return-to-dashboard
This fixes a bug whereby a user could access a page in the MSA case creation flow directly without having started the wizard. This could sometimes render an error if assumed session data was missing, or otherwise create a broken state with unexpected results.
This is an interim quick fix before refactoring the offending controller completely.
Rather than redirecting to the dashboard I have chosen to redirect to the first wizard page. Redirecting to the `new` action is better than redirecting to the first step using the Wicked helper because it sets up the session data in the call to `clear_session`. This is important even though it's not obvious.
> Bug fix: Accessing a MSA case creation wizard step page before starting from the beginning

- .github/workflows/rspec.yml
The Coveralls GitHub action appears to have some issues when running multiple jobs concurrently, e.g. https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/816/checks?check_run_id=1359213763
I suspect this is related to https://github.com/coverallsapp/github-action/issues/59
For now this PR disables the reporting until it can be resolved.
> Disable Coveralls reporting

- README.md
The Minitest suite was deprecated and removed so this badge is no longer relevant.
> Remove Minitest badge from README

- .github/workflows/rspec.yml
- README.md
- codecov.yml
- spec/rails_helper.rb
Implements code coverage reporting with [CodeCov](https://codecov.io/), replacing the previous Coveralls integration.
There were some issues with Coveralls' GitHub Action not working in parallel with other pull requests (throwing errors), reporting changes in coverage incorrectly, and necessitating two test runs per push in order to get PR comments.
I have tested CodeCov's implementation and it seems to resolve most of the issues. I haven't been able to test whether it works in parallel with multiple PRs. This will emerge when we use it in anger.
The main disadvantage compared with Coveralls that I have identified is that in order to prevent premature reporting it is necessary to manually specify the number of parallel test runs (2). Coveralls has a separate 'finish' action which seems …
> Upload coverage report to CodeCov

- .github/workflows/deploy.yml
- .github/workflows/review-apps-delete.yml
- .github/workflows/review-apps.yml
Replaces usage of `add-path` in GitHub Actions as described in:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Resolves warning messages seen in action annotations.
> Replace usage of deprecated add-path in GitHub workflows

- config/initializers/sprockets.rb.rb
This is a temporary fix until https://github.com/sass/sassc-ruby/issues/207 is
resolved
This should stop the segfault from happening upon deploy
> Avoid sprocket building assets concurrently

- db/migrate/20201110124109_flag_as_counterfeit_products.rb
- db/schema.rb
21 products contains the word counterfeit in various fields. This sets the `authenticity` to `counterfeit`.
> migrate counterfaited product flag

- app/forms/invite_user_to_team_form.rb
- spec/forms/invite_user_to_team_form_spec.rb
Prior to this commit whitelisting emails is enabled we see errors being raised if an incorrectly formatted email is entered. We did not see this issue raised in tests, nor could we replicate it in development, because `EMAIL_WHITELIST_ENABLED` is set to false.
The issue is that Mail::Field::IncompleteParseError is raised but not handled.
This commit rescues from this error and adds the whitelisted domain error to our form.
Note: This will raise both an error for incorrectly formatted error and an error for non-whitelisted email. The other option I considered was to return from `#email_domain_must_be_whitelisted` if there were existing validation errors, but while I believe that `validates` run before `validate` I can't seem to find any concrete documentation on that, and so I do not want …
> Fix email validation bug when whitelisting is turned on

- app/controllers/investigations/ownership_controller.rb
Fixes a N+1 query performance issue on the case ownership form page.
Example Scout report at https://scoutapm.com/apps/156303/endpoints/Q29udHJvbGxlci9pbnZlc3RpZ2F0aW9ucy9vd25lcnNoaXAvc2hvdw==/trace/1565238595?time=e%3A2020-11-11T00%3A00%3A00-08%3A00%2Cd%3A7-day%2Cc%3Anone
> Fix N+1 query performance issue on ownership selection form

- app/controllers/investigations_controller.rb
Fixes a N+1 query performance issue on the case ownership form page.
Example Scout report at https://scoutapm.com/apps/156303/endpoints/Q29udHJvbGxlci9pbnZlc3RpZ2F0aW9ucy9pbmRleA==/trace/1652083634?section=timing&nplusone=2879.029193
> Fix N+1 query performance issue on case export

- app/helpers/application_helper.rb
- app/models/investigation/allegation.rb
- app/models/investigation/enquiry.rb
- app/views/investigations/creation_flow/allegation_details.html.slim
- app/views/investigations/creation_flow/enquiry_details.html.slim
- app/views/investigations/products/new.html.erb
- app/views/investigations/record_corrective_actions/details.html.erb
- app/views/investigations/risk_assessments/edit.html.erb
- app/views/investigations/risk_assessments/new.html.erb
- app/views/investigations/test_results/new.html.erb
- app/views/products/edit.html.erb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/features/add_corrective_action_spec.rb
- spec/features/add_product_spec.rb
- spec/features/add_test_results_spec.rb
- spec/features/create_allegation_as_opss_user_spec.rb
- spec/features/create_enquiry_as_opss_user_spec.rb
- spec/helpers/application_helper_spec.rb
This PR started from [this ticket](https://trello.com/c/swtimLYe/806-enquiry-form-error-summary-to-be-in-correct-order) which related to incorrect ordering of errors on the enquiry form, but also includes fixes for incorrectly ordered errors on (hopefully) all the other forms that have this issue (which can be found in the comments on the card).
- Take the logic from the cosmetics app that allows us to optionally specify an ordering of errors each time we call `#error_summary` in a view.
- Add custom ordering to the views in question that already use `#error_summary`
- Change specified views that do not use `#error_summary` already to use it, and give custom ordering.
- Tests.
> Error ordering to match field ordering on forms

- app/decorators/concerns/formated_description.rb
- app/decorators/concerns/formatted_description.rb
- app/decorators/investigation_decorator.rb
- app/decorators/product_decorator.rb
- spec/decorators/investigation_decorator_spec.rb
- spec/decorators/product_decorator_spec.rb
- spec/support/shared_examples/simple_format.rb
When a description is empty the `simple_format` helper output an empty `<p/>`.
> fix empty paragraphs when empty description

- app/controllers/documents_flow_controller.rb
- config/locales/en.yml
- spec/features/add_attachment_to_a_business_spec.rb
- spec/features/add_attachment_to_a_case_spec.rb
- spec/features/add_attachment_to_a_product_spec.rb
- spec/features/case_images_tab_spec.rb
- spec/support/features/page_expectations.rb
https://trello.com/c/hU0jTM3S/290-no-confirmation-message-banner-after-attachment-is-added
Shows a confirmation message when an attachment is created. Note we currently have no way of knowing if the file was actually processed and not corrupt or invalid, so this is misleading in some circumstances. We have a story in the backlog to correct this.
I have also added feature specs around adding attachments to cases, products and businesses.
> Show a success message when adding an attachment. Add feature specs

- .env.development.example
- app/controllers/investigations/risk_assessments_controller.rb
- app/controllers/investigations/ts_investigations_controller.rb
- app/forms/risk_assessment_form.rb
- app/helpers/application_helper.rb
- app/services/update_risk_assessment.rb
- app/views/application/_upload_file_component.html.erb
- app/views/investigations/active_storage/blobs/_blob.html.erb
- app/views/investigations/risk_assessments/_form_fields.html.erb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/features/report_product_spec.rb
- spec/forms/risk_assessment_form_spec.rb
- spec/rails_helper.rb
This solves the problem whereby the attachment is lost upon validation error. 
I've used the same pattern we in other controller, unifying the interface: `FormObject#cache_file!` `FormObject#load_attribute_name_file` 
I've also created a `app/views/application/_upload_file_component.html.erb ` so that partial could be reused wherever we have file to upload.
> fix risk assessment uploaded document cleared when create/edit form has a validation error

- app/views/products/_form.html.erb
This PR removes some copy as requested on this card: https://trello.com/c/kQsb5En4/813-remove-extra-hint-text-from-product-name-field
It also adds `(if branded)` to the product brand question as per this card: https://trello.com/c/simjOA1T/804-update-product-brand-field
> Change copy on product form

- db/seeds.rb
This PR adds a user to our seed file that does not have `opss_user` role. We currently do not have a this kind of user and this will be useful to test the different flow available to trading standards users.
> Add user without opss_user role to seed file

- app/views/investigations/ts_investigations/_repeatable_info.html.erb
- app/views/investigations/ts_investigations/corrective_action.html.erb
- app/views/investigations/ts_investigations/product.html.erb
- app/views/investigations/ts_investigations/risk_assessments.html.erb
- app/views/investigations/ts_investigations/test_results.html.slim
This PR ensures the ordering of errors for TS users matches the order in which the information is requested on the form by providing the required error ordering to  `#error_summary`.
https://trello.com/c/nJTg0LCO/814-correctly-order-error-summaries-for-ts-journies
> Correct ordering of errors for TS flow

- app/views/investigations/ts_investigations/_repeatable_info.html.erb
- spec/features/report_product_spec.rb
- spec/support/features/page_expectations.rb
This fixes a regression bug introduced by https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1031
When there is a validation error on user-supplied input, the page is supposed to display again showing validation errors. It was throwing a 500 error as seen here https://sentry.io/organizations/beis/issues/2042190291/?project=1329381.
I have improved the test coverage to cover this behaviour to prevent it reoccurring.
> Fix for repeating info pages in TS flow when there is a validation error

- app/controllers/investigations_controller.rb
- app/views/investigations/index.xlsx.axlsx
- db/migrate/20201124121612_add_date_closed_to_investigations.rb
- db/schema.rb
- lib/tasks/backfill_date_closed.rake
- spec/requests/export_investigations_spec.rb
- spec/requests/investigations/updating_the_status_of_a_case_spec.rb
Adding date_closed field to `investigations` so that we do not have to query activities and get slow/unreliable results when attempting to find out when an investigation was closed. Also add additional fields to the CSV export.
- Migration to add `date_closed` to investigations
- Change in controller to populate this field.
- Adding test coverage for this change
- Add fields to csv export
- Add tests to cover csv export changes
- Rake task to backfill field for existing closed investigations
> Add date closed to investigation

- app/controllers/investigations/ts_investigations_controller.rb
- spec/features/report_product_spec.rb
This fixes a  bug reported by users when the application is running on production.
I was able to reproduce the error on staging and on review apps. It was not possible to reproduce in development or test modes locally or in CI.
The problem was that the product is instantiated as a child of `@investigation` and assigned to `@product` before it is saved in a later call to `CreateCase`, which calls `save` on the parent Investigation. See https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/controllers/investigations/ts_investigations_controller.rb#L615-L616. The product is therefore saved as well, but this state is not automatically updated in the controller.
Later, when images are attached to the product, it defers the saving of the attachments until the product is saved. This …
> Fix images not being attached to products on TS case creation flow on hosted environments

- app/views/businesses/index.html.erb
- app/views/investigations/_heading.html.erb
- app/views/products/index.html.erb
https://trello.com/c/AtLllGyL/591-count-of-search-results-all-tabs-is-wrong
Fixes the total search result count shown in the top left of the cases, businesses and products pages not reflecting the total number of matches. Instead it was showing the number of results on the current page.
Also fixes the count not being output on the product search results page.
> Fix total search results count

- app/controllers/investigations/ts_investigations_controller.rb
- app/controllers/products_controller.rb
- app/decorators/product_decorator.rb
- app/forms/product_form.rb
- app/helpers/products_helper.rb
- app/models/product.rb
- app/services/add_product_to_case.rb
- app/views/investigations/products/new.html.erb
- app/views/investigations/ts_investigations/product.html.erb
- app/views/products/_form.html.erb
- app/views/products/edit.html.erb
- config/locales/en.yml
- db/migrate/20201125160042_add_affected_units_status_and_number_of_affected_units_to_products.rb
- db/migrate/20201125171036_add_affected_units_status_and_number_of_affected_units_to_products.rb
- db/schema.rb
- spec/decorators/product_decorator_spec.rb
- spec/factories/products.rb
- spec/features/add_product_spec.rb
- spec/features/create_allegation_as_opss_user_spec.rb
- spec/features/edit_a_product_spec.rb
- spec/features/report_product_spec.rb
- spec/features/update_product_details_spec.rb
- spec/forms/product_form_spec.rb
- spec/support/product_helper.rb
https://trello.com/c/rjd0MTN9/203-5-add-how-many-units-are-affected-to-the-product-page
- Add :affected_units_status, :number_of_affected_units fields to products table.
- Add units affected question on the product form below the counterfeit question.
- Show answer on summary pages
- Add tests
##Screenshots
> Add 'how many units are affected?' to the product page

- spec/features/sign_in_spec.rb
This fixes a surprisingly common randomly failing spec (and the only one I am aware of now).
When the user's OTP code is generated it can sometimes be the same value when reversed, e.g. `12321`. This test was therefore not reliable, so I have ensured the OTP code will always be a known value for this spec, in exactly the same way the subsequent spec does.
> Fix randomly failing spec where OTP code is the same when reversed

- app/views/investigations/index.xlsx.axlsx
- spec/requests/export_investigations_spec.rb
https://trello.com/c/d2PJaeag/844-export-validation-status
Add the date_validated field to the csv export to show when the investigation had it's risk level validated.
> Add risk validation field to export

- spec/features/add_product_spec.rb
- spec/features/create_allegation_as_opss_user_spec.rb
- spec/features/edit_a_product_spec.rb
- spec/features/report_product_spec.rb
Fixes randomly failing specs introduced by a last minute change in #1081.
I did not catch these before as the specs data is randomised.
> Fix randomly failing specs related to product markings

- manifest.review.yml
- manifest.yml
This is a minor update which only bumps the RubyGems version to 3.2.1.
See https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.28 for full details.
Run `gem update --system '3.2.1'` locally to reproduce this setup.
> Bump CloudFoundry Ruby buildpack to v1.8.28

- Gemfile.lock
Bumps the version number following RubyGems and Bundler version updates in https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1099
> Update bundler version in Gemfile.lock to reflect new CloudFoundry Ruby buildpack

- app/models/role.rb
- app/models/team.rb
- app/models/user.rb
- app/models/user_role.rb
- app/services/create_organisation_with_team_and_admin_user.rb
- app/services/invite_user_to_team.rb
- db/migrate/20201230115058_change_user_roles_to_roles.rb
- db/migrate/20201230134737_clean_up_roles.rb
- db/schema.rb
- db/seeds.rb
- manifest.review.yml
- spec/factories/roles.rb
- spec/factories/teams.rb
- spec/factories/users.rb
- spec/features/admin_spec.rb
- spec/features/validate_risk_level_spec.rb
- spec/models/role_spec.rb
- spec/models/user_spec.rb
- spec/requests/investigations/validate_risk_level_spec.rb
- spec/services/invite_user_to_team_spec.rb
https://trello.com/c/mdnO2nMb/860-5-team-roles
Allows users to inherit the roles of their team.
This renders the `opss_user` role and the juggling of it for new users redundant, as we can set the role on the OPSS teams instead, and users will inherit this automatically. I have added a migration for this.
I have also migrated the `risk_level_validator` role to the relevant team. Currently we only have one team with this role, and all of their users have this role.
To be deployed out of hours due to changes to the user roles data and schema which might temporarily affect active users for a short time during deployment.
> Team roles

- app/views/investigations/ts_investigations/_repeatable_info.html.erb
- spec/features/report_product_spec.rb
https://trello.com/c/7daGEouo/739-accessibility-issue-on-this-corrective-action-page-in-ts-case-creation-flow
When no radio is checked, ensures the first radio field is highlighted when the user clicks the error message in the error summary.
> Fix accessibility issue on corrective actions form in TS flow

- app/decorators/product_decorator.rb
- app/forms/product_form.rb
- app/helpers/products_helper.rb
- app/services/add_product_to_case.rb
- app/views/products/_form.html.erb
- db/migrate/20210104153742_add_customs_code_to_product.rb
- db/schema.rb
- spec/features/add_product_spec.rb
- spec/features/edit_a_product_spec.rb
- spec/features/report_product_spec.rb
https://trello.com/c/6pBWKRqW/854-3-add-customs-code-field-to-product-page
Add a text input for the user to add customs code to a product.
> Customs codes new

- Gemfile.lock
- app/controllers/investigations_controller.rb
Fixes a Brakeman warning, and improves the controller so that other request methods other than `GET` will not trigger an update erroneously.
This really needs refactoring properly to a separate controller.
> Resolve Brakeman warning (and improve resilience)

- db/migrate/20210125111313_fix_test_result_audit_activity_metadata.rb
Fixes some issues with the migration against production data. Two activities reference filenames which were not unique. In this case both of them were attached to the original activity so we can resolve them that way. Unfortunately it was not possible to resolve all of them this way, as many of the blobs were `nil`. Hence all the extra file resolution code needed.
Also, we do not need to attempt to resolve every file if there are multiple updated activities. We only need the one that was originally attached.
> Fix migration against production data

- app/controllers/products_controller.rb
- app/decorators/product_decorator.rb
- app/decorators/products_decorator.rb
- app/helpers/products_helper.rb
- app/policies/product_policy.rb
- app/views/products/index.html.erb
- config/initializers/csv_renderer.rb
- spec/decorators/product_decorator_spec.rb
- spec/decorators/products_decorator_spec.rb
- spec/features/export_products_spec.rb
- spec/policies/product_policy_spec.rb
https://trello.com/c/hq74CuGh/901-csv-export-of-product-data
https://trello.com/c/5eW7fDI2/872-add-product-details-export
https://trello.com/c/2x6xL2gG/228-allow-users-to-export-product-information
I decided to make this a re-usable feature rather than a one-off, since this has been on the backlog for a while and didn't take long, and there is a need to do this regularly.
I decided to export products as a CSV rather than in Excel format as elsewhere, since CSV is more interoperable, simpler, and we are not using any specific features. The implementation used here will allow an easy switchover to CSV for the cases export in a future piece of work.
As with export of cases, if a user has the `psd_admin` role they will see a link at the bottom of the products listing which will allow them to …
> Allow export of products as CSV

- Gemfile.lock
- docker/web/Dockerfile
- manifest.review.yml
- manifest.yml
Bumps the Ruby buildpack to the latest version 1.8.31 as per https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.31
Consequently the Bundler version has been updated which resolves an error caused by a previous dependency update bumping the Bundler version erroneously.
> Bump CloudFoundry Ruby buildpack and dependencies

- app/controllers/investigations/corrective_actions_controller.rb
- app/forms/corrective_action_form.rb
- config/locales/en.yml
- spec/features/add_corrective_action_spec.rb
- spec/forms/corrective_action_form_spec.rb
- spec/support/shared_contexts/add_corrective_action_context.rb
https://trello.com/c/BMudIxj2/928-corrective-action-without-product-returns-422-error
It appears this validation was not implemented on the form object.
> Show an error message on the add corrective action form if no product is selected

- app/models/user.rb
- app/views/teams/show.html.erb
- spec/features/invite_user_spec.rb
- spec/features/team_spec.rb
- spec/models/user_spec.rb
https://trello.com/c/8cqGiWhN/521-resend-link-invite-should-not-displayed-once-account-set-up-is-complete
Before this change, if a user received an email invite and entered their details, but signed out before accepting the declaration then the inviting user had the option to resend an email invitation. This is not what we want as it could confuse the user, and possibly cause them to sign up multiple accounts.
This change only shows the 'resend invitation' button if the user has not yet visited the site and entered in their necessary details.
> Resend link invite bug

- db/migrate/20210223114010_fix_corrective_action_audit_activity.rb
- db/schema.rb
back populate corrective action id in audit activity.
This only addresses audit activities for which we can find the corrective action
I will address the others in a separate PR
> populate missing corrective action id in corrective action added audit

- db/migrate/20210223151528_fix_duration.rb
- db/migrate/20210223155926_fix_measure_type.rb
- db/schema.rb
Couple fixes: 
1. previous migration migrated `measure_type` under the key measure and used the capitalised value. This now migrated to the correct key and the downcased value.
2. Downcase values for duration
> fix duration and measure type ƒor corrective action added audit

- app/controllers/investigations/test_results_controller.rb
- app/controllers/investigations/ts_investigations_controller.rb
- app/decorators/test/result_decorator.rb
- app/forms/test_result_form.rb
- app/helpers/tests_helper.rb
- app/models/audit_activity/test/result.rb
- app/models/audit_activity/test/test_result_updated.rb
- app/services/add_test_result_to_investigation.rb
- app/services/update_test_result.rb
- app/views/investigations/activities/test/_result.html.erb
- app/views/investigations/activities/test/_test_result_updated.html.erb
- app/views/investigations/test_results/_form.html.erb
- app/views/investigations/test_results/new.html.erb
- config/locales/en.yml
- db/migrate/20210217142322_add_failure_details_to_tests.rb
- db/schema.rb
- spec/features/add_test_results_spec.rb
- spec/features/edit_test_result_spec.rb
- spec/features/report_product_spec.rb
https://trello.com/c/bJzV65vE/897-5-add-conditional-reveal-text-area-to-failed-test-result
Add a conditionally revealed text box so that users can enter information about failed text results
> Test result fail box

- app/controllers/investigations/ownership_controller.rb
- app/views/investigations/ownership/_owner_form.html.erb
- app/views/investigations/ownership/confirm.html.erb
- app/views/investigations/ownership/select-owner.html.erb
- spec/features/change_ownership_for_investigation_spec.rb
- spec/requests/investigations/changing_owner_spec.rb
https://trello.com/c/18nh0SjX/944-500-error-on-change-case-owner-form-when-submitted-incomplete
Bug fix for the form when validation errors are present.
Example exception thrown:
https://sentry.io/organizations/beis/issues/2246201384
In this case it appears the user submitted the form having selected 'someone in your team' without selecting a user from the dropdown.
The controller and view were not set up correctly to display the relevant error. This is now fixed.
I have also expanded the relevant feature spec to cover error handling.
Note: there is another bug with this form where the previous input is not pre-filled when showing errors. For example, select 'Someone in your team' but do not select anything from the dropdown. 'Someone in your team' is no longer checked. I think this would …
> Fix change case owner form throwing exception when there are validation errors

- .github/workflows/code-style.yml
- .github/workflows/rspec.yml
- .github/workflows/security-warnings.yml
- Gemfile.lock
Manually updated the ffi gem. Fixes a problem with it not finding required libraries when running the Rspec suite in GitHub actions.
The [actions/setup-ruby](https://github.com/actions/setup-ruby) GitHub action has been deprecated in favour of [ruby/setup-ruby](https://github.com/ruby/setup-ruby) so I have also updated this.
Specifying the Ruby version is not necessary due to the presence of the .ruby-version file.
> Update ffi gem to fix CI issues

- app/models/audit_activity/corrective_action/add.rb
- db/migrate/20210309114228_fix_empty_decided_date_in_corrective_action_audit_added.rb
- db/schema.rb
In the previous audit log migration some of the newest audit recorded in the `body` field had `Date decided: `  instead of the previous `Date came into effect: `
This PR address those 200 records
> Fix corrective action added audit with empty decided date

- config/constants/whitelisted_emails.yml
https://trello.com/c/6qcVMZ43/966-add-email-domain-to-approved-list-15-3
Adds the peterborough.gov.uk domain to the email address whitelist.
> Add peterborough.gov.uk to email domain whitelist

- app/forms/corrective_action_form.rb
- config/locales/en.yml
- spec/features/add_corrective_action_spec.rb
- spec/features/edit_corrective_action_spec.rb
- spec/forms/corrective_action_form_spec.rb
https://trello.com/c/CSCz4DV5/943-fix-date-field-validation-in-corrective-action-form
Changes the copy to better reflect the naming of the field. Also removes the incorrect validation requiring the date to not be in the future, contradicting the hint text.
> Change copy for corrective action form validation messages

- app/models/user.rb
- app/policies/investigation_policy.rb
- spec/factories/users.rb
- spec/features/send_alert_spec.rb
- spec/forms/investigation_actions_form_spec.rb
- spec/policies/investigation_policy_spec.rb
- spec/requests/investigations/send_alert_spec.rb
https://trello.com/c/UU5PlIdv/567-restrict-send-alert-to-just-imt-team
Creates a new role called `email_alert_sender` which will be added to the OPSS Incident Management Team post-deployment. The 'send email alert' functionality will be restricted to those users with this new role only, rather than all OPSS users as currently.
> Restrict sending of email alerts to users/teams with a new specified role

- Gemfile
- Gemfile.lock
Due to some licensing issue[1], a gem version that Rails depends on was
yanked, breaking Rails installation.
This is currently blocking our deployment pipeline.
Mimemagic released a new 0.3.6 version[2] so we can manually enforce it
until a new patch on Rails fixing the dependency is released.
1: rails/rails#41750
2: minad/mimemagic#98 (comment)
> Fix yanked gem version breaking rails dependency

- app/controllers/investigations/ts_investigations_controller.rb
- app/forms/test_result_form.rb
- config/locales/en.yml
- spec/forms/test_result_form_spec.rb
https://trello.com/c/64VjkgMm/881-regression-test-result-in-ts-flow-is-not-being-recored
Raise an error when further_test_results field is not populated by a ts user.
> Fix test result bug

- app/models/user.rb
- app/policies/investigation_policy.rb
- app/views/collaborators/edit.html.erb
- app/views/help/about.html.erb
- app/views/investigations/visibility.html.erb
- spec/factories/users.rb
- spec/policies/investigation_policy_spec.rb
- spec/requests/investigations/viewing_a_restricted_case_spec.rb
https://trello.com/c/4PxoZ72O/698-enable-opss-intelligence-team-to-view-restricted-cases
Allows users with the new `restricted_case_viewer` role (introduced in this PR) to view all restricted cases, even if their team has not been added to the case.
On deployment the role will be added to the OPSS Intelligence team.
I have updated copy in the service to reflect the changes. The copy has not yet been reviewed and should not be merged until the copy changes have been reviewed.
> Allow restricted case viewing with role

- app/views/investigations/ts_investigations/_file_page.html.slim
- app/views/investigations/ts_investigations/evidence_images.html.slim
- app/views/investigations/ts_investigations/product_images.html.slim
- spec/features/report_product_spec.rb
https://trello.com/c/ZHYvSo9y/823-fix-error-order-on-other-files-and-attachments-page-in-ts-flow
Fix order of errors on other files and attachment page in ts flow
> Fix order of errors on other files and attachment page in ts flow

- config/routes.rb
Resolves a deprecation warning, e.g. `WARNING: Sidekiq::Web.session_secret= is no longer relevant and will be removed in Sidekiq 7.0. /Users/steve/.rvm/gems/ruby-2.7.3/gems/sidekiq-6.2.1/lib/sidekiq/web.rb:75:in `set'`
Prior to and after merging, test that 'delete' actions working in Sidekiq web interface as this config was added to resolve errors that occurred when trying to perform this action. Test on the review app as well as staging and production after deployment.
UPDATE: Tested working in  review apps.
> Remove deprecated Sidekiq::Web config

- .github/workflows/review-apps-delete.yml
Fixes an issue introduced by changes in #1302.
Checking out the code is not necessary for the CloudFoundry interactions, and blocks the whole action running if the PR was closed but not merged, since the checkout action is looking for the merge commit with the master branch. This doesn't exist if the PR was closed without merging. This results in the unwanted review app left running.
I've moved the checkout action to the last step which requires the file in the codebase. This will still fail if the PR was closed without merging, but it will not prevent the review app being deleted. Perhaps this cloud be mitigated in future by setting the `GITHUB_REF` to the master branch, but that would also come with downsides if the file or the action definition was modified or deleted in a PR.
Tested …
> Fix GitHub deployments not being deactivated when PR closed

- config/database.yml
- db/seeds.rb
this is a fix for the following sentry error. Preventing the seeds from being populated.
https://sentry.io/organizations/beis/issues/2299480785/?environment=psd-pr-1319&project=1329381&query=is%3Aunresolved
I have not found what is causing this, however reseting the columns information before seeding the DB seems to fix the issue.
> Fix migration being jammed on team_id.

- config/initializers/sentry.rb
The majority of exceptions we receive on production are of type `Pundit::NotAuthorizedError` which just means someone was trying to access a page they're not permitted to. These exceptions are rescued by ActionDispatch to show a friendly error message, but Sentry is still reporting them.
We don't need to be alerted to every instance of this error as it is likely to derive from normal usage. All instances are logged in any case.
Tested in the review app.
> Sentry should ignore Pundit::NotAuthorizedError exceptions

- app/decorators/audit_activity/product/destroy_decorator.rb
- app/models/audit_activity/product/destroy.rb
- app/services/remove_product_from_case.rb
- spec/features/remove_product_from_a_case_spec.rb
- spec/services/remove_product_from_case_spec.rb
the audit now stores the product's attributes in the metadata.
Also standardised the use of `have_css` over `have_content` in the feature test
> render product removal audit title in the viewing

- app/controllers/investigations/actions_controller.rb
- app/forms/investigation_actions_form.rb
- app/views/investigations/actions/index.html.erb
- spec/forms/investigation_actions_form_spec.rb
- spec/support/features/page_expectations.rb
https://trello.com/c/jRw9wt3E/1019-non-js-actions-page-no-field-level-error-when-nothing-selected
Errors not correctly displaying on actions form bug. This PR fixes the issue.
> Fix error bugs on actions form

- app/models/audit_activity/investigation/update_status.rb
- db/migrate/20210426083705_migrate_invitation_update_status_audit_to_metadata.rb
- spec/models/audit_activity/investigation/update_status_spec.rb
Removes a migration which was taking longer than the 3 minute CloudFoundry timeout limit, causing deployments to fail.
I have run the migration manually.
> Remove failing migration

- app/services/remove_product_from_case.rb
- spec/services/remove_product_from_case_spec.rb
Address bug where instead of updating the investigation index after removing the product, the product search index was removed.
> fix product not appearing in the search after removal

- app/decorators/audit_activity/risk_assessment/risk_assessment_added_decorator.rb
- app/models/audit_activity/risk_assessment/risk_assessment_added.rb
- app/views/investigations/activities/risk_assessment/_risk_assessment_added.html.erb
- doc/tasks.md
- lib/tasks/update_activity_metadata.rake
- spec/decorators/audit_activity/risk_assessment/risk_assessment_added_decorator_spec.rb
- spec/factories/risk_assessments.rb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/models/audit_activity/risk_assessment/risk_assessment_added_spec.rb
https://trello.com/c/2DTwhgRB/731-add-risk-assessment-file-attached-doesnt-get-record-in-activity-log
Fixes the attached file not being displayed on the activity log. Also tidies up the view template and moves logic which should not be in the view to a decorator, and backfills missing tests.
We now store the complete file metadata in the activity so can trace the history of a risk assessment more completely.
**Importantly, this introduces a proposed design for how to handle migrations of activity metadata without the use of ActiveRecord migrations.**
Migrations have previously caused issues during deployments due to deployment timeout thresholds being reached, and the zero-downtime deploys resulting in two versions of the code being active during the deployment - sometimes resulting in …
> Fix risk assessment file not displayed on added audit activity

- app/views/investigations/tabs/_overview.html.erb
https://trello.com/c/mhYKkN7W/1024-1-move-safety-and-compliance-section-opss-cases
Move safety and compliance section to below risks and issues section on overview page
> Move safety and compliance section on case overview

- app/models/audit_activity/investigation/update_visibility.rb
- spec/factories/activities.rb
- spec/models/audit_activity/investigation/update_visibility_spec.rb
This fix legacy investigation visibility update audit logs throwing an error on the activity page
> Fix sentry audit visibility

- app/controllers/collaborators_controller.rb
- spec/requests/edit_collaborator_spec.rb
https://trello.com/c/edFNkDun/673-double-click-on-remove-team-form-returns-404-error
Fixes an unhelpful 404 error page which is shown if the user submits the form twice (e.g. double click).
> Fix 404 error thrown when form submitted twice

- app/models/product.rb
- app/views/products/show.html.erb
- app/views/products/tabs/_attachments.html.erb
- app/views/products/tabs/_images.html.erb
- spec/features/add_attachment_to_a_product_spec.rb
https://trello.com/c/60lu8SWT/586-split-product-attachments-tab-in-to-images-and-attachments-tabs
Split product attachments tab in to images and attachments tabs
> Split attachment tab out into images and attachments

- app/decorators/audit_activity/corrective_action/update_decorator.rb
- app/forms/corrective_action_form.rb
- app/services/update_corrective_action.rb
- app/views/investigations/activities/corrective_action/_update.erb
- app/views/investigations/corrective_actions/edit.html.erb
- spec/features/edit_corrective_action_spec.rb
https://trello.com/c/qk5MQogL/688-update-edit-corrective-action-behaviour-and-activity-log-file-upload-removal
It seems the only remaining work that needed to be done on the ticket above was to dynamically render the text for the no option on the question "Are there any files related to the action?" to say "Remove attached file" if there is an existing file attached to the corrective action being edited.
> Change radio button on edit corrective action

- deploy-github-functions.sh
Dependabot PRs no longer have access to GitHub repo secrets, preventing the review application from deploying when Dependabot (or any other third party) opens a PR. A user with write access to the repo needs to update the branch to trigger a successful review app deploy.
It would not be desirable for secrets to be readable by anyone without write access, since these could be sent to a malicious party by modifying the GitHub actions in the PR.
See https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544 for a description of the potential two-step workflow solution. Note the `pull_request_target` alternative solution described there is not appropriate for this repo.
This PR does not attempt to solve the problem, but fixes some bugs in the actions script which allowed …
> Do not attempt deployments for dependabot PRs

- app/models/audit_activity/product/destroy.rb
- spec/factories/activities.rb
- spec/models/audit_activity/product/destroy_spec.rb
https://trello.com/c/RWjoWopE/1058-bug-in-product-auditactivity-when-product-is-destroyed
Addresses a bug resulting in 500 errors surfaced to users when viewing an activity timeline containing a `AuditActivity::Product::Destroy` entity.
This was caused by existing data not being migrated in #1330.
On deployment the `activities:update_metadata` task should be run to persist the new data.
> Fix missing metadata for legacy audit activities

- app/controllers/investigations/ownership_controller.rb
- app/views/investigations/ownership/confirm.html.erb
- spec/requests/investigations/changing_owner_spec.rb
https://trello.com/c/IQznMlyf/1060-fix-error-when-navigating-back-to-change-owner-form-after-form-submission
According to examples of this exception on Sentry, an error occurs when a GET request is made to the `confirm` step. This probably happens when the user clicks the back button after submitting the form, since this should have corresponding form params.
This PR introduces a check and redirect to the first step page to avoid the error.
> Fix error when user navigates back to the change ownership form after submission

- Gemfile.lock
- docker/web/Dockerfile
- manifest.review.yml
- manifest.yml
Bumps the Ruby buildpack to the latest version. This updates RubyGems and Bundler.
See https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.41
> Update CloudFoundry Ruby buildpack

- app/models/concerns/investigation_elasticsearch.rb
- spec/services/elasticsearch_query_spec.rb
Remove index on complainant due to privacy concerns
> Remove complainant index on case search

- app/controllers/products_controller.rb
- app/helpers/products_helper.rb
- app/helpers/search_helper.rb
- app/helpers/search_params.rb
- app/models/product.rb
- app/views/products/index.html.erb
- spec/features/filter_products_spec.rb
https://trello.com/c/OqcJY4GR/1068-add-hazard-type-filter-to-products-tab
Add 'Hazard type' filter to products page which allows user to only view products that belong to a case which has the hazard type in question
> Filter products

- app/forms/accident_or_incident_form.rb
- app/forms/email_correspondence_form.rb
- app/forms/phone_call_correspondence_form.rb
- app/forms/risk_assessment_form.rb
- app/forms/test_result_form.rb
- app/validators/recent_date_validator.rb
- config/locales/en.yml
- spec/forms/accident_or_incident_form_spec.rb
- spec/forms/email_correspondence_form_spec.rb
- spec/forms/phone_call_correspondence_form_spec.rb
- spec/forms/risk_assessment_form_spec.rb
- spec/forms/test_result_form_spec.rb
- spec/support/shared_examples/date_validations.rb
- spec/validators/recent_date_validator_spec.rb
https://trello.com/c/6aBbE5o9/1108-make-1970-50y-date-handling-consistent
This PR adds validations to prevent users entering very old dates in fields where the date should be recent. It also standardises any existing validations to use the same validator.
- Accident/incident date
- Correspondence date (email/phone)
- Risk assessment (assessed on) — standardised to use the `recent_date` validator
- Test result
> Prevent very old dates (before 1970) and standardise on `recent_date` validator

- app/controllers/case_exports_controller.rb
- app/jobs/case_export_job.rb
- app/models/case_export.rb
- spec/features/export_cases_spec.rb
- spec/models/case_export_spec.rb
https://trello.com/c/M37lIPUp/1112-full-case-export-timing-out
This PR moves a large database query from a synchronous controller request to the background job for case export. This was an existing TODO item which needed to be cleared up since during very large exports, users were still seeing a timeout error, caused by a SQL timeout.
Rather than passing the records around, this PR passes `case_ids` as an array to the background job, and then allows the exporter to find cases in batches. This has the same effect in the backend as pagination would on the frontend.
> Move case export query into background job and find in batches

- apt.yml
- manifest.review.yml
- manifest.yml
https://trello.com/c/G1122diI/1115-fix-webp-image-processing
Uses the CloudFoundry multi-buildpack feature and the experimental [CloudFoundry apt buildpack](https://github.com/cloudfoundry/apt-buildpack), which is similar to the Heroku apt buildpack, to automatically install the webp library on GOV.UK PaaS-hosted environments. 
This should resolve the silent failures which occur when users upload WEBP formatted images. Currently, thumbnail previews are not generated. This should ensure that thumbnails are generated correctly.
> Download webp package on PaaS environments to support WEBP image processing

- db/seeds.rb
A fix for rare `ActiveModel::UnknownAttributeError` exceptions that occasionally occur when seeding review app databases. Examples:
https://sentry.io/organizations/beis/issues/2670001888
https://sentry.io/organizations/beis/issues/2653344496
https://sentry.io/organizations/beis/issues/2636844945
I'm not entirely sure on the cause, but I suspect there is a race condition between the migration and seed tasks which results in particular model attributes not being loaded correctly. Oddly it is always the `Product#markings` attribute affected.
**Update**: I found an instance where the `Product#subcategory` attribute failed: https://sentry.io/organizations/beis/issues/2582904790
This is a modification of a [fix for a similar error](https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1319) …
> Fix intermittent ActiveModel::UnknownAttributeError error when seeding review app database

- .github/workflows/review-apps-delete-dangling.yml
The 'Delete dangling review apps' GitHub action has been failing for the last five months. We have a few review apps which are no longer needed as a result.
It reports a syntax error e.g:
`/home/runner/work/_temp/9aed070d-c2e6-4ab4-8235-fc5ab590262f.sh: line 5: [: too many arguments`
This is due to an unquoted variable in a conditional. Presumably the variable is set to a weird or empty string in some race condition where the task is not yet returned by `cf tasks`, causing it to enter an infinite loop which can never be resolved, and takes 6 hours for the task to eventually be terminated.
Once merged I will rerun the action manually to ensure it has resolved the problem.
> Fix syntax error in dangling review app delete action

- .github/workflows/review-apps-delete-dangling.yml
Further fix to #1608 to ensure previous task runs do not conflict with the current one.
> Fix dangling review app deletion

- app/controllers/business_exports_controller.rb
- app/helpers/businesses_helper.rb
- app/models/concerns/searchable.rb
- spec/services/elasticsearch_query_spec.rb
https://trello.com/c/1HAsNX6G/1179-optimise-elasticsearch-query-for-business-export
This PR utilises elasticsearch's `search_after` functionality to retrieve all our businesses in 10k batches, which hopefully should reduce memory related issues now and in the future which could come from us retrieving >10k records in one query.
Note: I ordered by ID rather than created_at, as I found it much clearer to use ID as the search after point and the order will be the same regardless I believe. I don't think the ordering should matter much anyway as we are producing an excel file which the user can order as they see fit.
> Query ES for businesses in batches

- app/controllers/users/passwords_controller.rb
- app/forms/invite_user_to_team_form.rb
- app/models/user.rb
- app/services/delete_user.rb
- app/services/invite_user_to_team.rb
- spec/features/invite_user_spec.rb
- spec/features/registration_spec.rb
- spec/forms/invite_user_to_team_form_spec.rb
- spec/models/user_spec.rb
- spec/services/invite_user_to_team_spec.rb
https://trello.com/c/NdkIW2f3/1198-allow-re-adding-of-deleted-users
This change allows deleted users to be re-added by a team admin. 
Note: In order to ensure that the full user sign up flow is completed again upon re-adding I reset a lot of the user fields to the state they would be in for a fresh user upon re-adding.
> Re-invite deleted user

- app/services/attachment_categorizer.rb
- spec/requests/assets_security_spec.rb
[This bug](https://sentry.io/organizations/beis/issues/2817245290/?project=1329381&referrer=slack) occured today and seems to be due to the `attachment_categorizer` service not properly handling activity attachments.
I added a test which reproduced this error and a guard clause which stops it from occuring.
> Fix bug around activity attachments

- app/controllers/active_storage/blobs/proxy_controller.rb
- app/services/attachment_categorizer.rb
- spec/requests/assets_security_spec.rb
https://trello.com/c/A8X5Zs05/1225-correctly-authorize-attachments-on-activity
Prior to this PR, attachments on activities did not share the same level of authorization as the same attachments on other models. This PR corrects this issue.
> Attachments authorised by team

- .github/workflows/deploy.yml
This change disables smoke tests on production. Previously we disabled the smoke test on staging but not on prod. This issue seems to be due to some kind of change on the log in/2fa page and is causing the smoke test to not be useful at the current time until this is addressed
> Disable smoke test on prod

- .github/workflows/deploy.yml
- smoke_test/cases_page_spec.rb
https://trello.com/c/7J2xuOkC/1249-spike-investigate-smoke-test-failures
Smoke tests were failing due to not being able to find "Enter security code". This seemed to be because in our code we were breaking a loop based on the contents of a page which may not have loaded yet, so I have changed it to break the loop based on the path and changed the location of the break clause which fixes the issue.
> Fix smoke test bug

- app/forms/secondary_authentication_form.rb
- app/jobs/log_db_metrics_job.rb
- app/jobs/send_user_invitation_job.rb
https://trello.com/c/49rWAeuX/1161-kibana-dashboard-for-psd
This PR adds the additional logging and metrics as described in the ticket.
It adds:
- `total_number_of_locked_users` to the log metrics db job
- `total_number_of_failed_sign_ins` to the log metrics db job
- Logging for a user requested password reset email and for a failed 2FA attempt, as well as recording the ID of the user in question.
> Further logging metrics

- app/controllers/products_controller.rb
- app/helpers/products_helper.rb
- app/views/products/_controls.html.erb
- app/views/products/index.html.erb
- spec/features/sort_products_spec.rb
https://trello.com/c/ze5RRvfT/1265-additional-sorting-on-products-page
- Make the Products sort-by-name options consistent with the Businesses page
- Rename the "Name" sort option to "Name A–Z"
- Introduce a "Name Z-A" sort option
> Change the name sorting options on Products to match Businesses

- Gemfile.lock
- docker/web/Dockerfile
- manifest.review.yml
- manifest.yml
- Add rubygems 3.3.4, remove rubygems 3.2.33
- Add bundler 2.3.4, remove bundler 2.2.33
See [release notes](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.50)
> Bump CloudFoundry Ruby buildpack

- app/controllers/investigations/corrective_actions_controller.rb
- spec/features/add_corrective_action_spec.rb
- spec/requests/investigations/add_corrective_action_spec.rb
https://trello.com/c/fjiRMthJ/1271-nonteam-member-collaborator-on-a-case-can-add-corrective-action-via-url
Updates the policy for adding Corrective Actions to a Case, to require the user to have explicit edit access (be from a collaborating team with edit access).
> Update policy for adding Corrective Actions to a Case

- app/views/investigations/_heading.html.erb
- app/views/investigations/tabs/images/_product_images.html.erb
- app/views/teams/show.html.erb
https://trello.com/c/E4J3vvuV/1251-implement-solution-for-right-aligned-links-active-state
This bug has been raised a number of times internally, and now is being noticed by users.
I wasn't able to identify any such link on the businesses or products page, but I found it on the Your Team page and the case product images tab, which I've fixed as well.
> Fix right aligned anchors displaying as block elements

- app/helpers/investigations/display_text_helper.rb
- spec/features/filter_investigations_spec.rb
https://trello.com/c/V9VoZQbC/1167-case-search-result-page-returning-team-ids-instead-of-names
Displays the matching team name in case search result highlights rather than their ID.
Note Opensearch is currently configured to wrap highlights in its result set in `<em>` tags. This can be changed, but would involve a much larger refactoring, so I elected to strip them out in order to resolve the team name. An exception will be thrown if the team cannot be resolved from the ID. This should be safe since we do not delete teams for various reasons which would break things elsewhere.
I nalso changed the label 'teams with access' to 'team added to the case' to be consistent with the label in the filter list.
> Display matching team name on case result highlights

- app/models/product.rb
- spec/features/filter_products_spec.rb
https://trello.com/c/4YDZrTGw/1275-update-search-functionality-to-be-able-to-search-by-unique-product-id
Adds OpenSearch indexes to allow searching products by their ID or PSD Reference.
**IMPORTANT:** Indexes must be manually deployed:
```rb
Product.__elasticsearch__.import force: true, refresh: :wait
```
> Add indexes to search by Product ID or PSD ref

- app/controllers/businesses_controller.rb
- app/controllers/products_controller.rb
- app/views/businesses/index.html.erb
- app/views/products/index.html.erb
- spec/features/businesses_spec.rb
- spec/features/filter_products_spec.rb
https://trello.com/c/xLxeynfs/1288-wrong-count-on-products-and-businesses-pages
Prior to this change the search statement on the product and business page had a bug that caused it to show a maximum of 20 in the statement which describes total number of businesses/products. This PR fixes that issue.
> Fix incorrect count on products and businesses pages

- app/views/layouts/application.html.erb
https://trello.com/c/A4dcvuFU/1303-ensure-google-analytics-for-psd-is-picking-up-users
Fixes the invalid markup preventing Google Analytics from initialising.
> Remove invalid closing tag from GA script

- .github/workflows/publish-production-redacted-export.yml
- .github/workflows/publish-staging-redacted-export.yml
This change no longer `tee`s the export task's logs to the workflow output. These logs appeared as a single-line wall of text which were hard for a human to read and didn't add anything useful.
> Remove excess logs from redex workflows

- .github/workflows/publish-production-redacted-export.yml
- .github/workflows/publish-staging-redacted-export.yml
Expands on #1774 to remove cluttered log lines from the export workflows which were being written to `STDERR`.
> Remove more excess logs from redex workflows

- config/constants/whitelisted_emails.yml
https://trello.com/c/aDdqPYlh/1312-add-domain-to-whitelist
> Add daera-ni.gov.uk domain to whitelist

- app/models/user.rb
- app/policies/business_policy.rb
- app/policies/investigation_policy.rb
- app/policies/product_policy.rb
- db/seeds.rb
- doc/roles.md
- spec/factories/users.rb
- spec/features/export_businesses_spec.rb
- spec/features/export_cases_spec.rb
- spec/features/export_products_spec.rb
- spec/policies/business_policy_spec.rb
- spec/policies/product_policy_spec.rb
- spec/requests/export_cases_spec.rb
- spec/requests/export_products_spec.rb
https://trello.com/c/NW3AzThS/1334-rename-psdadmin-role
Renames the `psd_admin` role in line with the established naming convention to provide more clarity as to what it does, and more distinction between it and the other `team_admin` role.
> Rename psd_admin role for clarity and to avoid confusion with team_admin

- app/assets/stylesheets/opss/_opss-shared.scss
- app/controllers/businesses_controller.rb
- app/controllers/investigations_controller.rb
- app/controllers/products_controller.rb
- app/helpers/investigations_helper.rb
- app/helpers/search_helper.rb
- app/helpers/search_params.rb
- app/helpers/sort_by_helper.rb
- app/views/application/_sort_dropdown.html.erb
- app/views/investigations/_case_card.html.erb
- app/views/investigations/_full_table_body.html.erb
- app/views/investigations/_highlight_table_body.html.erb
- app/views/investigations/index.html.erb
- app/views/searches/show.html.erb
- spec/features/cases_navigation_spec.rb
- spec/features/investigations_spec.rb
- spec/models/search_params_spec.rb
https://trello.com/c/hxKa7Fov/1309-separate-out-sorting-option
- Add new sorting option "Oldest cases" as an option on investigation pages.
- Show sorting drop down on "Your cases" and "Team cases" when there is more than 11 cases.
- Refactor sorting logic
> Cases sorting options

- app/controllers/searches_controller.rb
- app/views/searches/show.html.erb
- spec/features/filter_investigations_spec.rb
https://trello.com/c/bGIuVXGf/1360-issue-on-prod-sort-by-defaults-to-oldest-cases-updates-on-the-cases-search-result-page
Bugfix on the cases page. Fixes an issue which caused sorting options to not persist after a user had searched for a case.
> Cases sorting bug

- app/models/case_export.rb
- spec/models/case_export_spec.rb
- spec/requests/export_cases_spec.rb
https://trello.com/c/JRrGkReH/1362-spike-investigate-how-to-implement-alldataexporter-role-restrictions-based-on-team
Redact information from the case export if the case is restricted and the current user is not on the team that owns the case.
> Redact data on restricted cases export unless user has access to it

- app/helpers/search_params.rb
- app/views/investigations/_filters.html.erb
- spec/features/filter_investigations_spec.rb
https://trello.com/c/6wCLk0Kn/1366-change-to-case-status-filter-on-all-cases-search-page
Swap places of case owner and case status filters on the all cases page
> Swap places of case owner and case status filters on the all cases page

- config/initializers/redacted_export.rb
- lib/redacted_export.rb
- lib/tasks/redacted_export.rake
- spec/lib/redacted_export_spec.rb
https://trello.com/c/hoUloDCd/1374-change-export-code-to-provide-additional-tables-in-the-cbas-export
This PR expands the redacted database export functionality to allow custom (non-model) tables to be exported. This is useful for many-to-many join tables.
```rb
redacted_export_with :id, :created_at, :updated_at
RedactedExport.register_model_attributes(
ActiveStorage::Attachment,
:id, :blob_id, :created_at, :name, :record_id, :record_type
)
RedactedExport.register_table_attributes(
"investigation_businesses",
:business_id, :created_at, :investigation_id, :relationship, :updated_at
)
Rails.application.eager_load!
puts RedactedExport.registry.to_sql
```
> Allow redaction and exporting of custom tables

- app/controllers/users_controller.rb
- app/views/users/remove.html.erb
- spec/features/remove_a_user_spec.rb
https://trello.com/c/x0BPJvqm/1240-prevent-double-click-on-remove-user-journey-and-backlink-to-return-back-to-the-team-page
When an admin removes a user from their team, if they clicked "save and continue" twice, or if they used the browser's back button after removing a user and tried to remove them a second time, a server error was produced. This PR prevents double-click on the button, and displayes an alert to the admin if they try to remove a user whom has already been removed.
> Prevent double-click/back when removing a user

- app/controllers/investigations_controller.rb
- spec/features/filter_investigations_spec.rb
- spec/features/search_cases_spec.rb
https://trello.com/c/2ZCw3ARc/1386-regression-on-prod-total-cases-count-remains-the-same-for-open-and-all-cases
Prior to this change, when showing open cases on the first visit to all_cases page in the search summary text we quoted the number of all cases rather than just open cases, this PR fixes this issue
> Fix case search statement bug

- app/jobs/delete_unsafe_files_job.rb
- app/mailers/notify_mailer.rb
- config/initializers/sidekiq.rb
- db/migrate/20220516133518_add_index_to_active_storage_blobs.rb
- db/schema.rb
- spec/jobs/delete_unsafe_files_job_spec.rb
https://trello.com/c/5wZznipW/1393-delete-unsafe-attachments-after-validation-has-completed
Prior to this change, unsafe files in our system were not deleted. We have validation on file upload, however due to this running in a background job if the antivirus check is not run in time sometimes the antivirus validation will be skipped.
This change introduces a cron job that deletes any offending files every 15 minutes and informs the user via email.
> Delete unsafe files job

- config/initializers/strong_migrations.rb
https://sentry.io/organizations/beis/issues/3277653425/?project=1329381&referrer=slack
A previous migration is not running, causing deploys to fail because (I think) creating an index concurrently on a large table is taking too long and timing out.
This change adds [the recommended time out settings for strong migrations](https://github.com/ankane/strong_migrations#migration-timeouts) so that we have a longer migration time out which may help us resolve the issue described above.
Note: Before deploying we may need to remove the index_active_storage_blobs_on_metadata index
> Change migration time out

- app/helpers/application_helper.rb
- app/views/businesses/_table_row.html.erb
- app/views/investigations/_full_table_body.html.erb
- spec/helpers/application_helper_spec.rb
https://trello.com/c/DRZxbvAt/1380-provide-standard-format-dates-on-cases-and-businesses-pages
Changes the dates on the cases and businesses lists from "About 1 month" terminology, to standard format dates e.g. "6 April 2022", except when the time frame is within the last 24hr.
- Your cases - updated column
- Team cases - updated column
- All cases - updated column
- All businesses - added column
- Team businesses - added column
- All businesses - added column
> Provide a standard format for dates on the Cases and Businesses lists

- app/views/investigations/index.html.erb
https://trello.com/c/W7tJiicf/1399-on-the-cases-pages-wrong-column-label-used-in-the-table-footer
Fixes a bug in the table footer for the Cases pages. On the Cases pages: 'Your cases' and 'Team cases' in the footer of the table, the second label currently reads "Case owner" when it should read "Case created".
> Correct heading in the cases pages table footer

- app/controllers/active_storage/blobs/proxy_controller.rb
- app/controllers/active_storage/representations/proxy_controller.rb
- app/controllers/concerns/set_sentry_blob_context.rb
https://trello.com/c/qfVpPoij/1367-capture-exceptions-on-image-thumbnail-generation
This PR adds some helpful information to the Sentry context which can be used to debug errors with user-uploaded files (for example, trying to thumbnail a zero-byte file or an unsupported image format).
> Add extra debug info into the Sentry context for file proxy exceptions

- app/views/products/heading/_all_products.html.erb
https://trello.com/c/X0X16yYV/1381-cases-and-products-page-snags
Before:
After:
> Change typo in help text link

- .erdconfig
- Gemfile.lock
https://trello.com/c/Hii77EO4/1419-improvements-to-the-erd
In response to feedback from users of the Entity Relationship Diagram, this PR removes indirect (dotted line) associations. These were not strictly necessary and were cluttering the diagram making it harder to follow.
> Remove indirect associations from ERD

- config/initializers/sidekiq.rb
The DeleteUnsafeFiles job is not working and causing a lot of unnecessary errors to be raised, this PR stops the job from running for now until we can debug and fix it.
> Deactivate unsafe files job until we can debug issue

- config/constants/legislation_constants.yml
https://trello.com/c/gTFsYkjt/1431-add-a-value-to-the-under-which-legislation-dropdown
This PR adds "Classification, Labelling and Packaging of Chemicals Regulations 2015" to the Corrective Action legislation options, allowing users to reference the [The Classification, Labelling and Packaging of Chemicals (Amendments to Secondary Legislation) Regulations 2015](https://www.legislation.gov.uk/uksi/2015/21/made).
> Add additional legislation for corrective actions

- app/helpers/investigations/display_text_helper.rb
- app/models/investigation.rb
- app/views/investigations/_actions.html.erb
- app/views/investigations/_navigable_case_nav.html.erb
- app/views/investigations/tabs/_overview.html.erb
- spec/features/case_actions_spec.rb
https://trello.com/c/P2gn8vwe/1417-grey-action-bar-for-the-cases-landing-page
Part of a design update to cases, this PR adds an actions section to the top of the case overview page with counts of the various case information and quick navigation links to add more. It also introduces a visual warning which is shown when a case does not yet relate to a product.
> Introduce an actions section on the case overview page

- app/views/documents/new.html.erb
- spec/support/features/page_expectations.rb
https://trello.com/c/gKRLeYN4/1462-contextual-hint-text-required-on-a-form
This change fixes issues on the new attachments page. Prior to this change it always had the text relating to case images, this text now refers to product images if the parent is a product, case images if it is a case and nothing if it is neither
> Render correct hint text based on the parent of the potential attachment

- app/views/application/_product_summary.html.erb
https://trello.com/c/i6KVXQOY/1454-cases-page-products-page-design-tweak
This PR affects the Products tab on a Case page. It moves the images section to the bottom of the main content column - this will leave only one wide right hand column, which gives more space to the content.
> Move product images to the bottom of the page

- app/helpers/investigations/display_text_helper.rb
- app/models/investigation_business.rb
- app/views/investigations/tabs/_businesses.html.erb
- config/locales/en.yml
- spec/features/add_business_spec.rb
- spec/features/investigation_business_page_spec.rb
- spec/features/navigation_spec.rb
- spec/features/remove_business_from_a_case_spec.rb
- spec/features/report_product_spec.rb
https://trello.com/b/X2VaoUr2/psd-sprint-board
This PR is a re-design of the investigation businesses tab
> New business page design

- app/controllers/investigations/risk_assessments_controller.rb
Fixes a typo in a redirect when updating a risk assessment.
```
NameError Investigations::RiskAssessmentsController#update
undefined local variable or method `investigation'
```
> Fix NameError when updating a Risk Assessment

- .github/workflows/deploy.yml
- .github/workflows/review-apps-delete.yml
- .github/workflows/review-apps.yml
Since transferring the repository to the new organisation, the old token is no longer valid. This change uses the new automatic token authentication as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication.
> Use automatic GitHub token authentication

- app/views/investigations/summary/edit.html.erb
- config/locales/en.yml
- spec/forms/change_case_summary_form_spec.rb
https://trello.com/c/f5lVcGj8/1507-remove-character-count-for-the-summary-field
#1952 and #1971 made some changes to case summaries, reducing their length. We have decided to revert these changes pending further research into how summaries are being used by our users. This PR restores the summary character limit to 10,000 characters, but removes the new character count design as this was determined to be a distraction.
> Remove the character count and lower limit on case summaries

- app/decorators/products_decorator.rb
- app/forms/product_form.rb
- app/models/product.rb
- app/models/product_export.rb
- app/models/team.rb
- db/migrate/20220822125733_add_owning_team_to_products.rb
- db/migrate/20220823094633_validate_foreign_key_products_to_owning_team.rb
- db/schema.rb
- spec/models/product_spec.rb
https://trello.com/c/9FcZdj4F/1526-creating-a-product-record-in-the-database-rules
- Adds a database column, attribute, relationships and foreign key to represent the Team which owns a Product
- Products have no owning team by default
```rb
Product.owning_team
Team.owned_products
```
> Add the concept of products being owned by a team

- app/controllers/investigations/case_names_controller.rb
- app/controllers/investigations/reference_numbers_controller.rb
- app/helpers/investigations_helper.rb
- app/views/investigations/case_names/_form.html.erb
- app/views/investigations/case_names/edit.html.erb
- app/views/investigations/reference_numbers/edit.html.erb
- app/views/investigations/ts_investigations/case_name.html.erb
- app/views/investigations/ts_investigations/reference_number.html.erb
- config/routes.rb
- spec/features/edit_investigation_case_name_spec.rb
- spec/features/edit_investigation_reference_number_spec.rb
https://trello.com/c/epZ5N9G9/1496-edit-links-for-case-specific-information-entered-on-the-new-create-a-case-journey
This change allows users to edit the case name and reference number for a previously created case.
> Edit reference number and case name

- app/assets/stylesheets/opss/_opss-psd.scss
- app/assets/stylesheets/opss/_opss-search.scss
- app/assets/stylesheets/opss/_opss-shared.scss
- app/forms/product_form.rb
- app/helpers/opss_aside_helper.rb
- app/helpers/products_helper.rb
- app/services/add_product_to_case.rb
- app/views/investigations/products/new.html.erb
- app/views/products/_form.html.erb
- config/locales/en.yml
- spec/factories/products.rb
- spec/features/add_product_spec.rb
- spec/features/create_allegation_as_opss_user_spec.rb
- spec/features/edit_a_product_spec.rb
- spec/features/update_product_details_spec.rb
- spec/forms/product_form_spec.rb
- spec/support/features/page_expectations.rb
https://trello.com/c/SKluPBiG/1512-create-a-product-updates-to-the-create-a-product-page-cap101
Updates the "Create a product" page (Case > Add product) with newer visual style, and adds hints for fields which have been moved to the Case level.
> Updates to the "Create a product" page

- app/services/delete_team.rb
- spec/services/delete_team_spec.rb
https://trello.com/c/Cql6ces5/1547-deleting-a-team-and-the-product-record-ownership-rules
When a team is deleted, the new team which takes on their users and cases, now also takes on their products.
> Move owned products to the new team when deleting a team

- Gemfile
- Gemfile.lock
- app/controllers/investigations_controller.rb
- app/helpers/investigation_search_helper.rb
- app/helpers/investigations_helper.rb
- app/models/concerns/investigation_opensearch.rb
- app/views/investigations/_case_hazard_type_filter.html.erb
- app/views/investigations/_filters.html.erb
- app/views/investigations/_full_table_body.html.erb
- app/views/investigations/_highlight_table_body.html.erb
- app/views/investigations/_restricted_table_body.html.erb
- app/views/investigations/_status_table_row.html.erb
- app/views/investigations/index.html.erb
- spec/features/cases_navigation_spec.rb
- spec/features/filter_investigations_spec.rb
https://trello.com/c/TKyYnDaN/1560-tech-debt-changes-for-the-your-team-all-cases-page-cap023
This ticket implements the following changes to the  all cases, your cases and team cases pages:
- Adds an additional column displaying the hazard type of the case
- Adds warning text on your cases and team cases page if a case does not have an associated product
- Adds the ability for a user to filter cases by hazard type
> Case search pages changes

- .erdconfig
Adds ORM cardinality markers to associations, uses ortho line routing for fewer overlapping lines, and moves primary keys to the top of the table.
Before:
After:
> Add options to the ERD for readability

- app/models/investigation_business.rb
- app/models/investigation_product.rb
- config/initializers/redacted_export.rb
As models now exist for `InvestigationProduct` and `InvestigationBusiness`, we no longer need static declarations in the initializer.
> Move the join model redacted export declarations into their model files

- spec/features/businesses_navigation_spec.rb
- spec/features/cases_navigation_spec.rb
- spec/features/filter_investigations_spec.rb
- spec/features/products_navigation_spec.rb
This is a developer quality of life improvement to some of the feature specs which require Opensearch.
This tackles all of the top 10 slowest running specs (all times taken from my 16in Macbook Pro Intel i9 2.4GHz w/ 64GB machine):
```
Top 10 slowest examples (406.72 seconds, 18.3% of total time):
Searching businesses when there are businesses when the user is on the all businesses page when more than 11 businesses does show the sort filter drop down with 'recent businesses' sorting option selected
58.95 seconds ./spec/features/businesses_navigation_spec.rb:175
Searching businesses when there are businesses when the user is on the team businesses page when more than 11 businesses does show the sort filter drop down with 'newly added' sorting option selected
58.94 seconds …
```
> Improve efficiency of Opensearch-dependent specs

- manifest.review.yml
- manifest.yml
The [CloudFoundry app manifest specification](https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#the-app-manifest-specification) shows that there is no `env` section for `processes`, and therefore `RAILS_MAX_THREADS` and `STATEMENT_TIMEOUT` were never being set in the applications.
This resulted in occasional database statement timeout errors in the workers.
Note that our deployment configuration [specifies the max threads for the application](https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/blob/master/.github/workflows/deploy.yml#L147-L148) but this configuration was never used. It is currently set to `16` threads in production. Deploying this change will therefore change the performance characteristics of the application by *reducing the number …
> Fix environment variables specified in wrong place in app manifests

- Gemfile
- Gemfile.lock
Upgrades `govuk-design-system-rails` to `0.9.5` to fix the input styling bug described at: https://github.com/OfficeForProductSafetyAndStandards/govuk-design-system-rails/pull/58
> Upgrade govuk-design-system-rails to 0.9.5

- app/controllers/investigation_products/number_of_affected_units_controller.rb
- app/decorators/audit_activity/investigation/update_case_specific_product_information_decorator.rb
- app/forms/number_of_affected_units_form.rb
- app/helpers/investigations_helper.rb
- app/models/audit_activity/investigation/update_case_specific_product_information.rb
- app/services/change_number_of_affected_units.rb
- app/views/investigation_products/number_of_affected_units/edit.html.erb
- app/views/investigations/activities/investigation/_update_case_specific_product_information.html.erb
- config/routes.rb
- spec/features/case_specific_information_spec.rb
- spec/support/features/page_expectations.rb
https://trello.com/c/UfZVqwiE/1519-edit-units-affected-form-page-cap109
As the final part of the piece allowing users to edit case specific information, this change allows users to change the numbers of, and status of, affected units.
> Allow editing of units affected data

- smoke_test/cases_page_spec.rb
The smoke test after deployment has become unreliable as the "Cases" homepage sometimes takes too long to respond after a fresh deployment. This PR adds some debug logging around 2FA to the smoke test to allow us to diagnose any issues around the number of 2FA attempts, and increases the maximum wait time for the cases page to 60 seconds.
> Improve smoke test reliability

- smoke_test/cases_page_spec.rb
Reverts OfficeForProductSafetyAndStandards/product-safety-database#2089.
The smoke test users in various environments are different types, so it's not possible to determine which path the smoke test will land on.
This PR follows the old logic of clicking Cases > All cases, which is common to both landing pages, and not checking the path explicitly.
> Revert "Improve smoke test reliability" and try again

- .github/workflows/review-apps.yml
The access token used by Dependabot does not have write access to the repository, and therefore no access to the secrets required to deploy the review apps.
This change will prevent the review app step being run in this event. As before, if a user with write access updates the branch the review app will still deploy as normal. This means we can choose to merge dependency updates without requiring a review app deployment beforehand.
> Skip review app deployment for Dependabot PRs

- app/controllers/investigations/ts_investigations_controller.rb
- app/forms/reason_for_creating_form.rb
- app/helpers/investigations_helper.rb
- app/services/add_product_to_case.rb
- app/services/create_case.rb
- app/views/investigations/ts_investigations/case_created.html.erb
- app/views/products/show.html.erb
- spec/decorators/investigation_decorator_spec.rb
- spec/factories/investigations.rb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/features/add_product_to_case_spec.rb
- spec/features/add_test_results_spec.rb
- spec/features/case_actions_spec.rb
- spec/features/case_specific_information_spec.rb
- spec/features/cases_navigation_spec.rb
- spec/features/create_case_as_ts_user_spec.rb
- spec/features/remove_product_from_a_case_spec.rb
- spec/models/case_export_spec.rb
- spec/services/add_product_to_case_spec.rb
- spec/services/create_case_spec.rb
- spec/services/remove_product_from_case_spec.rb
- spec/support/shared_contexts/add_corrective_action_context.rb
https://trello.com/c/9hL8XPMo/1559-create-a-case-directly-from-the-product-record-cap022
This ticket forces TS users to open cases from a product. This means that a case opened by a TS user must always have a product associated with it which has caused quite a few tests to need to be changed. For this reason I have made some changes to the investigation factory, defaulting the case creator to be an OPSS user so as to not force us to create products for every investigation by default.
> Create case from product record

- .github/workflows/publish-production-redacted-export.yml
- .github/workflows/publish-staging-redacted-export.yml
- .github/workflows/review-apps.yml
- .profile
- bin/tll
- doc/deployment.md
- doc/tasks.md
- doc/using-cloud-foundry.md
- manifest.review.yml
- manifest.yml
The project had a common initialisation task of destructuting some JSON stored in the `VCAP_SERVICES` environment variable and exporting several other environment variables reflecting Rails' config. This is a common pattern in applications deployed to Cloud Foundary.
This PR uses the [newer method of app initialization, using a `.profile` file](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#profile).
It also provides a shorthand for running processes within a launched environment:
```sh
cd app
/tmp/lifecycle/launcher /home/vcap/app 'bin/rails c' ''
bin/tll bin/rails c
```
This work was spurred on by https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/2650/commits/0ce88a866dd7269dba0fcb9573de0e56db0418fa.
> Use a .profile file to set up the app environment

- Gemfile
- Gemfile.lock
- app/controllers/create_a_case_page_controller.rb
- app/views/create_a_case_page/index.html.erb
- app/views/homepage/non_opss.html.erb
- app/views/investigations/_create_a_case_link.html.erb
- config/routes.rb
- spec/features/create_case_as_ts_user_spec.rb
https://trello.com/c/GprlgvMo/1595-create-a-case-link-and-redirect-page
This PR changes the create a case links for ts users to direct them to a new intermediary page that informs them that they need to create a case from a product record, and links them to the products page.
> Case to product page

- app/views/investigations/_sub_nav.html.erb
https://trello.com/c/IR7vDyBV/1635-html-id-bug
Removes DOM IDs from the links on the case navigation menu. Some of the generated IDs were not valid HTML as they had spaces in them, and these IDs were never actually used.
> Fix invalid DOM IDs on sub-nav links

- app/assets/stylesheets/opss/_opss-psd.scss
- app/views/investigations/_actions.html.erb
https://trello.com/c/d4YYDcJ0/1648-update-to-no-product-warning
Change text and styles for the no product warning shown on investigations that do not have associated products
> Update no product warning

- app/helpers/investigations_helper.rb
- app/views/investigations/tabs/_products.html.erb
- app/views/products/case_product_info_tabs/_details.html.erb
https://trello.com/c/6DeCXQmW/1647-case-page-snags
Various small design changes on the cases page, see trello ticket for details
> Cases page snags

- app/models/case_export.rb
- spec/models/case_export_spec.rb
- spec/requests/export_cases_spec.rb
https://trello.com/c/B21OZf08/1658-include-trading-standards-reference-in-the-cases-export
Adds the following existing field (Complainant Reference) to the Case Export.
- Adds a new column to case export Excel sheets "Complainant_Reference"
- This will display as "Restricted" for restricted cases
- Will be null/blank if not set
- Changes the casing of "Reported_as" to be "Reported_As" in order to be consistent with the casing of other fields
> Add Complainant_Reference to case export

- config/constants/hazard_constants.yml
- config/constants/product_constants.yml
https://regulatorydelivery.atlassian.net/jira/software/projects/PST1/boards/53?selectedIssue=PST1-1331
This change removes the "Other" option from the hazard type and product category drop-downs
> Remove other options

- .irbrc
The IRB autocomplete feature from Ruby 3.1 is extremely slow and causes issues when pasting code or when working over a remote connection.
This PR turns it off by default.
> Turn off IRB (rails console) autocomplete

- .github/workflows/deploy-research.yml
- .github/workflows/refresh-research.yml
Changes the workflows relating to the user research environment:
- No longer runs the smoke tests (because the environment will often have no cases/data to test with, and the researcher will be manually verifying the environment as part of the research process)
- No longer triggers an automatic data refresh (because this is not always desirable, for example, when fast-forwarding a deployed branch)
> Change research workflows

- app/controllers/products_controller.rb
- app/helpers/product_search_helper.rb
- app/helpers/search_helper.rb
- app/helpers/search_params.rb
- app/models/product.rb
- app/policies/product_policy.rb
- app/views/products/_filters.html.erb
- app/views/products/_search_statement.html.erb
- app/views/products/_table_row.html.erb
- app/views/products/heading/_all_products.html.erb
- app/views/products/index.html.erb
- spec/features/filter_products_spec.rb
- spec/features/products_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1168
This change allows opss users to filter by retired or active products. It does not allow non opss users to use this filter and instead only shows them active products.
> New search filter

- app/controllers/products_controller.rb
- app/views/products/retired.html.erb
- spec/features/retired_products_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1169
This change adds a retired product page to be shown when a none opss user tries to view a retired product.
> Retired product page

- app/controllers/products_controller.rb
- app/decorators/product_decorator.rb
- app/helpers/product_search_helper.rb
- app/helpers/products_helper.rb
- app/helpers/search_helper.rb
- app/helpers/search_params.rb
- app/models/product.rb
- app/models/product_export.rb
- app/services/add_product_to_case.rb
- app/services/change_case_status.rb
- app/views/products/_filters.html.erb
- app/views/products/_search_statement.html.erb
- app/views/products/_table.html.erb
- app/views/products/_table_row.html.erb
- app/views/products/heading/_all_products.html.erb
- app/views/products/heading/_team_products.html.erb
- app/views/products/heading/_your_products.html.erb
- app/views/products/index.html.erb
- spec/features/export_products_spec.rb
- spec/features/filter_products_spec.rb
- spec/features/products_navigation_spec.rb
- spec/features/products_spec.rb
- spec/features/sort_products_spec.rb
- spec/models/product_export_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1170
This change removes the hazard_type filter on the products page and replaces it with a category filter. It also includes some copy/design changes to the products pages and a couple of fixes relating to indexing updated products to fix existing bugs on the my products/team products pages.
> Product pages changes

- app/views/products/case_product_info_tabs/_images.html.erb
Fix the link to the product page on images tab in cases
https://regulatorydelivery.atlassian.net/browse/PSD-1073
- Fixed link to product
- Fixed indentation in file
> Fix product link on images tab

- config/constants/whitelisted_emails.yml
- Adds Isle of Anglesey County Council to the email whitelist
> Add ynysmon.llyw.cymru to the email whitelist

- app/views/teams/show.html.erb
- spec/features/team_spec.rb
After the rails 7 upgrade links which have been overridden to use non-GET requests no longer work (see [here](https://guides.rubyonrails.org/working_with_javascript_in_rails.html#replacements-for-rails-ujs-functionality)).
This PR changes the resend invitation link to a button which allows the functionality to work as expected. There is a minor visual change caused by this fix, which may need to be addressed in a future PR.
> Fix the resend invitation link

- app/helpers/investigations/display_text_helper.rb
- spec/features/case_source_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1313
Add links to the sub nav for the safety and compliance, case specific product information and case source sections
> Add links to investigation sub nav

- app/controllers/investigations/visibility_controller.rb
- app/controllers/investigations_controller.rb
- app/helpers/investigations_helper.rb
- app/policies/investigation_policy.rb
- app/views/investigations/_status_table_row.html.erb
- spec/features/change_case_visibility_restriction_spec.rb
- spec/policies/investigation_policy_spec.rb
Removes the ability for cases to be restricted on PSD. Existing cases that are open cannot be made restricted, but previously restricted cases can still be made public.
https://regulatorydelivery.atlassian.net/browse/PSD-1062
> Remove case restrictions

- app/assets/stylesheets/opss/_opss-shared.scss
Replicates https://github.com/OfficeForProductSafetyAndStandards/product-safety-database-prototypes/pull/167 which fixes some styling issues seen in Firefox.
> Design tweaks for the Firefox browser

- app/views/products/_cases.html.erb
- spec/features/products_spec.rb
Fix to CSS where it was found multiple product links couldn't be selected -
Added new `.capy-cases` to select for feature spec use, and not styled
https://regulatorydelivery.atlassian.net/browse/PSD-1351
> Fix product cases hover, could only select link for first product

- app/forms/risk_assessment_form.rb
- app/views/investigations/accident_or_incidents/_form.html.erb
- app/views/investigations/corrective_actions/_form.html.erb
- app/views/investigations/test_results/_form.html.erb
https://regulatorydelivery.atlassian.net/browse/PSD-1359
The `risk_assessed_products` table has a `unique` index on `product_id` and `investigation_id`. The introduction of versioned products on a case produces a problem: A user can add the same `Product` to a case multiple times (by adding it, closing the case, reopening the case, and adding again). This is intended behaviour, however the Risk Assessment creation/edit flow has not been updated to take this into account. Accordingly, in this scenario the same `product_id`/checkbox was presented on the form twice. Selecting _both_ checkboxes for the same logical product caused a 500 error.
Work to address the relationship of supporting information to products is ongoing, however in the meantime, this PR mitigates the issue by deduplicating …
> Fix a bug where products are selectable multiple times when adding risk assessments

- app/controllers/investigations/investigation_products_controller.rb
- app/models/investigation_product.rb
- app/services/remove_product_from_case.rb
- spec/features/remove_product_from_a_case_spec.rb
The services here were still pointing to `investigation.product` instead of `investigation_product`
This was leading to product being not able to be removed from cases if other adjacent investigation products had already been added with the same product parent.
https://regulatorydelivery.atlassian.net/browse/PSD-1401
> Removing a product from a case should use investigation_product

- app/services/update_risk_assessment.rb
- spec/features/edit_a_risk_assessment_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1383
Prior to this change, risk assessments could not be edited solely to change the products associated with them. This was because changing the related investigation_products did not cause the no_changes? method in update_risk_assessment to return true. This commit fixes this issue.
> Fix risk assessment edit bug

- .github/workflows/deploy.yml
Fix deploy workflow to run smoke test without 2FA
> run smoke test without 2FA

- app/decorators/investigation_decorator.rb
- app/views/products/_cases.html.erb
- spec/decorators/investigation_decorator_spec.rb
(https://regulatorydelivery.atlassian.net/browse/PSD-1478?atlOrigin=eyJpIjoiYjA5NTVmNjFhNGI3NDRjOTllMjdlZjM0YmYyZmZjNTgiLCJwIjoiaiJ9)
This is a response to a bug when super users do not see the link to restricted cases created against a given product.
We removed the ability to restrict cases so this is really a bug for older cases. I've added some extra logic to the decorator - rather than creating extra partials and methods into the policy for now.
> Updated investigation decorator to show title link for super users

- app/controllers/concerns/cookies_concern.rb
- app/views/help/cookies_policy.html.erb
- spec/requests/cookies_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1490
Changes the cookie consent cookie to be remembered for 1 year rather than the duration of the browser session.
This means users that respond to the cookie banner will not see it again for 1 year or until they delete all cookies.
N/A
> Remember cookie consent

- app/controllers/investigations/overseas_regulator_controller.rb
- app/forms/overseas_regulator_form.rb
- app/helpers/application_helper.rb
- app/helpers/investigations_helper.rb
- app/models/audit_activity/investigation/change_overseas_regulator.rb
- app/models/country.rb
- app/policies/investigation_policy.rb
- app/services/change_overseas_regulator.rb
- app/views/investigations/_pages_top.html.erb
- app/views/investigations/activities/investigation/_change_overseas_regulator.html.erb
- app/views/investigations/overseas_regulator/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20230511145908_add_overseas_regulator_to_investigations.rb
- db/schema.rb
- spec/features/change_notifying_country_spec.rb
- spec/features/change_overseas_regulator_spec.rb
- spec/models/audit_activity/investigation/change_overseas_regulator_spec.rb
- spec/policies/investigation_policy_spec.rb
- spec/services/change_overseas_regulator_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1480
Adds a new overseas regulator field to cases and allows OPSS users and super users to view and change it.
> Add overseas regulator field to cases

- app/helpers/countries_helper.rb
- app/models/country.rb
- app/views/application/_business_heading.html.erb
- app/views/application/_page_heading.html.erb
- app/views/businesses/_form.html.erb
- app/views/businesses/edit.html.erb
- app/views/businesses/show.html.erb
- app/views/contacts/_form.html.erb
- app/views/contacts/edit.html.erb
- app/views/contacts/new.html.erb
- app/views/investigations/businesses/index.html.erb
- app/views/investigations/businesses/new.html.erb
- app/views/locations/_address_form.html.erb
- app/views/locations/_form.html.erb
- config/locales/en.yml
- spec/features/add_a_contact_to_a_business_spec.rb
- spec/features/add_business_to_a_case_spec.rb
- spec/features/add_location_to_a_business_spec.rb
- spec/features/editing_business_details_spec.rb
- spec/features/update_a_business_contact_spec.rb
Redesigned business form page, for both editing business (via cases or business tab) and creating new businesses (via cases only)
- removes autocomplete from location country dropdown
- adds new helper for country list where UK is first & then preselected
> Businesses form redesign

- app/decorators/test/result_decorator.rb
- app/helpers/tests_helper.rb
- app/models/audit_activity/test/result.rb
- app/views/investigations/activities/test/_result.html.erb
- app/views/investigations/tabs/_supporting_information.html.erb
- app/views/investigations/test_results/funding_certificate/new.html.erb
- app/views/investigations/test_results/show.html.erb
- config/locales/en.yml
- spec/features/add_test_results_spec.rb
Adds the funding information for test results
https://regulatorydelivery.atlassian.net/browse/PSD-1576
> Show if tests are funded by OPSS (PSD-1576)

- app/forms/test_result_form.rb
- app/views/investigations/test_results/edit.html.erb
- config/locales/en.yml
- spec/features/edit_test_result_spec.rb
Change edit page for test results on cases
> update edit test result page

- Gemfile
- Gemfile.lock
This PR updating postgres pg gem might be breaking the production redacted export 
Reverts OfficeForProductSafetyAndStandards/product-safety-database#2393
> Revert "Bump pg from 1.4.6 to 1.5.3"

- app/controllers/investigations/businesses_controller.rb
- app/forms/add_business_to_case_form.rb
- spec/rake/redacted_export_rake_task_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1681
The fix to redacted export was broken due to `Location` and `Business` being instantiated at class level, breaking the eager load of the Rails app. The fix however meant that on the new business form, if a user submits with nothing filled in, they are then presented with a form without Contact and Address fieldsets (as they are now blank on the object)
Moving them to the form here means the attributes always built, and the form works as it should
I've also here added a rake task spec to run the redacted export rake, to make sure we don't break eager loading again in the same way
> Fix business form regression

- app/decorators/corrective_action_decorator.rb
- app/decorators/risk_assessment_decorator.rb
- app/decorators/test/result_decorator.rb
- app/models/product_export.rb
- spec/decorators/corrective_action_decorator_spec.rb
- spec/decorators/risk_assessment_decorator_spec.rb
- spec/decorators/test/result_decorator_spec.rb
- spec/models/product_export_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1613
For CBAS team, to help them link supporting information with each case automatically, which is tricky now that product decoupling has taken place.
- Adds new `case_id` to all supporting information rows in product export 
- Adds specs covering decorators
> Add case_id to supporting info in product export

- app/decorators/investigation/enquiry_decorator.rb
- app/decorators/investigation/project_decorator.rb
- spec/decorators/investigation/enquiry_decorator_spec.rb
- spec/decorators/investigation/project_decorator_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1712
This should fix the broken mailers
- Added missing #title decorator method for enquiry, project cases
I did add a action mailer preview file for these, but because the mail is going through Notify, only the template params are rendered, so not that helpful
> Add missing decorator methods, fixing mailers - PSD-1712

- app/decorators/investigation/enquiry_decorator.rb
- app/decorators/investigation/project_decorator.rb
- spec/decorators/investigation/enquiry_decorator_spec.rb
- spec/decorators/investigation/project_decorator_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1712
This should fix the broken mailers
Hotfix onto main branch
> Hotfix: Added missing #title decorator method for enquiry, project cases

- app/controllers/application_controller.rb
- app/controllers/prism_risk_assessments_controller.rb
- app/models/prism_risk_assessment.rb
- app/models/user.rb
- app/policies/prism_risk_assessment_policy.rb
- app/views/homepage/authenticated.html.erb
- app/views/prism_risk_assessments/_no_prism_risk_assessments.html.erb
- app/views/prism_risk_assessments/heading/_your_prism_risk_assessments.html.erb
- app/views/prism_risk_assessments/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/prism_risk_assessment_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1691
Adds links to a new PRISM risk assessment dashboard from PSD for users with the `prism` role.
The dashboard will be populated once the PRISM data structures are finalised.
> PRISM: risk assessment from PSD (PSD-1691)

- config/constants/whitelisted_emails.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1716
Adds the domain `torfaen.gov.uk` to the email whitelist after splitting from `blaenau-gwent.gov.uk`.
N/A
> Whitelist torfaen.gov.uk

- db/migrate/20230704140908_add_safety_legislation_to_prism_product_market_details.prism.rb
- db/migrate/20230705110026_fix_foreign_keys_for_prism_tables.prism.rb
- db/schema.rb
- prism/app/controllers/prism/tasks_controller.rb
- prism/app/models/prism/harm_scenario.rb
- prism/app/models/prism/product_market_detail.rb
- prism/app/models/prism/risk_assessment.rb
- prism/app/validators/array_intersection_validator.rb
- prism/app/views/prism/tasks/add_details_about_products_in_use_and_safety.html.erb
- prism/app/views/prism/tasks/search_or_add_a_new_product.html.erb
- prism/config/locales/en.yml
- prism/db/migrate/20230704140750_add_safety_legislation_to_prism_product_market_details.rb
- prism/db/migrate/20230705105415_fix_foreign_keys_for_prism_tables.rb
- spec/factories/prism/risk_assessment.rb
- spec/features/prism/tasks_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1730
Adds the “Add details about products in use and safety” page.
Also fixes some database fields and adds a placeholder product search page pending work on general product search.
> PRISM: add details about products in use and safety

- db/migrate/20230705124426_add_fields_to_prism_product_hazards.prism.rb
- db/schema.rb
- prism/app/controllers/prism/tasks_controller.rb
- prism/app/helpers/prism/tasks_helper.rb
- prism/app/models/prism/product_hazard.rb
- prism/app/views/prism/tasks/add_a_number_of_hazards_and_subjects_of_harm.html.erb
- prism/config/locales/en.yml
- prism/db/migrate/20230705124301_add_fields_to_prism_product_hazards.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1654
Adds the “number of hazards and subjects of harm” page and makes some minor design tweaks.
> PRISM: number of hazards and subjects of harm

- app/forms/add_business_to_case_form.rb
- app/models/location.rb
- app/views/locations/_address_form.html.erb
- spec/features/add_business_to_a_case_spec.rb
- spec/features/editing_business_details_spec.rb
- spec/forms/add_business_to_case_form_spec.rb
- spec/models/location_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1620
For adding businesses to cases, as well as updating old businesses - allows blank country by default, but ensures one is added -
> Business country validation - PSD-1620

- app/controllers/investigations_controller.rb
- app/controllers/searches_controller.rb
- app/helpers/investigations_helper.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1740
Changes the investigation listing pages to use normal ActiveRecord queries rather than OpenSearch. Searches across all investigations still use OpenSearch.
N/A
> Move investigation listings from OpenSearch to ActiveRecord

- app/javascript/dynamic_nested_step_fields.js
- app/views/prism_risk_assessments/_table_row.html.erb
- db/migrate/20230719134949_add_probability_evidence_description_to_prism_harm_scenario_steps.prism.rb
- db/schema.rb
- prism/app/controllers/prism/tasks_controller.rb
- prism/app/helpers/prism/tasks_helper.rb
- prism/app/javascript/locales/en.json
- prism/app/models/prism/harm_scenario.rb
- prism/app/models/prism/harm_scenario_step.rb
- prism/app/models/prism/product_hazard.rb
- prism/app/models/prism/risk_assessment.rb
- prism/app/views/prism/tasks/_harm_scenario_step_fields.html.erb
- prism/app/views/prism/tasks/add_a_harm_scenario_and_probability_of_harm.html.erb
- prism/app/views/prism/tasks/add_uncertainty_and_sensitivity_analysis.html.erb
- prism/app/views/prism/tasks/determine_severity_of_harm.html.erb
- prism/app/views/prism/tasks/determine_severity_of_harm_casualties.html.erb
- prism/config/initializers/constants.rb
- prism/config/locales/en.yml
- prism/db/migrate/20230719134900_add_probability_evidence_description_to_prism_harm_scenario_steps.rb
- prism/lib/prism/risk_matrix.rb
- spec/features/prism/tasks_spec.rb
JIRA tickets: https://regulatorydelivery.atlassian.net/browse/PSD-1728, https://regulatorydelivery.atlassian.net/browse/PSD-1743, https://regulatorydelivery.atlassian.net/browse/PSD-1661
Adds the following three pages:
* Severity of harm
* Severity of harm casualties
* Uncertainty and sensitivity analysis
Also:
* Adds support for hidden tasks
* Removes some extraneous validation
* Fixes validation of probability frequency
* Fixes probability calculations
* Adds cascade delete to related models
* Fixes some bugs when adding multiple dynamic nested fields
* Makes some minor fixes to the dashboard
> PRISM: severity of harm, uncertainty and sensitivity analysis

- app/controllers/investigations/risk_assessments_controller.rb
- spec/features/view_a_risk_assessment_spec.rb
This authorise line came in as part of the breadcrumb work. The `show` action here wasn't part of the update policy assertion, and got added accidentally in the refactor
The controller before the refactor commits: https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/blob/462a83623dac433fab34d0ed0aa5e369f801bbf6/app/controllers/investigations/risk_assessments_controller.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1770
> HOTFIX: Risk assessments, all users should be able to view

- app/javascript/dynamic_nested_step_fields.js
- prism/app/assets/javascripts/prism/application.js
- prism/app/assets/javascripts/prism/overall_probability_of_harm.js
- prism/app/controllers/prism/api_controller.rb
- prism/app/helpers/prism/api_helper.rb
- prism/app/helpers/prism/tasks_helper.rb
- prism/app/services/prism/probability_service.rb
- prism/app/services/prism/risk_matrix_service.rb
- prism/app/views/layouts/prism/application.html.erb
- prism/app/views/prism/tasks/_harm_scenario_step_fields.html.erb
- prism/app/views/prism/tasks/add_a_harm_scenario_and_probability_of_harm.html.erb
- prism/app/views/prism/tasks/add_uncertainty_and_sensitivity_analysis.html.erb
- prism/app/views/prism/tasks/determine_severity_of_harm.html.erb
- prism/app/views/prism/tasks/determine_severity_of_harm_casualties.html.erb
- prism/config/routes.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1658
Changes the overall probability of harm on the harm scenarios page to update dynamically as the user changes intermediate probabilities.
N/A
> PRISM: add dynamic calculation of probability

- app/controllers/investigations/business_types_controller.rb
- app/controllers/investigations/businesses_controller.rb
- app/decorators/investigation_business_decorator.rb
- app/forms/add_business_to_case_form.rb
- app/forms/set_business_type_on_case_form.rb
- app/services/add_business_to_case.rb
- app/views/investigations/business_types/new.html.erb
- app/views/investigations/tabs/_businesses.html.erb
- config/locales/en.yml
- db/migrate/20230721141131_add_authorised_representative_choice_to_investigation_businesses.rb
- db/schema.rb
- spec/decorators/investigation_business_decorator_spec.rb
- spec/features/add_business_to_a_case_spec.rb
- spec/forms/set_business_type_on_case_form_spec.rb
- spec/services/add_business_to_case_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1617
Adds new business type 'authorised representative', and provides UK & EU options.
> Authorised representative businesses - PSD-1617

- config/constants/whitelisted_emails.yml
Adds `businessandtrade.gov.uk` to email domain whitelist
Ready for emails starting to transition early next week
> HOTFIX - Whitelist businessandtrade.gov.uk email domain

- config/constants/hazard_constants.yml
- db/migrate/20230731094750_migrate_electromagnetic_disturbance_hazards.rb
- db/schema.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1795
- Migrates all cases with 'Electromagnetic' or 'Disturbance' to just 'Electromagnetic disturbance' 
- Remove the old two options & replaces with the newer one for future cases
> PSD-1795 - Migrate cases to new "Electromagnetic disturbance" hazard

- app/helpers/products_helper.rb
- app/views/products/_form.html.erb
- spec/features/add_product_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1599
Changes the blank 'country of origin' in the product form to 'Unknown', is the form default so not selecting any country will now be consistently worded
> PSD-1599 - Blank product country of origin is labelled as unknown

- prism/app/controllers/prism/tasks/evaluate_controller.rb
- prism/app/helpers/prism/tasks/evaluate_helper.rb
- prism/app/javascript/locales/en.json
- prism/app/views/prism/tasks/evaluate/consider_perception_and_tolerability_of_the_risk.html.erb
- prism/config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1777
Adds the “consider perception and tolerability of the risk” page.
> PRISM: consider perception and tolerability of the risk

- prism/app/controllers/prism/tasks/evaluate_controller.rb
- prism/app/views/prism/tasks/evaluate/risk_evaluation_outcome.html.erb
- prism/config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1778
Adds the “risk evaluation outcome” page.
> PRISM: risk evaluation outcome

- app/views/products/duplicate_checks/show.html.erb
https://regulatorydelivery.atlassian.net/browse/PSD-1737
[For this error in Sentry](https://beis.sentry.io/issues/4304941494/?environment=staging&query=is%3Aarchived&referrer=issue-stream&statsPeriod=24h&stream_index=0). 
A duplicate product without an image was never an issue - but when the product has a stored PSD image, it would throw an exception
To reproduce:
1. Add a product with a new barcode
2. Add a new case, add that product to the case
3. Edit the product, add an image
4. Try and add a new product, lookup with the same barcode
5. This new code works, on staging you currently get a 500 
https://psd-pr-2537.london.cloudapps.digital/products/11/duplicate-check
> Fix duplicate image tag - PSD-1737

- prism/app/controllers/prism/tasks_controller.rb
- prism/app/controllers/prism/triage_controller.rb
- prism/app/views/prism/triage/full_risk_assessment_required.html.erb
- prism/app/views/prism/triage/index.html.erb
- prism/app/views/prism/triage/perform_risk_triage.html.erb
- prism/app/views/prism/triage/serious_risk.html.erb
- prism/config/routes.rb
- spec/features/prism/tasks_spec.rb
- spec/features/prism/triage_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1846
Changes the ordering of the triage pages and only enforces authentication once the user reaches the task list.
N/A
> PRISM: change order of triage pages

- app/views/investigations/_full_table_body.html.erb
- app/views/investigations/_status_table_row.html.erb
- app/views/investigations/index.html.erb
- spec/features/add_product_to_case_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1855
Adds a product count for each case index view
> Add product count to case index view - PSD-1855

- app/controllers/investigations/prism_risk_assessments_controller.rb
- app/models/investigation.rb
- app/models/prism_associated_investigation.rb
- app/models/prism_associated_investigation_product.rb
- app/models/prism_associated_product.rb
- app/models/prism_risk_assessment.rb
- app/views/investigations/_actions.html.erb
- app/views/investigations/prism_risk_assessments/choose_product.html.erb
- app/views/investigations/prism_risk_assessments/new.html.erb
- app/views/investigations/risk_assessments/new.html.erb
- app/views/investigations/risk_assessments/no_products.html.erb
- app/views/prism_risk_assessments/_table.html.erb
- config/routes.rb
- db/migrate/20230915145123_add_name_to_prism_risk_assessments.prism.rb
- db/schema.rb
- prism/app/models/prism/associated_investigation.rb
- prism/db/migrate/20230915145048_add_name_to_prism_risk_assessments.rb
- spec/features/add_a_risk_assessment_to_a_case_spec.rb
- spec/features/case_actions_spec.rb
- spec/support/features/page_expectations.rb
JIRA tickets: https://regulatorydelivery.atlassian.net/browse/PSD-1864, https://regulatorydelivery.atlassian.net/browse/PSD-1891
Adds functionality to assign an existing submitted PRISM risk assessment to a case where the risk assessment is already assigned to the product in question either directly or via another case.
> PRISM: PSD integration scenario 3

- db/migrate/20230918155916_remove_other_safety_legislation_standard_from_prism_product_market_details.prism.rb
- db/schema.rb
- package.json
- prism/app/assets/stylesheets/prism/_autocomplete.scss
- prism/app/assets/stylesheets/prism/application.scss
- prism/app/controllers/prism/tasks/define_controller.rb
- prism/app/models/prism/product_market_detail.rb
- prism/app/views/layouts/prism/application.html.erb
- prism/app/views/prism/tasks/define/add_details_about_products_in_use_and_safety.html.erb
- prism/config/locales/en.yml
- prism/db/migrate/20230918155754_remove_other_safety_legislation_standard_from_prism_product_market_details.rb
- spec/features/prism/risk_assessment_spec.rb
- spec/features/prism/tasks_spec.rb
- yarn.lock
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1906
Adds a multiple selection autocomplete component to select the relevant product legislation and standards.
> PRISM: add autocomplete component for product legislation

- prism/app/assets/javascripts/prism/overall_probability_of_harm_and_risk_level.js
- prism/app/models/prism/harm_scenario_step.rb
- prism/config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1916
Makes the harm scenario evidence file optional. Also fixes a bug where the probability and risk level disappear when the page is reloaded with an error.
N/A
> PRISM: make evidence file optional

- app/controllers/prism_risk_assessments_controller.rb
- app/helpers/breadcrumb_helper.rb
- app/models/prism_risk_assessment.rb
- app/views/prism_risk_assessments/_search_statement.html.erb
- app/views/prism_risk_assessments/_secondary_nav.html.erb
- app/views/prism_risk_assessments/heading/_all_prism_risk_assessments.html.erb
- app/views/prism_risk_assessments/heading/_team_prism_risk_assessments.html.erb
- app/views/prism_risk_assessments/index.html.erb
- config/locales/en.yml
- config/locales/loaf.en.yml
- config/routes.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1907
Adds “your”, “team” and “all” risk assessments to the dashboard to match other dashboards.
> PRISM: add your, team and all risk assessments

- app/models/product_export.rb
- spec/models/product_export_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1885
Adds a new case type column to every sheet in the product export spreadsheet.
N/A
https://psd-pr-2579.london.cloudapps.digital/
https://psd-pr-2579-support.london.cloudapps.digital/
> Add case type to product export

- app/forms/set_business_type_on_case_form.rb
- app/views/businesses/_form.html.erb
- app/views/investigations/business_types/new.html.erb
- config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1761
Adds a new “responsible person” business type.
https://psd-pr-2599.london.cloudapps.digital/
https://psd-pr-2599-support.london.cloudapps.digital/
> Add “responsible person” as a business type

- app/services/generate_product_recall_pdf.rb
- app/views/products/recalls/complete.html.erb
- app/views/products/recalls/product-details.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1925
* Pre-fill corrective actions from the case
* Don’t pre-fill the “notified by” field
* Use the value of the “notified by” field in the generated PDF and Markdown
N/A
https://psd-pr-2602.london.cloudapps.digital/
https://psd-pr-2602-support.london.cloudapps.digital/
> Product recall tool amendments

- app/helpers/businesses_helper.rb
- app/helpers/investigations_helper.rb
- app/helpers/products_helper.rb
- app/models/business_export.rb
- app/models/case_export.rb
- app/models/product_export.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1932
Fixes a bug where data exports were limited to default page size limits in OpenSearch and Kaminari.
Moves all export activity away from OpenSearch into Postgres and optimises queries to return all IDs.
N/A
https://psd-pr-2611.london.cloudapps.digital/
https://psd-pr-2611-support.london.cloudapps.digital/
> Remove limits on data exports

- app/views/products/recalls/complete.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1933
Removes the risk level and online marketplace fields from the Markdown templates.
N/A
https://psd-pr-2612.london.cloudapps.digital/
https://psd-pr-2612-support.london.cloudapps.digital/
> Product recall tool Markdown amendments

- app/helpers/businesses_helper.rb
- app/helpers/investigations_helper.rb
- app/helpers/products_helper.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1935
Fixes the search logic to correctly exclude adding filtering by query when no query string is provided.
N/A
https://psd-pr-2613.london.cloudapps.digital/
https://psd-pr-2613-support.london.cloudapps.digital/
> Allow empty searches

- app/controllers/products_controller.rb
- app/forms/product_form.rb
- app/helpers/products_helper.rb
- app/views/products/_form.html.erb
- app/views/products/edit.html.erb
- spec/features/sort_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1822
Adds functionality to attach an image when creating a product.
N/A
https://psd-pr-2609.london.cloudapps.digital/
https://psd-pr-2609-support.london.cloudapps.digital/
> Add product image to product creation

- app/controllers/investigations/ts_investigations_controller.rb
- app/models/investigation/case.rb
- app/models/investigation/notification.rb
- db/migrate/20231012141513_change_all_cases_to_notifications.rb
- db/schema.rb
- spec/decorators/investigation_decorator_spec.rb
- spec/factories/investigations.rb
- spec/forms/notifying_country_form_spec.rb
- spec/models/audit_activity/investigation/add_case_spec.rb
- spec/models/investigation/case_spec.rb
- spec/models/investigation/enquiry_spec.rb
- spec/models/investigation/notification_spec.rb
- spec/models/investigation/project_spec.rb
- spec/services/find_closest_product_duplicate_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1947
Changes Case class to Notification for clarity, adds a `case_type=notification`for reports/exports and changes all current `Investigation::Case` objects to `Investigation::Notification`
https://psd-pr-2618.london.cloudapps.digital/
https://psd-pr-2618-support.london.cloudapps.digital/
> Rename case to notification - PSD-1947

- app/views/businesses/tabs/_contacts.html.erb
- app/views/businesses/tabs/_locations.html.erb
- config/initializers/content_security_policy.rb
- manifest.review.yml
- prism/app/assets/javascripts/prism/overall_probability_of_harm_and_risk_level.js
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2018
Fixes the following errors that are spamming Sentry:
* Missing CSP directives for data URIs for images
* Inline CSS rules
* Errors when initialising review app databases
N/A
https://psd-pr-2621.london.cloudapps.digital/
https://psd-pr-2621-support.london.cloudapps.digital/
> Fix high-volume errors being reported to Sentry

- app/services/add_corrective_action_to_case.rb
- spec/services/add_corrective_action_to_case_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1528
Automatically adds OPSS IMT with edit permissions to a case when a corrective action is added if:
* The investigation risk level is serious or high, or
* The corrective action indicates a recall
N/A
https://psd-pr-2622.london.cloudapps.digital/
https://psd-pr-2622-support.london.cloudapps.digital/
> Add OPSS IMT to case when adding a corrective action

- app/helpers/investigations_helper.rb
- app/views/searches/show.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1895
Detects searching for investigations by pretty ID and disables edit distance so only relevant results are returned.
Also fixes the display of investigation search results in the table.
https://psd-pr-2625.london.cloudapps.digital/
https://psd-pr-2625-support.london.cloudapps.digital/
> Only return relevant investigations when searching by ID

- app/helpers/investigations_helper.rb
- app/helpers/search_params.rb
- app/serializers/investigation_serializer.rb
- app/views/investigations/_case_change_date_filter.html.erb
- spec/features/search_cases_spec.rb
- spec/models/case_export_spec.rb
- spec/serializers/investigation_serializer_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2023
Based on feedback from Monika - the case date filter should be...
- Just searching the case `created_at` time
- and allow you to search both from and up to a certain date
https://psd-pr-2632.london.cloudapps.digital/
> Case extract by created date: part II - PSD-2023

- app/controllers/bulk_products_controller.rb
- app/forms/bulk_products_create_case_form.rb
- app/forms/bulk_products_triage_form.rb
- app/models/bulk_products_upload.rb
- app/services/create_case.rb
- app/views/bulk_products/create_case.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20231019104345_create_bulk_products_uploads.rb
- db/schema.rb
- spec/features/bulk_upload_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1871
Adds the case creation page for bulk product uploads.
https://psd-pr-2635.london.cloudapps.digital/
https://psd-pr-2635-support.london.cloudapps.digital/
> Add case creation for bulk product uploads

- app/controllers/bulk_products_controller.rb
- app/forms/bulk_products_add_business_details_form.rb
- app/forms/bulk_products_add_business_type_form.rb
- app/models/bulk_products_upload.rb
- app/services/add_business_to_case.rb
- app/views/bulk_products/add_business_details.html.erb
- app/views/bulk_products/create_business.html.erb
- app/views/bulk_products/create_case.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20231020120918_add_investigation_business_to_bulk_products_uploads.rb
- db/schema.rb
- spec/features/bulk_upload_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1872
Adds the business creation pages for bulk product uploads.
https://psd-pr-2640.london.cloudapps.digital/
https://psd-pr-2640-support.london.cloudapps.digital/
> Add business creation for bulk product uploads

- app/controllers/investigations_controller.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2038
When all search filters are set as 'all' or kept as default, and new date filters are used, the result count is not accurate. 
This PR fixes that search count to detect when a date filter is used
### After
https://psd-pr-2641.london.cloudapps.digital/
https://psd-pr-2641-support.london.cloudapps.digital/
> Fix case search counts with all cases & created date filters - PSD-2038

- app/services/add_corrective_action_to_case.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2037
Fixes an issue when attempting to create a new corrective action which triggers adding OPSS IMT to the case when they have already been added.
The nested transaction aborts, which also aborts the outer transaction and prevents the corrective action from being created.
N/A
https://psd-pr-2643.london.cloudapps.digital/
https://psd-pr-2643-support.london.cloudapps.digital/
> Fix adding OPSS IMT team to case on corrective action

- app/services/add_corrective_action_to_case.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2053
Sends an email to OPSS IMT members when the team is automatically added to a case due to the severity level or corrective action.
N/A
https://psd-pr-2648.london.cloudapps.digital/
https://psd-pr-2648-support.london.cloudapps.digital/
> Notify OPSS IMT when adding them to a case

- app/forms/product_form.rb
- spec/features/add_product_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2051
Correctly uploads the image on product creation if the product is initially valid.
N/A
https://psd-pr-2651.london.cloudapps.digital/
https://psd-pr-2651-support.london.cloudapps.digital/
> Upload image on product creation

- app/forms/corrective_action_form.rb
- app/forms/test_result_form.rb
- app/models/correspondence.rb
- app/views/investigations/accident_or_incidents/_form.html.erb
- app/views/investigations/record_emails/_form_fields.html.erb
- app/views/investigations/record_phone_calls/_form.html.erb
- app/views/investigations/test_results/_form.html.erb
- spec/forms/corrective_action_form_spec.rb
- spec/forms/test_result_form_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2060
Changes all free text fields that were previously limited to 50,000 characters to instead be limited to 32,767 characters.
This is due to these fields being exportable to XLSX spreadsheets that have a per-cell character limit of 32,767.
N/A
https://psd-pr-2653.london.cloudapps.digital/
https://psd-pr-2653-support.london.cloudapps.digital/
> Limit free text fields to 32,767 characters

- app/controllers/bulk_products_controller.rb
- app/forms/bulk_products_upload_products_file_form.rb
- app/models/bulk_products_upload.rb
- app/services/create_bulk_products_upload.rb
- app/services/create_bulk_products_upload_business.rb
- app/services/create_bulk_products_upload_products.rb
- app/services/update_bulk_products_upload_business.rb
- app/services/update_bulk_products_upload_case.rb
- db/migrate/20231101140817_add_business_to_bulk_products_uploads.rb
- db/migrate/20231101140826_create_bulk_products_uploads_products_join_table.rb
- db/schema.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2081
* Moves large scale data tasks to separate services
* Fixes a bug when attempting to continue without choosing a file
* Keeps track of businesses and proucts created and adds a method to clean up
N/A
https://psd-pr-2658.london.cloudapps.digital/
https://psd-pr-2658-support.london.cloudapps.digital/
> Refactor bulk products uploads

- app/controllers/bulk_products_controller.rb
- app/forms/bulk_products_choose_products_for_corrective_actions_form.rb
- app/javascript/controllers/application.js
- app/services/add_corrective_action_to_case.rb
- app/services/create_bulk_products_upload_business.rb
- app/views/bulk_products/choose_products_for_corrective_actions.html.erb
- app/views/bulk_products/create_corrective_action.html.erb
- config/locales/en.yml
- config/routes.rb
- package.json
- spec/features/bulk_upload_products_spec.rb
- yarn.lock
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1876
Adds two pages to create corrective actions for bulk product uploads.
https://psd-pr-2659.london.cloudapps.digital/
https://psd-pr-2659-support.london.cloudapps.digital/
> Add corrective actions for bulk product uploads

- app/assets/stylesheets/application.scss
- app/controllers/bulk_products_controller.rb
- app/controllers/investigations/corrective_actions_controller.rb
- app/forms/bulk_products_upload_products_file_form.rb
- app/services/update_bulk_products_upload_business.rb
- app/views/bulk_products/check_corrective_actions.html.erb
- app/views/bulk_products/choose_products_for_corrective_actions.html.erb
- app/views/bulk_products/upload_products_file.html.erb
- app/views/investigations/corrective_actions/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20231102164229_add_submitted_at_to_bulk_products_uploads.rb
- db/schema.rb
- db/seeds.rb
- spec/features/bulk_upload_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1904
Adds the corrective action confirmation page and completion for bulk product uploads.
https://psd-pr-2660.london.cloudapps.digital/
https://psd-pr-2660-support.london.cloudapps.digital/
> Confirmation for bulk products upload

- app/controllers/bulk_products_controller.rb
- app/services/add_product_to_case.rb
- app/services/create_bulk_products_upload_products.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2097
Saves the case-level details for existing products added during bulk product uploads. This includes batch numbers, customs codes and units affected.
N/A
https://psd-pr-2666.london.cloudapps.digital/
https://psd-pr-2666-support.london.cloudapps.digital/
> Save case details for existing products when bulk uploading

- app/forms/bulk_products_upload_products_file_form.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2101
Fixes a bug when a spreadsheet row is returned as `nil`.
N/A
https://psd-pr-2667.london.cloudapps.digital/
https://psd-pr-2667-support.london.cloudapps.digital/
> Fix issue with empty row handling for bulk product uploads

- app/forms/bulk_products_add_business_details_form.rb
- config/locales/en.yml
- spec/features/bulk_upload_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2096
Prevents displaying the business trading name if it is the default assigned when the business was created to force the user to enter their own. Also adds validation to prevent a default business name being saved.
N/A
https://psd-pr-2665.london.cloudapps.digital/
https://psd-pr-2665-support.london.cloudapps.digital/
> Prevent users from accepting default business name for bulk product uploads

- app/controllers/investigations_controller.rb
- app/controllers/products_controller.rb
- app/models/bulk_products_upload.rb
- app/views/application/_incomplete_bulk_products_upload_notification.html.erb
- app/views/investigations/heading/_all_cases.html.erb
- app/views/investigations/show.html.erb
- app/views/products/heading/_all_products.html.erb
- spec/features/bulk_upload_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2102
Shows a banner on the all cases and all products pages when the current user has one or more incomplete bulk products uploads. Also shows the banner on the case page of a case associated with an incomplete bulk products upload.
https://psd-pr-2668.london.cloudapps.digital/
https://psd-pr-2668-support.london.cloudapps.digital/
> Allow resumption of incomplete bulk products upload journeys

- db/migrate/20231109111428_add_sensitivity_analysis_details_to_prism_evaluations.prism.rb
- db/schema.rb
- prism/app/controllers/prism/tasks/evaluate_controller.rb
- prism/app/helpers/prism/tasks/evaluate_helper.rb
- prism/app/models/prism/evaluation.rb
- prism/app/services/prism/risk_assessment_pdf_service.rb
- prism/app/views/prism/tasks/evaluate/add_level_of_uncertainty_and_sensitivity_analysis.html.erb
- prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_assessment.html.erb
- prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_evaluation.html.erb
- prism/app/views/prism/tasks/view_submitted_assessment.html.erb
- prism/db/migrate/20231109111312_add_sensitivity_analysis_details_to_prism_evaluations.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2080
Adds an optional text area to enter more details if sensitivity analysis has been undertaken.
https://psd-pr-2672.london.cloudapps.digital/
https://psd-pr-2672-support.london.cloudapps.digital/
> PRISM: add sensitivity analysis details

- app/views/prism_risk_assessments/_table.html.erb
- app/views/prism_risk_assessments/_table_row.html.erb
- prism/app/controllers/prism/tasks_controller.rb
- prism/app/views/prism/tasks/remove.html.erb
- prism/config/routes.rb
- spec/features/prism_risk_assessment_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2103
Allows draft risk assessments to be deleted by the creating user.
N/A
https://psd-pr-2673.london.cloudapps.digital/
https://psd-pr-2673-support.london.cloudapps.digital/
> PRISM: allow drafts to be deleted

- prism/app/controllers/prism/tasks/evaluate_controller.rb
- prism/app/views/prism/tasks/evaluate/confirm_overall_product_risk.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2049
Changes the risk level choice criteria as follows:
* One harm scenario -> risk level of the harm scenario
* More than one harm scenario with different severity levels and/or identical hazard types -> highest risk level
* More than one harm scenario with identical severity levels and different hazard types -> choice between highest and combined risk level
The risk level plus label is also only displayed for multiple hazard types.
N/A
https://psd-pr-2674.london.cloudapps.digital/
https://psd-pr-2674-support.london.cloudapps.digital/
> PRISM: Change risk level choice criteria

- app/controllers/bulk_products_controller.rb
- app/views/bulk_products/no_upload_mixed.html.erb
- app/views/bulk_products/no_upload_unsafe.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2120
Removes the links to PRISM for users that do not have PRISM access when they attempt to bulk upload multiple unsafe products or a mix of unsafe and non-compliant products.
N/A
https://psd-pr-2679.london.cloudapps.digital/
https://psd-pr-2679-support.london.cloudapps.digital/
> Remove PRISM links for non-PRISM users for bulk products uploads

- app/assets/stylesheets/_psd_header.scss
- app/assets/stylesheets/opss/_opss-psd.scss
- app/assets/stylesheets/opss/_opss-shared.scss
- app/assets/stylesheets/opss/_opss-step-by-step-nav.scss
- app/javascript/menu.js
- package.json
- yarn.lock
Upgrades `govuk-frontend` from 4.6.0 to 4.7.0 and fixes some deprecations.
N/A
https://psd-pr-2686.london.cloudapps.digital/
https://psd-pr-2686-support.london.cloudapps.digital/
> Upgrade govuk-frontend

- app/views/bulk_products/triage.html.erb
- config/locales/en.yml
- spec/features/bulk_upload_products_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2131
Updates the error message and textbox label for why the products are non-compliant to be plural.
N/A
https://psd-pr-2707.london.cloudapps.digital/
https://psd-pr-2707-support.london.cloudapps.digital/
> Update error message for bulk products uploads

- support_portal/lib/support_portal/engine.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2140
Fixes an issue in `production` Rails enviroinments where visiting the Support Portal root path incorrectly redirects to the sign in path for the parent app.
N/A
https://psd-pr-2709.london.cloudapps.digital/
https://psd-pr-2709-support.london.cloudapps.digital/
> OSU Support Portal: fix redirection issue

- support_portal/app/controllers/concerns/support_portal/secondary_authentication_concern.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2142
Fixes the 2FA concern for the OSU Support Portal to correctly redirect to the 2FA page.
N/A
https://psd-pr-2710.london.cloudapps.digital/
https://psd-pr-2710-support.london.cloudapps.digital/
> OSU Support Portal: fix 2FA redirection

- app/controllers/case_exports_controller.rb
- app/models/case_export.rb
- spec/models/case_export_spec.rb
- Correctly redirects users of new search to the right page after running an extract.
- Fix next page scrolling on opensearch for extract
https://psd-pr-2712.london.cloudapps.digital/
https://psd-pr-2712-support.london.cloudapps.digital/
> fix case export issues

- spec/features/support_portal/account_administration_spec.rb
- support_portal/app/controllers/support_portal/account_administration_controller.rb
- support_portal/app/models/support_portal/add_role_form.rb
- support_portal/app/views/support_portal/account_administration/_account_details.html.erb
- support_portal/app/views/support_portal/account_administration/_account_roles.html.erb
- support_portal/app/views/support_portal/account_administration/add_role.html.erb
- support_portal/app/views/support_portal/account_administration/index.html.erb
- support_portal/app/views/support_portal/account_administration/invite_user.html.erb
- support_portal/app/views/support_portal/account_administration/remove_role.html.erb
- support_portal/app/views/support_portal/account_administration/show.html.erb
- support_portal/config/routes.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2144
Adds functionality to add and remove user roles.
https://psd-pr-2718.london.cloudapps.digital/
https://psd-pr-2718-support.london.cloudapps.digital/
> OSU Support Portal: add user role management

- prism/app/services/prism/risk_assessment_pdf_service.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2153
Adds the names of files uploaded as evidence in PRISM in the generated PDF.
Also handles issues with unknown image types in Prawn by retrying without images.
N/A
https://psd-pr-2725.london.cloudapps.digital/
https://psd-pr-2725-support.london.cloudapps.digital/
> PRISM: Add evidence file name to generated PDF

- spec/features/support_portal/account_administration_spec.rb
- support_portal/app/views/support_portal/account_administration/show.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2157
Removes the “delete account” button when viewing user account details.
N/A
https://psd-pr-2726.london.cloudapps.digital/
https://psd-pr-2726-support.london.cloudapps.digital/
> OSU Support Portal: remove delete account button

- config/initializers/devise.rb
- lib/devise/custom_failure_app.rb
- support_portal/lib/support_portal/engine.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2207
Fixes an issue where editing records in PSD attempts to redirect to the support portal host.
N/A
https://psd-pr-2739.london.cloudapps.digital/
https://psd-pr-2739-support.london.cloudapps.digital/
> Fix redirecting from PSD to support portal

- app/helpers/investigations_helper.rb
- app/helpers/search_params.rb
- app/serializers/investigation_serializer.rb
- app/views/notifications/_filters.html.erb
- app/views/notifications/_reported_reason_checkboxes.html.erb
- spec/features/search_notifications_spec.rb
- spec/models/case_export_spec.rb
Adds a filter for searching notifications on. the reported reason.
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?assignee=6411e6661273131f2ae0b4b2&selectedIssue=PSD-2227
https://psd-pr-2751.london.cloudapps.digital/
https://psd-pr-2751-support.london.cloudapps.digital/
> add filter for reported reason on notification search

- app/helpers/products_helper.rb
- spec/features/products_spec.rb
Adds the ability to search for products by their brand name
Fixes a commented out spec as well around product search - the button wasn't being pressed properly 
https://psd-pr-2756.london.cloudapps.digital/
> Allow search by product brand name - PSD-2243

- app/forms/bulk_products_upload_products_file_form.rb
- app/forms/product_recall_form.rb
- app/helpers/products_helper.rb
- app/services/generate_product_recall_pdf.rb
- app/views/products/recalls/product-details.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2264
Adds the ability to choose “unsure” for the authenticity of a product.
N/A
https://psd-pr-2764.london.cloudapps.digital/
https://psd-pr-2764-support.london.cloudapps.digital/
> Re-add “unsure” option for product authenticity

- app/models/bulk_products_uploads_product.rb
- app/services/csv_exporter.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2280
Adds missing namespaced tables to the CSV export.
N/A
https://psd-pr-2769.london.cloudapps.digital/
https://psd-pr-2769-support.london.cloudapps.digital/
> Add namespaced tables to CSV export

- app/helpers/investigations_helper.rb
- app/views/businesses/index.html.erb
- app/views/investigations/_filters.html.erb
- app/views/notifications/_filters.html.erb
- app/views/products/_filters.html.erb
- app/views/products/heading/_team_products.html.erb
- app/views/products/heading/_your_products.html.erb
- spec/features/products_navigation_spec.rb
JIRA tickets: https://regulatorydelivery.atlassian.net/browse/PSD-1348, https://regulatorydelivery.atlassian.net/browse/PSD-1083, https://regulatorydelivery.atlassian.net/browse/PSD-1075
* Don’t show “optional reference number” when the reference number is not present
* Amend hint text on your and team products pages
* Fix mobile alignment for download as XLSX hint block
N/A
https://psd-pr-2774.london.cloudapps.digital/
https://psd-pr-2774-support.london.cloudapps.digital/
> Fix hint text issues

- app/helpers/breadcrumb_helper.rb
Provides the notifications_path for the breadcrumbs for a user using the new search
> use correct breadcrumb for new notifications search

- app/models/case_export.rb
- spec/models/case_export_spec.rb
Add unsafe reason to notification extract
https://psd-pr-2802.london.cloudapps.digital/
https://psd-pr-2802-support.london.cloudapps.digital/
> add unsafe reason to notifications extract

- app/controllers/notifications/create_controller.rb
- app/forms/change_notification_product_safety_compliance_details_form.rb
- app/helpers/notifications/create_helper.rb
- app/views/investigations/_create_a_case_link.html.erb
- app/views/investigations/_create_a_notification_link.html.erb
- app/views/investigations/heading/_all_cases.html.erb
- app/views/investigations/heading/_assigned_cases.html.erb
- app/views/investigations/heading/_team_cases.html.erb
- app/views/investigations/heading/_your_cases.html.erb
- app/views/notifications/create/add_notification_details.html.erb
- app/views/notifications/create/add_product_safety_and_compliance_details.html.erb
- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2013
Add the “add product safety and compliance details” task.
Also changes the “create a notification” link from the notification search pages to link to the task list when the user has the relevant role.
https://psd-pr-2826.london.cloudapps.digital/
https://psd-pr-2826-support.london.cloudapps.digital/
> Notification task list: add product safety and compliance details

- app/assets/stylesheets/opss/_opss-search.scss
- app/views/investigations/_case_type_radios.html.erb
- app/views/investigations/_filters.html.erb
- spec/features/export_cases_spec.rb
- spec/features/filter_notifications_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2297
- Changes copy of notification type filter to just 'Type'
- Hides for non-OPSS user roles
> Hide notification type filter for non OPSS - PSD-2297

- app/controllers/notifications/create_controller.rb
- app/forms/change_notification_product_safety_compliance_details_form.rb
- app/helpers/notifications/create_helper.rb
- app/services/change_batch_number.rb
- app/services/change_customs_code.rb
- app/services/change_number_of_affected_units.rb
- app/services/change_safety_and_compliance_data.rb
- app/services/change_ucr_numbers.rb
- app/views/notifications/create/_ucr_numbers_form.html.erb
- app/views/notifications/create/add_business_details.html.erb
- app/views/notifications/create/add_notification_details.html.erb
- app/views/notifications/create/add_product_identification_details.html.erb
- app/views/notifications/create/add_product_identification_details_batch_numbers.html.erb
- app/views/notifications/create/add_product_identification_details_customs_codes.html.erb
- app/views/notifications/create/add_product_identification_details_number_of_affected_units.html.erb
- app/views/notifications/create/add_product_identification_details_ucr_numbers.html.erb
- app/views/notifications/create/add_product_safety_and_compliance_details.html.erb
- app/views/notifications/create/index.html.erb
- app/views/notifications/create/search_for_or_add_a_product.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2252
Adds the “add product identification details” task including batch numbers, customs codes, UCR numbers and number of units affected.
Also:
* Fixes display of form submission errors in the body and title of the page
* Hides unsafe/non-compliant checkboxes if the notification as already been marked as “safe and compliant”
* Fixes saving of unsafe/non-compliant data
* Adds a placeholder page for section 3 to allow progress to section 4
* Fixes logic to allow all optional tasks to be enabled simultaneously as well as the next mandatory task
https://psd-pr-2829.london.cloudapps.digital/
https://psd-pr-2829-support.london.cloudapps.digital/
> Notifications task list: add product identification details

- app/controllers/notifications/create_controller.rb
- app/services/remove_product_from_notification.rb
- app/views/notifications/create/remove_product.html.erb
- app/views/notifications/create/search_for_or_add_a_product.html.erb
- config/routes.rb
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2312
Allows products to be removed from a notification before the “search for or add a product” task has been marked as completed.
N/A
https://psd-pr-2831.london.cloudapps.digital/
https://psd-pr-2831-support.london.cloudapps.digital/
> Notification task list: allow product removal

- app/helpers/investigations_helper.rb
- app/views/notifications/_filters.html.erb
- spec/features/cases_spec.rb
- spec/features/edit_a_product_spec.rb
- spec/features/editing_business_details_spec.rb
- spec/features/filter_notifications_spec.rb
- spec/features/search_cases_spec.rb
- spec/features/search_notifications_spec.rb
- spec/requests/export_cases_spec.rb
Remove type filter for non-opss users
https://psd-pr-2832.london.cloudapps.digital/
https://psd-pr-2832-support.london.cloudapps.digital/
> 2300 2337 remove type filter for non-opss users

- app/models/case_export.rb
- spec/models/case_export_spec.rb
- spec/requests/export_cases_spec.rb
Rearranges column order for notification extract
https://psd-pr-2833.london.cloudapps.digital/
https://psd-pr-2833-support.london.cloudapps.digital/
> PSD 2320 rearrange column order on notification extract

- app/assets/stylesheets/application.scss
- app/controllers/notifications/create_controller.rb
- app/decorators/test/result_decorator.rb
- app/views/notifications/create/add_supporting_documents.html.erb
- app/views/notifications/create/add_supporting_images.html.erb
- app/views/notifications/create/remove_test_report.html.erb
- app/views/notifications/create/remove_upload.html.erb
- config/routes.rb
- spec/features/notification_task_list_spec.rb
JIRA tickets: https://regulatorydelivery.atlassian.net/browse/PSD-2258 and https://regulatorydelivery.atlassian.net/browse/PSD-2331
Adds the “add supporting images” and “add supporting documents” tasks.
https://psd-pr-2845.london.cloudapps.digital/
https://psd-pr-2845-support.london.cloudapps.digital/
> Notification task list: add supporting images and documents

- db/migrate/20240124120110_change_ahoy_user_ids_to_uuids.rb
- db/schema.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2389
Migrates the Ahoy tables to use uuids for `user_id` - this column is optional, but we intended to link users to activity. User uses uuid IDs on the table, and cannot be cast to bigint
> Migrate Ahoy user_id columns to use uuids from bigint - PSD-2384

- app/javascript/controllers/application.js
- app/javascript/controllers/dynamic_checkbox_states_controller.js
- app/views/notifications/create/index.html.erb
- app/views/notifications/create/record_a_corrective_action.html.erb
- app/views/notifications/create/record_a_corrective_action_details.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2123
* Prevent repeated database calls for task status
* Add “select all” checkbox for corrective action product selection
* Apply restrictions to mutually-exclusive geographic scope checkboxes
https://psd-pr-2862.london.cloudapps.digital/
https://psd-pr-2862-support.london.cloudapps.digital/
https://psd-pr-2862-report.london.cloudapps.digital/
> Improve corrective actions

- app/controllers/bulk_products_controller.rb
- app/controllers/concerns/corrective_actions_concern.rb
- app/controllers/investigations/corrective_actions_controller.rb
- app/controllers/notifications/create_controller.rb
- app/decorators/audit_activity/corrective_action/add_decorator.rb
- app/decorators/audit_activity/corrective_action/base_decorator.rb
- app/decorators/audit_activity/corrective_action/update_decorator.rb
- app/decorators/corrective_action_decorator.rb
- app/forms/corrective_action_form.rb
- app/helpers/application_form_builder.rb
- app/views/investigations/corrective_actions/_form.html.erb
- app/views/notifications/create/record_a_corrective_action_details.html.erb
- db/migrate/20240129110857_change_corrective_actions_legislation_to_array.rb
- db/schema.rb
- prism/app/views/prism/tasks/define/add_details_about_products_in_use_and_safety.html.erb
- spec/decorators/audit_activity/corrective_action/add_decorator_spec.rb
- spec/decorators/audit_activity/corrective_action/update_decorator_spec.rb
- spec/factories/corrective_actions.rb
- spec/features/edit_corrective_action_spec.rb
- spec/features/notification_task_list_spec.rb
- spec/services/add_corrective_action_to_notification_spec.rb
- spec/support/features/page_expectations.rb
- spec/support/shared_contexts/add_corrective_action_context.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2123
Updates the existing corrective actions add/edit flow, bulk products uploads and the notification task list to allow choosing multiple legislations.
N/A
https://psd-pr-2863.london.cloudapps.digital/
https://psd-pr-2863-support.london.cloudapps.digital/
https://psd-pr-2863-report.london.cloudapps.digital/
> Allow multiple legislation choices for corrective actions

- app/helpers/application_form_builder.rb
- app/helpers/investigations/user_filters_helper.rb
- app/views/investigations/_case_hazard_type_filter.html.erb
- app/views/investigations/_why_reporting_form_unsafe_details.html.erb
- app/views/investigations/accident_or_incidents/_form.html.erb
- app/views/investigations/ownership/_owner_form.html.erb
- app/views/investigations/ownership/_owner_selection.html.erb
- app/views/investigations/test_results/_form.html.erb
- app/views/products/_filters.html.erb
- app/views/products/_form.html.erb
Removes autocomplete from most `<select>` elements since they function just as well when a standard element and don’t have enough values to justify a custom autocomplete element.
Autocomplete elements are now only used for `<select>` elements that allow multiple choices since the default user experience for these is unintuitive.
N/A
https://psd-pr-2865.london.cloudapps.digital/
https://psd-pr-2865-support.london.cloudapps.digital/
https://psd-pr-2865-report.london.cloudapps.digital/
> Remove autocomplete fields

- app/controllers/notifications/create_controller.rb
- app/forms/change_notification_product_safety_compliance_details_form.rb
- app/helpers/notifications/create_helper.rb
- app/services/change_notification_overseas_regulator.rb
- app/views/notifications/create/add_product_safety_and_compliance_details.html.erb
- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2355
Adds a new question “Was the safety issue reported by an overseas regulator?” to the “Add product safety and compliance details” task.
https://psd-pr-2868.london.cloudapps.digital/
https://psd-pr-2868-support.london.cloudapps.digital/
https://psd-pr-2868-report.london.cloudapps.digital/
> Notification task lisk: add overseas regulator question

- app/services/update_test_result.rb
- app/views/notifications/create/add_test_reports.html.erb
- app/views/notifications/create/add_test_reports_details.html.erb
Fixes test reports for the notification task list to ignore funding status when editing and prevent data being overwritten.
N/A
https://psd-pr-2875.london.cloudapps.digital/
https://psd-pr-2875-support.london.cloudapps.digital/
https://psd-pr-2875-report.london.cloudapps.digital/
> Fix test reports

- report_portal/app/views/report_portal/dashboard/index.html.erb
https://regulatorydelivery.atlassian.net/browse/PSD-2400
Fixes a typo in the reporting portal summary page
> Fx typo in reporting summary view - PSD-2400

- app/controllers/notifications/create_controller.rb
- app/controllers/notifications_controller.rb
- app/helpers/notifications_helper.rb
- app/models/investigation.rb
- app/services/create_notification.rb
- app/views/investigations/risk_validations/edit.html.erb
- app/views/notifications/access.html.erb
- app/views/notifications/create/add_product_identification_details.html.erb
- app/views/notifications/create/confirmation.html.erb
- app/views/notifications/show.html.erb
- config/routes.rb
- spec/features/validate_risk_level_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2376
Add the notification summary page for submitted notifications, allowing owner and team access changes and linking to existing pages to add/change other information.
Also changes the existing notification creation flow to create submitted notifications since that flow has no concept of drafts.
https://psd-pr-2877.london.cloudapps.digital/
https://psd-pr-2877-support.london.cloudapps.digital/
https://psd-pr-2877-report.london.cloudapps.digital/
> Notification task list: submitted summary

- app/views/notifications/show.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2382
Adds an “add corrective action” button to the notification summary page.
https://psd-pr-2878.london.cloudapps.digital/
https://psd-pr-2878-support.london.cloudapps.digital/
https://psd-pr-2878-report.london.cloudapps.digital/
> Notificaion task list: add corrective action button

- .github/workflows/refresh-research.yml
- .github/workflows/review-apps.yml
- app/controllers/investigations_controller.rb
- app/controllers/notifications_controller.rb
- app/helpers/investigations_helper.rb
- app/helpers/search_params.rb
- app/models/concerns/investigation_searchkick.rb
- app/models/investigation/allegation.rb
- app/models/investigation/enquiry.rb
- app/models/investigation/project.rb
- app/policies/investigation_policy.rb
- app/views/investigations/_create_a_notification_link.html.erb
- app/views/investigations/heading/_all_cases.html.erb
- app/views/investigations/heading/_assigned_cases.html.erb
- app/views/investigations/heading/_team_cases.html.erb
- app/views/investigations/heading/_your_cases.html.erb
- app/views/notifications/delete.html.erb
- app/views/notifications/your_notifications.html.erb
- config/routes.rb
- doc/using-cloud-foundry.md
- lib/tasks/notifications.rake
- spec/features/export_notifications_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2354
* Completely separates the new notifications pages from the old cases pages and redirects between the two based on role
* Prevents draft notifications from being indexed by Opensearch
* Excludes draft notifications from being displayed except on the “your notifications” page in a separate section
* Allows draft notifications to be deleted
* Adds a one-time rake task to update all current notifications to a submitted state
https://psd-pr-2879.london.cloudapps.digital/
https://psd-pr-2879-support.london.cloudapps.digital/
https://psd-pr-2879-report.london.cloudapps.digital/
> Update notifications pages

- app/views/investigations/tabs/_products.html.erb
- app/views/notifications/create/check_notification_details_and_submit.html.erb
- app/views/notifications/show.html.erb
- app/views/products/show.html.erb
- config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1909
* Change the notification summary field in the task list to have a maxmium size wit h scroll bars for very long summaries
* Add “online seller” and “online marketplace” as business types when displayed in the task list
* Show the full product name with brand in the existing case and products pages
https://psd-pr-2880.london.cloudapps.digital/
https://psd-pr-2880-support.london.cloudapps.digital/
https://psd-pr-2880-report.london.cloudapps.digital/
> Notification and product bug fixes

- Gemfile
- Gemfile.lock
- app/analyzers/anti_virus_analyzer.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1399
Removes the `rest-client` gem and switches usage to `Net::HTTP`.
N/A
https://psd-pr-2895.london.cloudapps.digital/
https://psd-pr-2895-support.london.cloudapps.digital/
https://psd-pr-2895-report.london.cloudapps.digital/
> Remove rest-client gem

- app/analyzers/anti_virus_analyzer.rb
Configures `Net::HTTP` to use HTTPS for the antivirus endpoint when on a non-development/test environment.
N/A
https://psd-pr-2900.london.cloudapps.digital/
https://psd-pr-2900-support.london.cloudapps.digital/
https://psd-pr-2900-report.london.cloudapps.digital/
> Use HTTPS for antivirus endpoint

- db/migrate/20240207103811_remove_enums.rb
- db/schema.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2199
Removes PostgreSQL native enums and replace them with ActiveRecord enums (already existing) backed by string columns to make them more flexible.
N/A
https://psd-pr-2899.london.cloudapps.digital/
https://psd-pr-2899-support.london.cloudapps.digital/
https://psd-pr-2899-report.london.cloudapps.digital/
> Remove native enums

- app/controllers/notifications/create_controller.rb
- app/forms/add_business_details_form.rb
- app/forms/add_contact_form.rb
- app/forms/add_location_form.rb
- app/models/investigation/notification.rb
- app/services/change_business_names.rb
- app/views/notifications/create/add_business_details.html.erb
- app/views/notifications/create/add_contact.html.erb
- app/views/notifications/create/add_location.html.erb
- app/views/notifications/create/add_notification_details.html.erb
- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
- spec/forms/add_business_details_form_spec.rb
- spec/forms/add_location_form_spec.rb
- spec/services/change_business_names_spec.rb
Adds ability to create businesses with a location and contact from the notification task list
https://psd-pr-2902.london.cloudapps.digital/
https://psd-pr-2902-support.london.cloudapps.digital/
https://psd-pr-2902-report.london.cloudapps.digital/
> allow businesses to be added from the notification task list

- app/decorators/investigation_decorator.rb
- app/views/investigations/summary/edit.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2405
Fixes the notification summary edit page to show the summary without HTML tags.
N/A
https://psd-pr-2905.london.cloudapps.digital/
https://psd-pr-2905-support.london.cloudapps.digital/
https://psd-pr-2905-report.london.cloudapps.digital/
> Remove HTML formatting from notification summary edit page

- config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2406
Adds an error message which is displayed if a future date is entered for the test result certificate issue date.
https://psd-pr-2907.london.cloudapps.digital/
https://psd-pr-2907-support.london.cloudapps.digital/
https://psd-pr-2907-report.london.cloudapps.digital/
> Add error message for test result certificate issue date in future

- app/controllers/notifications/create_controller.rb
- app/decorators/investigation_business_decorator.rb
- app/views/notifications/create/check_notification_details_and_submit.html.erb
- app/views/notifications/show.html.erb
- config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2409
Prevents the “save as draft” button on the notification check page from submitting the notification - it will now save changes and return to the task list.
Also fixes how business relationships appear on the check page.
N/A
https://psd-pr-2908.london.cloudapps.digital/
https://psd-pr-2908-support.london.cloudapps.digital/
https://psd-pr-2908-report.london.cloudapps.digital/
> Don’t submit notification on “save as draft”

- app/controllers/investigations_controller.rb
- app/controllers/notifications_controller.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2411
Adds redirects so users of the notification task list always see the new notification summary page and vice versa.
Also fixes existing redirects between the your, team and assigned cases and notifications pages to use the same redirection criteria.
N/A
https://psd-pr-2909.london.cloudapps.digital/
https://psd-pr-2909-support.london.cloudapps.digital/
https://psd-pr-2909-report.london.cloudapps.digital/
> Redirect between case and notification summary pages

- .github/workflows/review-apps-delete.yml
Fixes the GitHub Action that deletes review apps after the PR is merged or closed to use the correct test of an app’s existence when attempting to delete it.
N/A
https://psd-pr-2914.london.cloudapps.digital/
https://psd-pr-2914-support.london.cloudapps.digital/
https://psd-pr-2914-report.london.cloudapps.digital/
> Fix review app deletion

- app/controllers/notifications/create_controller.rb
- app/views/notifications/create/search_for_or_add_a_product.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2410
Allows products to be removed when using the notification task list until the next task has been completed.
N/A
https://psd-pr-2915.london.cloudapps.digital/
https://psd-pr-2915-support.london.cloudapps.digital/
https://psd-pr-2915-report.london.cloudapps.digital/
> Expand product removal timeframe for notification task list

- lib/tasks/index.rake
- lib/tasks/notifications.rake
* `index.rake` has been replaced by `notifications.rake`
* All notifications have been marked as submitted
N/A
https://psd-pr-2918.london.cloudapps.digital/
https://psd-pr-2918-support.london.cloudapps.digital/
https://psd-pr-2918-report.london.cloudapps.digital/
> Remove unnecessary rake tasks

- app/helpers/notifications/create_helper.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2419
Change the hazard type select box to record hazard types as user-readable strings.
N/A
https://psd-pr-2920.london.cloudapps.digital/
https://psd-pr-2920-support.london.cloudapps.digital/
https://psd-pr-2920-report.london.cloudapps.digital/
> Fix hazard type on notification task list

- app/views/notifications/create/add_risk_assessments_prism_or_legacy.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2420
Limits the ability to add existing PRISM risk assessments via the notification task list to PRISM users.
https://psd-pr-2921.london.cloudapps.digital/
https://psd-pr-2921-support.london.cloudapps.digital/
https://psd-pr-2921-report.london.cloudapps.digital/
> Limit PRISM risk assessments to PRISM users

- app/decorators/product_decorator.rb
- app/views/notifications/create/search_for_or_add_a_product.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2416
Adds more product details to the notification task list page when selecting products.
https://psd-pr-2922.london.cloudapps.digital/
https://psd-pr-2922-support.london.cloudapps.digital/
https://psd-pr-2922-report.london.cloudapps.digital/
> Show more product details for notification task list

- app/controllers/notifications/create_controller.rb
- app/helpers/notifications/create_helper.rb
- app/views/notifications/create/check_notification_details_and_submit.html.erb
- config/locales/en.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2417
Adds the ability for a user to change whether a corrective action has been taken in the notification task list from “no” to “yes”.
https://psd-pr-2924.london.cloudapps.digital/
https://psd-pr-2924-support.london.cloudapps.digital/
https://psd-pr-2924-report.london.cloudapps.digital/
> Allow user to change whether a corrective action has been taken

- app/controllers/api/v1/notifications_controller.rb
- app/views/api/v1/notifications/index.json.jbuilder
- app/views/api/v1/products/index.json.jbuilder
- config/routes.rb
- spec/requests/api/v1/notifications_controller_spec.rb
- spec/requests/api/v1/products_controller_spec.rb
- swagger/v1/swagger.yaml
- Adds notification search API, using new opensearch helper
- Add new example responses for product, notification index endpoints
- Fix index array view, always have a named array instead of root json array
> Notification search & example responses - PSD-2425

- app/controllers/api/v1/products_controller.rb
- app/helpers/products_helper.rb
- app/helpers/search_params.rb
- config/routes.rb
- spec/requests/api/v1/products_controller_spec.rb
- swagger/v1/swagger.yaml
- New endpoint /api/products/named_parameter_search
- Search does AND matching for products, no fuzzy matching except for name
- Updated swagger docs
> Named parameter search for product API - PSD-2449

- app/controllers/notifications/create_controller.rb
- app/helpers/notifications/create_helper.rb
- app/models/investigation/notification.rb
- app/services/change_business_names.rb
- app/services/remove_business_from_notification.rb
- app/services/task_list_service.rb
- app/views/notifications/create/add_business_contact.html.erb
- app/views/notifications/create/add_business_location.html.erb
- app/views/notifications/create/index.html.erb
- app/views/notifications/create/remove_business.html.erb
- app/views/notifications/create/search_for_or_add_a_business.html.erb
- app/views/notifications/create/search_for_or_add_a_product.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/notification_task_list_spec.rb
- spec/services/task_list_service_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1999
Adds a business search option for the notification task list to add existing busiesses to a notification. Also allows a new business to be added and cleans up the presentation of this option.
https://psd-pr-2931.london.cloudapps.digital/
https://psd-pr-2931-support.london.cloudapps.digital/
https://psd-pr-2931-report.london.cloudapps.digital/
> Add business search for notification task list

- app/controllers/notifications/create_controller.rb
- app/forms/add_business_details_duplicate_form.rb
- app/views/notifications/create/add_business_details.html.erb
- app/views/notifications/create/add_business_details_duplicate.html.erb
- config/locales/en.yml
- config/routes.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2002
Adds a page to allow users to resolve potential duplicates when creating a new business.
https://psd-pr-2934.london.cloudapps.digital/
https://psd-pr-2934-support.london.cloudapps.digital/
https://psd-pr-2934-report.london.cloudapps.digital/
> Notification task list: resolve business duplicates

- app/controllers/notifications/create_controller.rb
- app/forms/add_business_roles_form.rb
- app/models/investigation/notification.rb
- app/services/change_business_roles.rb
- app/views/notifications/create/add_business_roles.html.erb
- config/locales/en.yml
- db/migrate/20240221161301_remove_uniqueness_constraint_for_investigation_businesses.rb
- db/schema.rb
- spec/features/notification_task_list_spec.rb
- spec/forms/add_business_roles_form_spec.rb
- spec/services/change_business_roles_spec.rb
Add business roles for a notification
https://psd-pr-2937.london.cloudapps.digital/
https://psd-pr-2937-support.london.cloudapps.digital/
https://psd-pr-2937-report.london.cloudapps.digital/
> add business roles page

- app/helpers/notifications/create_helper.rb
- app/views/notifications/create/add_product_safety_and_compliance_details.html.erb
- app/views/notifications/create/add_supporting_documents.html.erb
- app/views/notifications/create/add_supporting_images.html.erb
- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2438
Changes all instances of “product hazard” to “product harm” in the notification task list.
N/A
https://psd-pr-2939.london.cloudapps.digital/
https://psd-pr-2939-support.london.cloudapps.digital/
https://psd-pr-2939-report.london.cloudapps.digital/
> Change “product hazard” to “product harm”

- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2439
Change the heading to include a reference to non-compliant products.
N/A
https://psd-pr-2940.london.cloudapps.digital/
https://psd-pr-2940-support.london.cloudapps.digital/
https://psd-pr-2940-report.london.cloudapps.digital/
> Update corrective actions heading

- app/controllers/notifications/create_controller.rb
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2440
Changes the notifications task list to show tasks as “in progress” rather than “completed” when “save as draft” is used rather than “save and continue”.
N/A
https://psd-pr-2941.london.cloudapps.digital/
https://psd-pr-2941-support.london.cloudapps.digital/
https://psd-pr-2941-report.london.cloudapps.digital/
> Mark task as “in progress” when saving as draft

- app/controllers/notifications/create_controller.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2454
Correctly select "no" for notification reference when revisiting the task in the notification task list.
N/A
https://psd-pr-2942.london.cloudapps.digital/
https://psd-pr-2942-support.london.cloudapps.digital/
https://psd-pr-2942-report.london.cloudapps.digital/
> Correctly select "no" for notification reference when revisiting the task

- app/views/notifications/create/search_for_or_add_a_product.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2441
Adds the PSD reference to product search results in the notifications task list.
https://psd-pr-2943.london.cloudapps.digital/
https://psd-pr-2943-support.london.cloudapps.digital/
https://psd-pr-2943-report.london.cloudapps.digital/
> Add PSD reference to product search results

- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2448
Changes the risk level working in the notifications task list.
N/A
https://psd-pr-2944.london.cloudapps.digital/
https://psd-pr-2944-support.london.cloudapps.digital/
https://psd-pr-2944-report.london.cloudapps.digital/
> Change “determine” to “evaluate” for risk level

- app/controllers/notifications/create_controller.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2453
Fixes a bug when attempting to search products in the notifications task list to allow the search to complete.
N/A
https://psd-pr-2945.london.cloudapps.digital/
https://psd-pr-2945-support.london.cloudapps.digital/
https://psd-pr-2945-report.london.cloudapps.digital/
> Fix bug when attempting to search products in the notifications task list

- app/controllers/notifications/create_controller.rb
- app/views/notifications/create/search_for_or_add_a_business.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2452
Don’t display a “remove” link for any business that is currently associated with at least one corrective action or risk assessment for the same notification.
https://psd-pr-2950.london.cloudapps.digital/
https://psd-pr-2950-support.london.cloudapps.digital/
https://psd-pr-2950-report.london.cloudapps.digital/
> Disallow associated business removal for notification task list

- doc/dns.md
Changes the DNS docs to include allowing the `User-Agent` header.
N/A
https://psd-pr-2951.london.cloudapps.digital/
https://psd-pr-2951-support.london.cloudapps.digital/
https://psd-pr-2951-report.london.cloudapps.digital/
> Add User-Agent header to DNS docs

- app/controllers/notifications/create_controller.rb
- app/forms/add_business_details_form.rb
- app/forms/add_contact_form.rb
- app/models/investigation/notification.rb
- app/views/notifications/create/add_business_contact.html.erb
- app/views/notifications/create/add_business_details.html.erb
- app/views/notifications/create/add_business_location.html.erb
- app/views/notifications/create/add_business_roles.html.erb
- app/views/notifications/create/confirm_business_details.html.erb
- config/locales/en.yml
- spec/features/notification_task_list_spec.rb
Add page to confirm of change business details
https://psd-pr-2954.london.cloudapps.digital/
https://psd-pr-2954-support.london.cloudapps.digital/
https://psd-pr-2954-report.london.cloudapps.digital/
> add confirm business details page

- app/controllers/notifications/create_controller.rb
- app/views/notifications/create/add_business_roles.html.erb
- app/views/notifications/create/confirm_business_details.html.erb
- spec/features/notification_task_list_spec.rb
Redirects user to search_for_or_add_business page after adding a business
Fixes bug that prevented existing business from being added
displays full contact information
prevents empty contacts from being saved
https://psd-pr-2955.london.cloudapps.digital/
https://psd-pr-2955-support.london.cloudapps.digital/
https://psd-pr-2955-report.london.cloudapps.digital/
> Redirect to serach for a business page after adding business

- app/controllers/notifications/create_controller.rb
- app/forms/add_business_details_form.rb
- app/services/change_business_names.rb
- app/views/notifications/create/add_business_details.html.erb
- app/views/notifications/create/add_business_roles.html.erb
- app/views/notifications/create/confirm_business_details.html.erb
- app/views/notifications/create/search_for_or_add_a_business.html.erb
- Adds company number as a field for new business records
- Confirm business details when adding existing businesses
- Display roles businesses have for notification
> confirm business details for existing businesses

- report_portal/app/views/report_portal/best_teams/_notifications.html.erb
- report_portal/app/views/report_portal/best_teams/_products.html.erb
- report_portal/app/views/report_portal/best_teams/_users.html.erb
- report_portal/app/views/report_portal/best_teams/index.html.erb
- report_portal/app/views/report_portal/worst_teams/_notifications.html.erb
- report_portal/app/views/report_portal/worst_teams/_products.html.erb
- report_portal/app/views/report_portal/worst_teams/_users.html.erb
- report_portal/app/views/report_portal/worst_teams/index.html.erb
Changes copy from 'worst' -> 'least active', 'best' -> 'most active'
> Rename to most/least active teams - PSD-2442

- app/controllers/notifications_controller.rb
- app/models/investigation/notification.rb
- app/views/notifications/show.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2480
Displays any comments added to a notification on the new summary page.
https://psd-pr-2990.london.cloudapps.digital/
https://psd-pr-2990-support.london.cloudapps.digital/
https://psd-pr-2990-report.london.cloudapps.digital/
> Show notification comments on new summary page

- app/controllers/comments_controller.rb
- app/views/notifications/show.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2479
Adds the ability to add comments to a submitted notification via the new notification summary page.
https://psd-pr-2992.london.cloudapps.digital/
https://psd-pr-2992-support.london.cloudapps.digital/
https://psd-pr-2992-report.london.cloudapps.digital/
> Add comment via notification summary page

- app/views/notifications/create/search_for_or_add_a_product.html.erb
Removes link to product pages from "search for or add product" page on notification creation.
> PSD 2473 remove links on search for or add product page

- app/helpers/notifications/create_helper.rb
- app/views/notifications/create/check_notification_details_and_submit.html.erb
- app/views/notifications/show.html.erb
- config/database.yml
- spec/features/visit_risk_assessment_from_notification_task_list_page_spec.rb
This Branch addresses the Jira ticket PSD-2481: https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?selectedIssue=PSD-2481
Description
I have changed the text adjacent to Risk assessments in the Notification page to a hyperlink that when clicked would redirect the user straight to the show page of that risk assessment
Screen-shots or screen-capture of UI changes
> PSD-2481 - Test report and Risk assessment hyperlinks

- app/views/notifications/show.html.erb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2509
Fixes a condition where non-task-list notifications without a reported reason cause an exception.
N/A
https://psd-pr-3012.london.cloudapps.digital/
https://psd-pr-3012-support.london.cloudapps.digital/
https://psd-pr-3012-report.london.cloudapps.digital/
> Fix notification summary for non-task-list notifications

- config/locales/en.yml
- spec/features/validate_risk_level_spec.rb
When a risk is validated by IMT , the messaged shown will be "The notification risk level has been validated"
> [PSD-2536] - updated the message for risk level validation

- app/helpers/notifications/create_helper.rb
Picked up ticket PSD-2557 for `undefined method `address_line_1' for nil:NilClass (ActionView::Template::Error)` and found it had been worked on previously as part of PR 3010
Saw a small update to the code which could be done so added that in.
> fix/PR-2557 - Update to the previous fix

- app/decorators/test/result_decorator.rb
- spec/decorators/test/result_decorator_spec.rb
Fix to the `undefined method `metadata' for nil:NilClass (ActionView::Template::Error)` raised by sentry. 
Updated the tests too so we cover the `result_decorator.rb` file better as there were some missing tests.
> fix/PSD-2558 - Fix to the undefined method metadata raised by sentry

- app/controllers/notifications/edit_controller.rb
- app/views/notifications/edit/add_business_contact.html.erb
- app/views/notifications/edit/add_business_details.html.erb
- app/views/notifications/edit/add_business_details_duplicate.html.erb
- app/views/notifications/edit/add_business_location.html.erb
- app/views/notifications/edit/add_business_roles.html.erb
- app/views/notifications/edit/confirm_business_details.html.erb
- app/views/notifications/edit/remove_business.html.erb
- app/views/notifications/edit/search_for_or_add_a_business.html.erb
- app/views/notifications/show.html.erb
- config/locales/devise.en.yml
- config/routes.rb
- spec/features/add_and_remove_a_business_spec.rb
Description
Implemented new Controller and identical views that allow users to access the new Business view Journey that was only exclusive to the create notification Journey.
Screen-captures
Before
https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/assets/83423212/c9efb782-68d4-4600-890a-7387702971f3
After
https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/assets/83423212/5ca04712-5cde-44df-a945-61f627103a4e
> PSD-2542 - Add Business from the Update Notification

- app/services/add_corrective_action_to_notification.rb
- spec/services/add_corrective_action_to_notification_spec.rb
Description
Added change that adds the IMT team to a notification when the corrective action: modification programme is created for a notification.
made changes to the corrective action spec to account for this change
> PSD-2694: IMT automatically added to Modification programme corrective actions

- app/controllers/investigations/business_types_controller.rb
- spec/features/add_business_to_a_notification_spec.rb
PSD 1.0 user journey for adding an online marketplace to an existing notification caused an Interactor error
> fix/PSD-2720 - Interactor failure

- app/controllers/notifications/edit_controller.rb
- app/forms/product_form.rb
- app/views/products/_form.html.erb
- app/views/products/edit.html.erb
- app/views/products/new.html.erb
- config/database.yml
- spec/features/edit_a_product_spec.rb
- spec/features/product_versioning_spec.rb
- spec/features/update_product_details_spec.rb
Description
Refactored Products Form to use GOVUKDesignSystemFormBuilder instead of  ApplicationFormBuilder and made changes to the product related rspecs where necessary
> PSD-2569: Refactor Products Form

- app/views/investigations/record_emails/_form_fields.html.erb
Description
Added custom handling to correspondence email form that highlights every field in the fieldset in red with the error if an email attachment and email subject and body is not provided, and allows the user to go straight to the error when the message is clicked, you cannot assign an attribute name to a GOVUK fieldset so I had to come with a custom solution.
Before
After
> chore/PSD-2870:Update_to_Email_Correspondence_form

- app/controllers/bulk_products_controller.rb
- app/controllers/concerns/corrective_actions_concern.rb
- app/controllers/investigations/corrective_actions_controller.rb
- app/controllers/investigations/risk_assessments_controller.rb
- app/controllers/notifications/create_controller.rb
- app/forms/corrective_action_form.rb
- app/services/update_corrective_action.rb
- app/services/update_risk_assessment.rb
- app/views/investigations/corrective_actions/_form.html.erb
- app/views/notifications/create/record_a_corrective_action_details.html.erb
- spec/features/add_corrective_action_spec.rb
Description
Rearranged the corrective action form validations so that the appear the the right order on screen based on the fields the user is missing. Removed the manual implementation the OJ guys put for the date fields and used the GOVUK builder field for the date field and created handling for the date fields.
I prevented the corrective actions edit form and risk assessments form from creating a new activity log when nothing in the form was edited and the form was resubmitted, it would create a new activity log due to the 3 date parameters I was passing for the date fields
> chore/PSD-2869:PSD2.0_rearrange_Corrective_Action_messages

- app/controllers/bulk_products_controller.rb
- app/forms/add_business_to_notification_form.rb
- app/forms/bulk_products_add_business_details_form.rb
- app/views/bulk_products/add_business_details.html.erb
- app/views/businesses/_form.html.erb
- app/views/businesses/edit.html.erb
- app/views/businesses/locations/_address_form.html.erb
- app/views/businesses/locations/_form.html.erb
- app/views/businesses/locations/edit.html.erb
- app/views/businesses/locations/new.html.erb
- app/views/investigations/businesses/_form.html.erb
- app/views/investigations/businesses/new.html.erb
- spec/features/add_business_to_a_notification_spec.rb
- spec/features/bulk_upload_products_spec.rb
- spec/features/editing_business_details_spec.rb
Description
Changed forms to use GOVUKSystemForm builder, made sure parameters were handled correctly and the country error message redirected to the select box when clicked. The reason for this form being finnicky is due to the forms being nested multiple times and also due to there being multiple forms being rendered at one time as one form.
> refactor/PSD-2894:Update_to_businesses_form

- app/forms/email_correspondence_form.rb
- app/forms/phone_call_correspondence_form.rb
- app/helpers/error_summary_presenter.rb
- app/views/products/duplicate_checks/new.html.erb
- app/views/products/duplicate_checks/show.html.erb
- spec/forms/email_correspondence_form_spec.rb
- spec/helpers/error_summary_presenter_spec.rb
Description
Refactored product duplicate check form top use GOVUK Form Builder, made changes to Error Summary Presenter helper, it was not displaying all the errors a form attribute had separately but merging them together in a long string and showing the error on frontend, added extra test case to Error Summary presenter spec.
> Refactor/PSD-2988:Update_to_products_duplicate_checks_forms

- app/controllers/notifications/create_controller.rb
- app/forms/record_a_corrective_action_form.rb
- app/views/notifications/create/record_a_corrective_action.html.erb
Prevented form attributes from being assigned twice causing form to fail when the parameters were not present, the method set_date for the form does that already, added new form model to display errors
> chore/PSD-2936:Update_to_NTL_corrective_actions_form

- app/controllers/notifications/create_controller.rb
- app/forms/test_result_form.rb
- app/views/investigations/test_results/_form.html.erb
- app/views/notifications/create/add_test_reports_details.html.erb
- app/views/notifications/create/add_test_reports_funding_details.html.erb
- spec/features/add_test_results_spec.rb
Description
Made changers to manual implementation to forms to make sure errors redirect to the correct fields, added a caching function to ensure documents are persisted when entered but the form is invalid
> refactor/PSD-3021:Update_to_NTL_test _reports_form

- app/controllers/investigations/prism_risk_assessments_controller.rb
controller fix, added an extra condition that checks if this is the first time the user is accessing that specific view for a prism risk assessment, this will prevent the controller from raising an exception due to the user accessing the view without the needed parameters
> chore/PSD-3036:Update_to_prism_risk_assessments_form

- app/views/products/recalls/select-images.html.erb
Description
Disabled the ability for user to select GIF image types for the product Recall PDF, added hint message to explain why they cannot select their gif images.
> chore/PSD-3050-Update_to__product_recall_pdf_extract 

- app/views/products/recalls/select-images.html.erb
Only allowed JPG and PNG files to be submitted to product recall PDF, made changes to hint text to be the text Ali supplied me
> refactor/PSD-3158:Change_to_product_recall_image_selection 

- app/forms/change_notification_name_form.rb
- app/views/investigations/case_names/_form.html.erb
Changed limiter for notification name input to 100 as thats the amount of characters user is allowed to input there, added validation that ensures user does not go over the limit to prevent ActiveRecord::RecordInvalid error
> chore/PSD-2980:fix_to_notification_name_form

- app/controllers/investigations/ts_investigations_controller.rb
- spec/features/create_case_spec.rb
PSD-2841 product id is nil in new notification wizard steps.
When navigating to `/ts_investigation/case_name` resulted in product id being nil.  Added defensive code to avoid this happening user is redirected to the new notification view explaining how to create a notification for a product.
> fixed case name bug and updated spec`

- app/forms/product_form.rb
- app/views/products/_form.html.erb
Description
Made sure the uploaded images to a product form are persisted and any unsupported file type isn't and the error is thrown
> chore/PSD-2742:Update-to-product-form

- app/controllers/investigations/overseas_regulator_controller.rb
- app/controllers/notifications/create_controller.rb
- app/forms/change_notification_product_safety_compliance_details_form.rb
- app/forms/overseas_regulator_form.rb
- app/helpers/investigations_helper.rb
- app/models/audit_activity/investigation/change_overseas_regulator.rb
- app/models/notification_export.rb
- app/services/change_notification_overseas_regulator.rb
- app/services/create_notification.rb
- app/views/investigations/activities/investigation/_change_overseas_regulator.html.erb
- app/views/investigations/overseas_regulator/edit.html.erb
- app/views/notifications/create/add_product_safety_and_compliance_details.html.erb
- app/views/notifications/create/check_notification_details_and_submit.html.erb
- app/views/notifications/show.html.erb
- config/locales/en.yml
- spec/features/change_notification_overseas_regulator_spec.rb
- spec/models/audit_activity/investigation/change_notifying_country_spec.rb
- spec/models/audit_activity/investigation/change_overseas_regulator_spec.rb
- spec/services/change_notification_overseas_regulator_spec.rb
Changed all references to overseas_regulator country in the code now change notifying_country instead. 
Made changes to field names for forms in order to reflect these changes, made changes to form to now use GOVUKDesignSystemFormBuilder instead of applicationformbuilder.
Made changes to activity partial so that it displays UK based countries in human form not the country code, this bug has been in the code for a long time.
Made spec changes
> refactor/PSD-3321:Make_change_to_overseas_regulator_field_change_notifying_country_field

- app/controllers/notifications/create_controller.rb
- spec/features/search_for_or_add_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-3529
Fixed issue where retired products were being displayed in the product search results.
Incorrect results (showing two retired products):
Fix applied:
All products screen appears to already exclude retired products (checked view):
> added retired_at exclusion from search query ensuring only active products

- app/views/products/recalls/product-details.html.erb
- app/views/products/recalls/select-images.html.erb
- spec/features/product_recall_spec.rb
changes made to keep the wording of the button save to "Save and continue" , also minimised unnecessary calling of the methods
> [PSD-2092] - product recall module enhancements

- app/views/businesses/_table.html.erb
- app/views/businesses/_table_row.html.erb
- app/views/notifications/create/search_for_or_add_a_business.html.erb
- app/views/notifications/edit/search_for_or_add_a_business.html.erb
- spec/features/businesses_navigation_spec.rb
- spec/features/businesses_spec.rb
add legal name to the business search tables
> PSD-2717 - add legal name to the business search tables

- app/services/send_sms.rb
- spec/services/send_sms_spec.rb
Sentry reporting an error: InvalidPhoneError: Not a UK mobile number (Notifications::Client::BadRequestError)
Expanded regex to cater for double leading zeros (when UK code is valid) as well.
> Refactored regex to handle leading double zero scenario

- app/views/shared/_ga_head.html.erb
- config/initializers/content_security_policy.rb
Fixed shared partial that loads the GTM related scripts with a `javascript_tag` helper to ensure `nonce` is handled and resolve the CSP violations currently in Staging.
Resolved GA container script and source related issues.
> CSP file ensuring the app scripts & styles are handled

- app/decorators/investigation/enquiry_decorator.rb
- spec/decorators/investigation/enquiry_decorator_spec.rb
When viewing certain enquiries in the system, users encounter a 500 error if the `date_received` field is nil. This occurs because the code attempts to call `to_formatted_s` on a nil value.
Error:
```ruby
ActionView::Template::Error (undefined method `to_formatted_s' for nil:NilClass)
```
Modified the `source_details_summary_list` method in `EnquiryDecorator` to conditionally display the received date only when it exists. This is achieved by using the existing `should_display_date_received?` method as a guard clause.
- Added conditional check before displaying received date
- Added comprehensive test coverage for various date/type combinations
- Maintained existing behavior for cases with valid dates
Added test cases covering:
- When both date_received and received_type are present
- When …
> PSD-3957-500_error

- app/jobs/send_reminder_email_draft_notifications_job.rb
- app/mailers/notify_mailer.rb
- config/locales/en.yml
- config/sidekiq.yml
- spec/jobs/send_reminder_email_draft_notifications_job_spec.rb
a new job to run and check the elapsed days on drafts to send emails to the users to remind them to submit the Notification
> PSD-4023  send_email_reminders_to_submit_drafts based on the days elapsed

- prism/app/views/layouts/prism/application.html.erb
- spec/views/layouts/prism/application.html.erb_spec.rb
Adds Google Tag Manager (GTM) partials to the PRISM layout file to ensure all PRISM pages are properly tagged for analytics tracking.
- Added GTM head and body partials to `prism/app/views/layouts/prism/application.html.erb`
- Added comprehensive view specs to test GTM inclusion based on:
- Environment (production vs non-production)
- Cookie acceptance status
Some pages in the PRISM risk assessment section were not being tagged with GTM, causing gaps in analytics tracking. This change ensures consistent GTM implementation across all PRISM pages.
1. Sign in to staging environment
2. Visit PRISM risk assessment pages
3. Check browser dev tools (Network tab) for GTM requests
4. Verify GTM tags are present in page source
5. Test with analytics cookies both accepted and rejected
> fix/PSD-3971-GTM_bug: Add GTM partials to PRISM layout

- app/helpers/google_tag_manager_helper.rb
- app/views/shared/_ga_body.html.erb
- app/views/shared/_ga_head.html.erb
- prism/app/controllers/prism/application_controller.rb
- spec/system/prism/google_tag_manager_spec.rb
PRISM risk assessment pages were not being tagged with Google Tag Manager (GTM), leading to inconsistent analytics tracking across the application. This was particularly noticeable when users were editing risk assessments.
- Added GTM partials to the PRISM layout file with proper conditional rendering:
- Only loads in production environment
- Only loads when analytics cookies are accepted
- Extended `CookiesConcern` to the PRISM layout to handle cookie checks
- Included `GoogleTagManagerHelper` in PRISM application controller
- Ensured consistent loading of GTM container (`GTM-K2S954RK`) across all PRISM pages
- Implemented DRY approach with a helper method to manage GTM container configuration
Added comprehensive system tests that verify:
- GTM container is included when:
- In production …
> fix/PSD-3971-GTM_bug_2 - Add GTM containers to PRISM layout

- lib/tasks/update_submitted_at_investigations.rake
- spec/lib/update_submitted_at_investigations_spec.rb
Rake task to update the Submitted_at with created_at date for all notifications , and the epic track status change will cater for all new Notifications created.
To run the task : rails investigations:update_submitted_date
> PSD-4457 - data change , rake task to update notifications

- app/controllers/businesses/locations_controller.rb
- spec/controllers/businesses/locations_controller_spec.rb
This PR fixes the validation handling when creating a new location for a business. Previously, when required fields (name and country) were missing, the application would raise an exception instead of displaying validation errors to the user.
- Changed `create!` to `build` in locations controller to handle validation errors gracefully
- Added proper HTTP status code (422 Unprocessable Entity) for validation errors
- Added comprehensive controller specs to ensure proper validation handling
Added controller specs that verify:
- Valid locations can be created successfully
- Invalid locations show proper validation errors
- Correct HTTP status codes are returned
- User is redirected appropriately after successful creation
- Flash messages are set correctly
- Current user is properly assigned …
> PSD-3709: Fix location validation handling and error display

- app/controllers/notifications/create_controller.rb
- app/controllers/notifications_controller.rb
- app/policies/investigation_policy.rb
- spec/controllers/notifications/create_controller_spec.rb
- spec/controllers/notifications_controller_spec.rb
- spec/policies/investigation_policy_can_access_draft_spec.rb
- spec/policies/investigation_policy_draft_access_spec.rb
Prevents unauthorized access to draft notifications via direct URL
- Adds policy check to restrict draft notification access to creators and owners only
- Implements proper redirects and error handling for unauthorized access attempts
- Improves code readability with clean method extraction and better comments
- Adds comprehensive test coverage for all access scenarios
> PSD-4705: prevent drafts from being accessed via URL

- config/application.rb
- spec/features/two_factor_authentication_flipper_spec.rb
- spec/support/flipper.rb
- Deployment to staging failed because the implementation used `alias_method` on a method that didn't exist yet
- This caused the application to crash during initialization
- Fixed method overriding approach by using direct method definition instead of alias_method
- Added test to verify the safer approach works correctly
This PR ensures the application can deploy successfully while maintaining the same 2FA Flipper functionality.
> Fix 2FA Flipper for CloudFoundry staging space

- config/redacted_export.yml
with respect to DBT migration we are supposed to use BUCKET_ACCESS_KEY_ID and BUCKET_SECRET_ACCESS_KEY instead of the existing AWS prefix variables .
> PSD-5701_update_code_to_use_new_varaibles_for_AWS
