OfficeForProductSafetyAndStandards/product-safety-database

psd-web/.env.development.example, psd-web/.env.test.example, psd-web/.gitignore, psd-web/Gemfile, psd-web/Gemfile.lock, psd-web/README.md, psd-web/config/database.yml, psd-web/config/elasticsearch.yml, psd-web/config/redis_queue.yml, psd-web/config/redis_session.yml
More flexible configuration for development, with possibility to switch between docker or standalone services.
Additionally, adds `pry` gem for easier debugging.
=> Better development env

README.md, psd-web/app/models/business.rb, psd-web/app/models/concerns/indexable.rb, psd-web/app/models/concerns/investigation_elasticsearch.rb, psd-web/app/models/investigation/allegation.rb, psd-web/app/models/investigation/enquiry.rb, psd-web/app/models/investigation/project.rb, psd-web/app/models/product.rb, psd-web/config/database.yml, psd-web/db/seeds.rb, psd-web/deploy-review.sh, psd-web/manifest.review.yml
Introduces review apps. 
Changes:
* namespaced elasticsearch index
* db name is being lookup by label
* by default, database is shared, but it is possible to override by providing `DB_NAME`
=> Review applications for easier testing

psd-web/test/system/create_allegation_test.rb
=> Merge staging back into master

psd-web/app/models/business.rb, psd-web/app/models/concerns/indexable.rb, psd-web/app/models/concerns/investigation_elasticsearch.rb, psd-web/app/models/concerns/searchable.rb, psd-web/app/models/investigation/allegation.rb, psd-web/app/models/investigation/enquiry.rb, psd-web/app/models/investigation/project.rb, psd-web/app/models/product.rb
=> Explicitly set index name

psd-web/test/test_helper.rb
Only run tests with coverage on CI
=> only run tests on CI

.gitignore, psd-web/config/important_team_names.yml, psd-web/spec/models/team_spec.rb, psd-web/test/system/investigation_default_opss_team_assignee_test.rb
Ticket: https://trello.com/c/6TOv2SJI
=> Change default OPSS team

psd-web/manifest.prod.yml
Add email whitelist env to production manifest
=> Email whitelist env to manifest

psd-web/app/clients/keycloak_client.rb, psd-web/config/application.rb, psd-web/spec/models/user_spec.rb
I forgot why I originally put the Keycloak config here... see https://travis-ci.org/UKGovernmentBEIS/beis-opss-psd/jobs/611923291
=> Fix Keycloak config on application boot - ENV vars not available on PaaS during build stage

psd-web/test/system/keycloak_test.rb
Fix to system tests to reflect copy change on https://github.com/UKGovernmentBEIS/keycloak-theme-govuk/commit/cf3c56ec3ee275ffbae5027a2e537b736551cc50
=> Update copy of sign in page from Keycloak theme

psd-web/config/database.yml
=> Fix the default values for DATABASE_URL

psd-web/db/migrate/20191119151907_add_active_flag_to_users.rb
This addresses an error which has just started happening during the deployment stage to the staging environment: https://sentry.io/organizations/beis/issues/1363496230
This change should be functionally equivalent.
=> Fix database migration rejected by strong_migrations

.github/workflows/system_tests.yml, .github/workflows/tests.yml
Goal is to get all build around 5-6 minutes
=> Improve CI speed

.github/workflows/tests.yml, psd-web/Gemfile, psd-web/Gemfile.lock, psd-web/app/models/user.rb, psd-web/spec/decorators/investigation_decorator_spec.rb, psd-web/spec/factories/investigations.rb, psd-web/spec/features/assign_investigation_spec.rb, psd-web/spec/models/user_spec.rb, psd-web/spec/rails_helper.rb, psd-web/spec/support/database_cleaner.rb
This fixes two intermittently failing RSpec tests.
They previously failed intermittently because the database was not clean and sometimes the wrong object was unwittingly being referenced due to data conflicts.
In fact, neither of these tests should have passed if run properly in isolation, so previous passes were false positives.
I've added the [Database Cleaner gem](https://github.com/DatabaseCleaner/database_cleaner) to ensure RSpec tests are cleaned up properly after each test. Both tests failed reliably after adding this.
I also changed the CI environment setup so the unrelated test data seeds are no longer loaded; this data is unrelated to the automated tests and is intended for manual testing/demo purposes.
Because this was causing failures, I also refactored the …
=> Fix failing RSpec tests

.github/workflows/review-apps.yml, psd-web/deploy-review.sh, psd-web/manifest.review.yml
This fixes an issue when trying to compile from source.
Also upgrades to using the 7.0.0 beta
=> Install CloudFoundry command line from binary

psd-web/app/views/homepage/non_opss.html.slim
https://trello.com/c/fW4NMyXK/237-05-remove-intermittent-issues-banner-from-ts-home-page
=> remove the performance issue banner

psd-web/app/views/investigations/index.html.slim, psd-web/test/controllers/investigations_controller_test.rb
Update the text of the sort order options on the caselist page at the request of Amy.
=> Update sort column names

README.md, psd-web/app/views/components/_psd_header.html.slim, psd-web/app/views/layouts/application.html.slim
Some minor fixes to PSD:
* Improve our readme by giving it a better title and contact details for OPSS
* Remove title case in a few places
* Put error summary on case list page correctly inside the main element
Error summary before:
Error summary after:
=> Misc fixes

.github/workflows/code-style.yml
=> install rubocop-performance to slimt lint

psd-web/test/system/investigation_highlight_test.rb
=> fix flaky test

psd-web/app/controllers/searches_controller.rb, psd-web/app/helpers/investigations_helper.rb, psd-web/app/views/investigations/_filters.html.slim, psd-web/app/views/investigations/index.html.slim, psd-web/app/views/searches/show.html.slim, psd-web/spec/features/investigations_spec.rb
not very happy with how this code looks. But not really possible to do otherwise as the refactoring the search/code/form would take days.
So this is really just another hack on top of a tone of hacks.
=> fix search

psd-web/deploy.sh
=> HOTFIX: Fix deploy script

psd-web/manifest.yml
=> HOTFIX: Fix antivirus environment variables not bound to PSD apps

.github/workflows/review-apps-delete.yml
Fixes the repo URL in the previous PR https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/221
=> Fix repo URL

.github/workflows/review-apps-delete.yml
=> Fix app name

.github/workflows/review-apps-delete.yml
=> Clean up multi-process app

.github/workflows/review-apps-delete.yml
Now that we have multi-process apps and all PRs are merged/updated, we no longer need to clean up these old separate apps.
=> Remove redundant app names

psd-web/spec/features/investigations_spec.rb
This fixes a test which could intermitently fail.
The cause of the failures is down to using Faker to generate the descriptions of the test investigations, and then search query. On ocassion, by chance the search query could match more than one result (in part due to the use of the OR operator in the search query), which caused the test to fail.
This fix makes that scenario a lot less likely by explicitly setting descriptions on each of the investigations, and explicitly setting a search query which should only ever match one of those.
=> Bugfix: make search tests more reliable

README.md
Adds CodeClimate maintainability score badge.
=> Add CodeClimate Maintainability badge

.codeclimate.yml
This folder contains migrations, the schema, and seed data. The files are often necessarily verbose, and there is little value in refactoring old migrations.
=> Ignore db folder for codeclimate analysis

psd-web/test/models/product_test.rb, psd-web/test/models/rapex_import_test.rb, psd-web/test/models/source_test.rb
Tidying up... we’re switching to rspec so these stub files and folders aren't needed.
=> Remove empty test files

psd-web/app/decorators/investigation_decorator.rb, psd-web/app/decorators/team_decorator.rb, psd-web/app/decorators/user_decorator.rb, psd-web/app/models/team.rb, psd-web/app/models/user.rb, psd-web/app/views/investigations/_case_card.html.slim, psd-web/spec/decorators/investigation_decorator_spec.rb, psd-web/spec/decorators/team_decorator.rb, psd-web/spec/decorators/team_decorator_spec.rb, psd-web/spec/decorators/user_decorator_spec.rb, psd-web/spec/features/businesses_spec.rb, psd-web/test/models/user_test.rb
=> tidy up messy code

doc/decisions/0000-template.md
This adds a folder and a template for "architecture decision records", which can be used to document any significant decisions about how the application is built.
=> Architecture decision records template

.github/workflows/review-apps.yml, psd-web/.gitignore, psd-web/app/models/organisation.rb, psd-web/app/models/team.rb, psd-web/app/models/user.rb, psd-web/db/migrate/20200225103836_enable_pgcrypto.rb, psd-web/db/migrate/20200225103936_generate_uuid_for_organizations_teams_and_users.rb, psd-web/db/migrate/20200225163932_remove_path_from_team_and_organisation.rb, psd-web/db/schema.rb, psd-web/db/seeds.rb, psd-web/spec/factories/organisations.rb, psd-web/spec/factories/teams.rb, psd-web/spec/factories/user_roles.rb, psd-web/spec/factories/users.rb, psd-web/spec/models/team_spec.rb, psd-web/spec/shared_contexts/omniauth_response.rb, psd-web/test/fixtures/organisations.yml, psd-web/test/fixtures/teams.yml
Generate organizations, teams and users in seeds. Also generate uuid's in database.
=> Add users, teams, organisations to seeds and fix id generation

psd-web/deploy-review.sh, psd-web/deploy.sh
Attempts to fix the timeout issue affection production deployments. The `timeout` property on the manifest appears to be ignored on rolling deployments.
=> Set timeout on cf push command

psd-web/spec/features/creating_an_account_from_an_invitation_spec.rb, psd-web/spec/features/sign_in_spec.rb, psd-web/spec/forms/sign_in_form_spec.rb, psd-web/spec/jobs/send_user_invitation_job_spec.rb, psd-web/spec/models/user_spec.rb, psd-web/spec/requests/user_completes_registration_spec.rb, psd-web/spec/validators/common_password_validator_spec.rb, psd-web/spec/validators/phone_validator_spec.rb
This applies rubocop-rspec to the new tests/changes introduced on the Keycloak feature branch, as per https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/321
=> Fix keycloak branch cops

infrastructure/env/get-env-from-vcap.sh, psd-web/app/models/organisation.rb, psd-web/app/models/team.rb, psd-web/config/database.yml, psd-web/manifest.yml
Brings back loading keycloak db removed by mysterious git operations.
=> Fix db loading

.codeclimate.yml, psd-web/app/jobs/sync_keycloak_passwords_job.rb, psd-web/app/models/keycloak_connector.rb, psd-web/config/initializers/sidekiq.rb
To be verified on keycloak password worker.
=> Synch password worker

README.md, psd-web/db/schema.rb, psd-web/deploy-review.sh
Document pgcrypto and add it to review apps
=> pgcrypto in our databases

psd-web/app/controllers/users/passwords_controller.rb, psd-web/app/jobs/send_user_invitation_job.rb, psd-web/spec/jobs/send_user_invitation_job_spec.rb, psd-web/spec/requests/user_requests_password_reset_spec.rb
This is a possible refactor of the controller code, for discussion.
=> Refactor: move conditionals to the existing job class

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
The contributing guidelines document formalises the team's agreed approach to pull requests, and some agreed code conventions. It is intended to be a living document which can be iterated.
I've also updated the checklist template to make it more relevant and we should ensure this is completed or redacted for future changes.
=> Add contribution guidelines

README.md
=> Lowercase our email address

docker-compose.yml, docker/env.keycloak, psd-web/app/jobs/sync_keycloak_db_job.rb, psd-web/app/jobs/sync_keycloak_passwords_job.rb, psd-web/app/models/keycloak_connector.rb, psd-web/config/initializers/sidekiq.rb, psd-web/db/migrate/20200309120706_add_keycloak_import_fields_to_users.rb, psd-web/db/schema.rb
https://trello.com/c/WNCc6QD0/392-import-mobile-numbers-and-other-stuff-from-keycloak
Adds several keycloak fields to user table. Most important is mobile number.
=> Copy mobile phone and other data from keycloak

psd-web/db/migrate/20200309104244_two_factor_authentication_add_to_users.rb
Moves rest of the fields from `keycloak-replacement` to master.
=> Move transaction from devise branch

psd-web/db/migrate/20200320144542_add_mobile_number_verified_to_users.rb, psd-web/db/schema.rb
This will be used by a later branch which adds 2-factor-authentication.
=> Add flag indicating whether mobile number has been verified or not

doc/getting-set-up.md, psd-web/.env.development.example, psd-web/db/seeds.rb
added an environment variable to facilitate 2 factor auth testing in development.
=> Add development environment mobile number

infrastructure/env/get-env-from-vcap.sh, psd-web/config/database.yml
=> Fix database connection in PaaS

psd-web/db/migrate/20200319121332_add_lockable_to_devise.rb
Move remaining migrations from `keycloak-replacement`
=> Move migrations from devise

psd-web/deploy-devise.sh
Script to manually deploy `keycloak-replacement` to staging and production.
=> Devise deploy script

CHANGELOG.md, psd-web/Gemfile.lock, psd-web/app/controllers/investigations/ts_investigations_controller.rb, psd-web/app/decorators/investigation_decorator.rb, psd-web/app/helpers/investigations/display_text_helper.rb, psd-web/app/models/audit_activity/investigation/add_allegation.rb, psd-web/app/models/investigation.rb, psd-web/app/views/investigations/_current_status.html.slim, psd-web/app/views/investigations/ts_investigations/coronavirus.html.erb, psd-web/config/locales/en.yml, psd-web/spec/decorators/investigation_decorator_spec.rb, psd-web/spec/factories/investigations.rb, psd-web/spec/factories/users.rb, psd-web/spec/features/report_product_spec.rb, psd-web/spec/models/audit_activity/investigation/add_allegation_spec.rb, psd-web/spec/support/capybara.rb, psd-web/spec/support/investigation.rb
https://trello.com/c/b3K7oCvN/466-add-page-asking-if-case-is-related-to-coronavirus-for-trading-standards
Implements the question to ask MSA users if the case is related to the coronavirus.
I added an extra scenario to the existing feature spec since the existing one only tested the happy path and with every field completed. The new scenario tests a minimal input data set with some of the validations around those. Each scenario has a different value for the coronavirus question. Ideally there would be a few more scenarios with different input combinations but that is beyond the scope of this change. I also fixed the user having the wrong role in this feature spec.
Needless to say, the wizard controller implementation is pretty terrible, but I have not attempted to improve this, just the …
=> Add coronavirus question

psd-web/app/controllers/investigations/project_controller.rb, psd-web/app/views/investigations/coronavirus.html.erb
Add some tweaks in the coronavirus form so we don't depend in the model instance to show errors and can simplify the controller code.
=> add tweaks

psd-web/app/models/comment_activity.rb
This pr improves the consistency of the comment activities.
Previously:
Now:
Main changes:
* Title was weirdly written before
* Titles were incorrectly changing the case of the author
* Comment activities were inconsistent with not showing the author in the subtitle
=> Improve consistency of comment activities

psd-web/app/controllers/users/passwords_controller.rb
Propose changes to https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/480
`UserPasswordsController`
- One of the before filters calls a method that contains just another call to a different method. I believe the second method could be directly called in the filter without the proxy method. 
- Other call mixes logic from the `edit` action with a `require_secondary_authentication` call. It seems to me this should be inline so `edit` logic is wrapped together.
=> Proposal over PR: Inline before action and remove unneeded method

psd-web/app/controllers/concerns/secondary_authentication_concern.rb, psd-web/app/controllers/secondary_authentications_controller.rb, psd-web/app/forms/secondary_authentication_form.rb, psd-web/app/models/secondary_authentication.rb, psd-web/app/views/secondary_authentications/new.html.erb, psd-web/config/routes.rb, psd-web/db/migrate/20200424100228_add_secondary_authentication_operation_to_users.rb, psd-web/db/schema.rb, psd-web/spec/features/admin_spec.rb, psd-web/spec/features/creating_an_account_from_an_invitation_spec.rb, psd-web/spec/features/password_reset_spec.rb, psd-web/spec/features/registration_spec.rb, psd-web/spec/features/sign_in_spec.rb, psd-web/spec/forms/secondary_authentication_form_spec.rb, psd-web/spec/models/secondary_authentication_spec.rb, psd-web/spec/requests/secondary_authentication_spec.rb, psd-web/spec/requests/user_completes_registration_spec.rb, psd-web/spec/requests/user_resets_password_spec.rb, psd-web/spec/support/devise.rb
To be merged after all specs will pass.
=> First part of refactoring to remove SA records with Steve

psd-web/app/models/team.rb
This method seems pointless to me and doesn't appear to be used anywhere in our app.
=> Remove unused method

psd-web/deploy-review.sh
Need to use `cf7` on GitHub workflows.
=> Fix multiple database binding on review apps

psd-web/Gemfile, psd-web/Gemfile.lock
**CHANGES:**
Pin sprockets to 3.7.2 as 4.0.0 is broken
=> Pin sprokets to 3.7.2 as 4.0.0 is broken

doc/tasks.md
https://trello.com/c/Yt7uEDsr/338-user-deletion-deactivation
Adds documentation for running the Rake task in the live environments.
=> Add documentation for deleting a user

psd-web/app/models/user.rb
This fixes and error while deleting user. I think this line is hangover from from the first implementation of 2FA
=> Remove unecessary relationship

.github/workflows/overrides/bugfix-filtering-cases-assigned-to-me.env, .github/workflows/overrides/re-fix-seed.env, psd-web/db/seeds.rb, psd-web/deploy-review.sh, psd-web/manifest.review.yml
1. there was multiple duplicate emails.
2. Also had to change how to get the seeds data, by using a labeled service, which we can then find the credentials by.
=> Re fix seed

psd-web/app/views/searches/show.html.erb
Fixes:
* Page title wasn't working
* Content shown when no results had changed.
Whilst doing this I've slightly improved the title from 'cases' to 'case search results'.
=> fix small bugs with title and content

psd-web/app/controllers/collaborators_controller.rb, psd-web/app/controllers/investigations/coronavirus_related_controller.rb, psd-web/app/controllers/investigations/ownership_controller.rb, psd-web/app/controllers/investigations_controller.rb, psd-web/config/locales/en.yml, psd-web/spec/requests/edit_collaborator_spec.rb, psd-web/spec/requests/investigations/coronavirus_related_spec.rb
Updates the flash messages for several different investigation activities.
Also fixes a bug where a flash message wasn't shown
Introduces a flash message when adding a team to a case.
=> Update flash message content

psd-web/app/helpers/investigations/display_text_helper.rb
Fixes an issue caused by the last deployment. https://sentry.io/organizations/beis/issues/1680007638/?project=1329381&referrer=slack
No tests added yet as it needs a quick fix.
=> Fix error caused by not passing user

psd-web/app/views/comments/new.html.erb, psd-web/app/views/documents_flow/upload.html.erb, psd-web/app/views/investigations/businesses/details.html.erb, psd-web/app/views/investigations/coronavirus_related/show.html.erb, psd-web/app/views/investigations/edit_summary.html.erb, psd-web/app/views/investigations/emails/confirmation.html.erb, psd-web/app/views/investigations/meetings/confirmation.html.erb, psd-web/app/views/investigations/ownership/confirm.html.erb, psd-web/app/views/investigations/phone_calls/confirmation.html.erb, psd-web/app/views/invitations/new.html.erb
This mainly has the advantage of not needing to add the `govuk-back-link` class everywhere, and also is forward-compatible in case of any HTML changes.
=> Use back link component helper

psd-web/db/migrate/20200514123702_add_collaborators_references_to_collaborations.rb, psd-web/db/schema.rb
Migration is not working on staging
=> Fix migration

psd-web/db/migrate/20200528082345_add_constraints_on_collaborations.rb, psd-web/db/schema.rb
Last bit from refactoring collaborators.
=> Add constraints

psd-web/app/views/application/_breadcrumbs_navigation.html.erb, psd-web/app/views/application/_breadcrumbs_navigation.html.slim, psd-web/app/views/application/_business_heading.html.erb, psd-web/app/views/application/_business_heading.html.slim, psd-web/app/views/application/_investigation_heading.html.erb, psd-web/app/views/application/_investigation_heading.html.slim, psd-web/app/views/application/_investigations_summary.html.erb, psd-web/app/views/application/_investigations_summary.html.slim, psd-web/app/views/application/_minimal_investigation_heading.html.erb, psd-web/app/views/application/_minimal_investigation_heading.html.slim, psd-web/app/views/application/_product_heading.html.erb, psd-web/app/views/application/_product_heading.html.slim
This is a straight conversion, apart from also fixing a `<p>` which was nested within an `<h1>` (which is invalid).
=> Convert Slim partials to ERb

psd-web/db/migrate/20200604192242_create_creator_users_from_user_source.rb
=> Make migration fail proof

psd-web/app/controllers/investigations/risk_level_controller.rb, psd-web/app/decorators/investigation_decorator.rb, psd-web/app/forms/risk_level_form.rb, psd-web/app/models/audit_activity/investigation/risk_level_updated.rb, psd-web/app/models/investigation.rb, psd-web/app/models/investigation/risk_level_change.rb, psd-web/app/services/change_case_risk_level.rb, psd-web/app/views/investigations/risk_level/show.html.erb, psd-web/config/locales/en.yml, psd-web/db/migrate/20200708184946_change_risk_level_to_enum.rb, psd-web/db/schema.rb, psd-web/spec/decorators/investigation_decorator_spec.rb, psd-web/spec/features/set_investigation_risk_level_spec.rb, psd-web/spec/forms/risk_level_form_spec.rb, psd-web/spec/models/audit_activity/investigation/risk_level_updated_spec.rb, psd-web/spec/models/investigation/risk_level_change_spec.rb, psd-web/spec/models/investigation_spec.rb, psd-web/spec/services/change_case_risk_level_spec.rb
=> Proposition to simplify risk level

.github/workflows/deploy.yml, deploy.sh, manifest.yml
This resolves some free disk space errors we have been experiencing when processing file uploads. It is now configurable using the same conventions as memory and instances.
=> Increase disk quota for prod/staging

app/controllers/help_controller.rb, app/views/help/accessibility.html.erb, app/views/layouts/application.html.slim, config/routes.rb, spec/requests/accessibility_statement_spec.rb
Adds a page which describes how accessible the service is.
=> Add accessibility statement

db/migrate/20201015114750_remove_psd_user_roles.rb, db/schema.rb
This is now longer needed, following #950.
=> Remove psd_user role

doc/tasks.md
This documents how to specify a disk quota for the instances that run tasks, as the default is insufficient.
=> Update documentation for running tasks

Gemfile.lock
this dependencies where slightly out of date. Particularly ffi might help in fixing the segfault we are experiencing
=> Update ffi and zeitwerk.

app/decorators/product_decorator.rb, spec/decorators/product_decorator_spec.rb
https://sentry.io/organizations/beis/issues/2020584136/?project=1329381
=> Fix sentry error, missing a method

spec/features/edit_a_product_spec.rb
**CHANGES:**
Add test to cover adding a document to a product
=> Improve test coverage

db/seeds.rb, docker-compose.yml, docker/web/Dockerfile, docker/web/docker-entrypoint.sh, docker/worker/Dockerfile
This fixes some issues running the stack using the included Docker config and also fixes an issue running seeds:
* Updates Ruby, Node and Bundler dependency versions
* Resolves issue introduced since moving the code from `./psd-web` to root.
* Removes redundant X frame buffer process which was only used to support the redundant system test suite.
* Removed `webpack-dev-server` usage which is now no longer needed.
* Fixed the seeds trying to populate the `summary` of a corrective action, which was recently renamed `other_action`.
=> Update Docker config and fix seeds

app/helpers/application_form_builder.rb, app/views/investigations/test_results/_form.html.erb, app/views/investigations/test_results/edit.html.erb, app/views/investigations/test_results/new.html.erb
https://trello.com/c/zG7NnnjB/820-accessibility-issue-on-test-result-page
This fixes issues with all fields except the file upload field. There is another piece of work ongoing concurrently to refactor the test results code which will make fixing this field with existing patterns easier.
=> Fix accessibility issues on test results form

app/decorators/product_decorator.rb, app/views/products/_form.html.erb, spec/decorators/product_decorator_spec.rb, spec/features/add_product_spec.rb, spec/features/create_allegation_as_opss_user_spec.rb, spec/features/edit_a_product_spec.rb, spec/features/report_product_spec.rb, spec/features/update_product_details_spec.rb
https://trello.com/c/vbrTTFH9/829-amendments-to-add-product-page
Minor copy tweaks for consistency.
=> Update product form labels and hint text

app/controllers/investigations/risk_validations_controller.rb, app/forms/risk_validation_form.rb, app/helpers/investigations_helper.rb, app/mailers/notify_mailer.rb, app/models/audit_activity/investigation/update_risk_level_validation.rb, app/models/investigation.rb, app/models/user.rb, app/policies/investigation_policy.rb, app/services/change_risk_validation.rb, app/views/investigations/activities/investigation/_update_risk_level_validation.html.erb, app/views/investigations/risk_validations/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20201207173507_add_is_risk_validated_to_investigation.rb, db/schema.rb, spec/features/validate_risk_level_spec.rb, spec/models/investigation_spec.rb
=> Edit risk validation

app/controllers/investigations/risk_validations_controller.rb, app/helpers/investigations_helper.rb, spec/requests/investigations/validate_risk_level_spec.rb
https://trello.com/c/DugCGZfi/866-fix-security-issue-related-to-validating-case-risk-level
Add protection to the risk validation controller methods to ensure only users with the correct permissions can access the edit and update actions
=> Risk validation security fix

app/controllers/investigations_controller.rb, app/views/investigations/index.xlsx.axlsx, spec/requests/export_investigations_spec.rb
https://trello.com/c/dUHnCgvO/890-add-case-creator-team-to-export
Add case_creator_team to our csv export
=> Add case_creator_team to export

db/migrate/20210125111313_fix_test_result_audit_activity_metadata.rb
Hotfix for https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1144
I have checked the production data and manually fixed two activities where there were more than one test result on the case and the attachments had been changed and were no longer attached to the test result.
=> Fix migration where there is no metadata on the activity

db/migrate/20210125111313_fix_test_result_audit_activity_metadata.rb
=> Fix test result migration

db/migrate/20210223125626_fix_corrective_actions_added_geographic_scopes.rb, db/schema.rb
Fix  this sentry error https://sentry.io/organizations/beis/issues/2226867247/?project=1329381&referrer=slack
=> migrate non array geographic scopes to array

db/migrate/20210223125626_fix_corrective_actions_added_geographic_scopes.rb, db/schema.rb
=> Fix corrective action audit geographic scopes

db/migrate/20210224113829_reconcile_corrective_action_without_document_attached.rb, db/schema.rb
reconcile corrective action and its audit using timestamp.
=> reconcile audit an corrective action by created_at time

db/migrate/20210224113829_reconcile_corrective_action_without_document_attached.rb
=> Fix corrective action audit added without attached document

app/decorators/unexpected_event_decorator.rb, app/forms/accident_or_incident_form.rb, app/forms/supporting_information_type_form.rb, app/helpers/investigations/accident_or_incidents_helper.rb, app/helpers/investigations_helper.rb, app/views/investigations/accident_or_incidents/_form.html.erb, app/views/investigations/accident_or_incidents/edit.html.erb, app/views/investigations/accident_or_incidents/new.html.erb, app/views/investigations/accident_or_incidents/show.html.erb, app/views/investigations/accident_or_incidents_type/new.html.erb, app/views/investigations/activities/accident_or_incident/_accident_or_incident_added.html.erb, config/locales/en.yml, spec/decorators/audit_activity/accident_or_incident/accident_or_incident_added_decorator_spec.rb, spec/features/add_an_accident_or_incident_to_a_case_spec.rb, spec/features/edit_an_accident_or_incident_spec.rb, spec/support/features/page_expectations.rb
https://trello.com/c/ODwzxBNs/926-accident-and-incident-tweaks
=> Tweaks to accident and incidents copy

spec/requests/export_investigations_spec.rb
Ensure the uniqueness of Faker::Hipser.word
=> fix Flaky spec

app/controllers/investigations_controller.rb, app/views/investigations/index.xlsx.axlsx, spec/factories/risk_assessments.rb, spec/requests/export_investigations_spec.rb
https://trello.com/c/0y256WnI/953-add-riskassessments-counter-to-case-export
Adds an extra column to the case export file.
=> Add risk assessment count to case export

lib/tasks/backfill_team_countries.rake
Add logging to figure out why rake task is failing
=> Backfill country raketask

app/views/help/about.html.erb
=> Update to risk assessment links

app/controllers/investigations/safety_and_compliance_controller.rb, app/decorators/audit_activity/investigation/change_safety_and_compliance_data_decorator.rb, app/forms/why_reporting_form.rb, app/helpers/investigations_helper.rb, app/models/audit_activity/investigation/change_safety_and_compliance_data.rb, app/models/investigation.rb, app/services/change_safety_and_compliance_data.rb, app/views/investigations/activities/investigation/_change_safety_and_compliance_data.html.erb, app/views/investigations/index.xlsx.axlsx, app/views/investigations/safety_and_compliance/edit.html.erb, app/views/investigations/tabs/_overview.html.erb, config/locales/en.yml, config/routes.rb, spec/features/change_safety_and_compliance_spec.rb, spec/features/report_product_spec.rb, spec/requests/export_investigations_spec.rb, spec/services/change_safety_and_compliance_data_spec.rb
https://trello.com/c/uo3Po1he/970-5-edit-safety-and-compliance-information
Allow users to edit safety and compliance information for a case
=> Safety and compliance

config/constants/legislation_constants.yml
https://trello.com/c/Ho24bSt9/984-amend-legislation-list
Amend noise emission legislation as per trello card
=> Amend noise emission legislation

config/constants/product_constants.yml, lib/tasks/update_motor_vehicle_category_products.rake
https://trello.com/c/kSpV34Hf/982-2-change-to-motor-vehicles-product-category
Change product category string in yml file and add rake task to update products with old motor vehicles category
=> Change motor vehicle product category

app/decorators/audit_activity/test/result_decorator.rb, app/forms/test_result_form.rb, app/models/audit_activity/test/test_result_updated.rb, app/services/update_test_result.rb, app/views/investigations/activities/test/_result.html.erb, app/views/investigations/ts_investigations/product_images.html.slim, spec/features/add_test_results_spec.rb, spec/features/edit_test_result_spec.rb, spec/features/report_product_spec.rb, spec/models/audit_activity/test/test_result_updated_spec.rb
https://trello.com/c/6NkU8dEZ/857-test-result-audit-log-missing-some-info
Various fixes around the audit log for test results
=> Test result attachment errors

app/controllers/investigations/actions_controller.rb, app/forms/investigation_actions_form.rb, app/helpers/investigations_helper.rb, config/locales/en.yml, spec/forms/investigation_actions_form_spec.rb
https://trello.com/c/KGnPDfS5/686-add-change-set-case-risk-level-to-case-bar-menu
Add 'change/set case risk level' to case bar menu
=> Risk level action

Gemfile.lock
removes a warning at rails startup time
=> bump parser gem

app/controllers/searches_controller.rb, app/helpers/investigations_helper.rb
This should fix the following error https://sentry.io/organizations/beis/issues/2328211151/?project=1329381&referrer=slack
I was not able to reproduce the error, this could have happen during a deploying the new search form
=> Fix sentry error

docker-compose.yml, docker/web/docker-entrypoint.sh
1. use bin/rails 
2. use yarn 🤦  not webacker:install which overwrite configuration files
=> fix docker setup

spec/services/remove_product_from_case_spec.rb
Test was failing on master - I wonder whether merging guards are all set properly.
=> fix failing spec

.github/workflows/review-apps-delete-dangling.yml
Fixes an infinite loop causing the script to timeout and fail.
=> Fix bug in delete dangling review apps script

.github/workflows/review-apps.yml, lib/tasks/index.rake
This indexes the seeds after successful deploys
=> index after successful deploys

app/models/comment_activity.rb
CommentActivity no longer used. This PR deletes it.
=> Comment activity no longer needed

config/constants/whitelisted_emails.yml
https://trello.com/c/AevE68rc/1076-add-team-to-psd
=> Add domain name to whitelist

app/views/investigations/_filters.html.erb, app/views/investigations/_heading.html.erb, app/views/investigations/_search_bar.html.erb, app/views/investigations/index.html.erb, app/views/searches/show.html.erb, spec/features/create_allegation_as_opss_user_spec.rb, spec/features/create_enquiry_as_opss_user_spec.rb, spec/features/create_project_spec.rb, spec/features/delete_user_mid_session_spec.rb, spec/features/home_page_spec.rb, spec/features/opening_a_new_case_as_opss_user_spec.rb
https://trello.com/c/9tlVBnmU/1214-case-search-page-improvements-5
- Add details with help text
- Replace Open a new case button with Create a case link
- Make keyword search bar more prominent (separate out from filters and expand)
- Add Filters header to filters
=> Case page design improvements

doc/roles.md
https://trello.com/c/7xRyEL2h/1239-make-darren-a-psdadmin-and-teamadmin-on-staging-document-roles-2
Documentation for the roles available to teams and users.
=> Document the various user and team roles

app/controllers/users/sessions_controller.rb, app/jobs/log_db_metrics_job.rb, app/jobs/send_user_invitation_job.rb
https://trello.com/c/49rWAeuX/1161-kibana-dashboard-for-psd
- Add in logging for 2 additional events: `Failed sign in attempt` and `Invitation sent to user`.
- Filter out deleted users from the user related metrics in `log_db_metrics_job`
- Add additional deleted users metric to `log_db_metrics_job` to allow us to visualise the number of deleted users in kibana.
=> More kibana logging

app/views/businesses/index.html.erb, app/views/products/index.html.erb
https://trello.com/c/gjAmxKNv/1272-bug-duplicate-id-used-in-the-products-search-page
=> Fix duplicate HTML element ID on products and businesses pages

app/views/homepage/non_opss.html.erb, config/locales/en.yml, spec/features/viewing_introduction_spec.rb
https://trello.com/c/fzjaCQEc/1278-change-open-a-new-case-to-create-a-case-on-the-ts-homepage
=> Change button label for MSA users

app/views/investigations/_filters.html.erb, app/views/investigations/_search_result.html.erb, app/views/investigations/heading/_all_cases.html.erb
https://trello.com/c/qDuiwaVU/1349-snags-on-the-cases-pages-your-cases-team-cases-all-cases-search
Small presentational/copy changes on the cases page.
=> Fix some presentation issues on the cases apge

app/models/case_export.rb, doc/roles.md, spec/models/case_export_spec.rb, spec/requests/export_cases_spec.rb
https://trello.com/c/hcskigvK/1359-alldataexporter-role-review
- Note the team eligible to receive the all_data_exporter role in the roles doc.
- Remove source column, replacing it with source type column. Note: We actually already had the source type recorded in the export, this PR changes the column header from Complainant_Type to Source_Type as per the trello card.
=> Data export updates

app/views/investigations/_navigable_case_nav.html.erb, app/views/investigations/activities/show.html.erb, app/views/investigations/businesses/index.html.erb, app/views/investigations/images/index.html.erb, app/views/investigations/products/index.html.erb, app/views/investigations/show.html.erb, app/views/investigations/supporting_information/index.html.erb, spec/features/add_business_spec.rb, spec/features/add_product_spec.rb, spec/features/change_case_status_spec.rb
https://trello.com/c/YHeMLORM/1453-implement-new-header-sections-across-all-cases-pages
Change the headers the case pages to maintain consistency and give extra information to the users
=> Add header sections for each sub page on case page

app/controllers/products_controller.rb
This action had no route and is old redundant code.
=> Remove the destroy action for products

app/decorators/product_decorator.rb, app/forms/product_form.rb, app/models/concerns/investigation_opensearch.rb, app/models/investigation_product.rb, app/models/product.rb, app/models/product_export.rb, app/views/investigations/products/new.html.erb, app/views/products/_product.json.jbuilder, app/views/products/edit.html.erb, db/migrate/20220921095355_move_investigation_product_fields.rb, db/schema.rb, db/seeds.rb, lib/tasks/rapex_import.rake, spec/decorators/product_decorator_spec.rb, spec/features/export_products_spec.rb, spec/models/product_export_spec.rb, spec/services/opensearch_query_spec.rb, spec/support/product_helper.rb
https://trello.com/c/I3imrFNG/1520-data-migration-of-4-pieces-of-case-specific-info-from-product-to-case
Migrate investigation product data from the products table to the investigation products table and remove references to these removed columns
=> Investigation product data migration

app/helpers/investigations_helper.rb, app/views/investigations/tabs/_overview.html.erb, config/locales/en.yml, spec/features/case_specific_information_spec.rb
https://trello.com/c/CFxQxHOo/1516-case-landing-page-case-specific-info-cap106
Show the case specific information on the investigation page.
- empty fields with an explanation text if no products are added.
- products in order from oldest to newest if products are added
=> Case specific info

app/controllers/investigation_products/batch_numbers_controller.rb, app/decorators/audit_activity/investigation/update_batch_number_decorator.rb, app/forms/batch_numbers_form.rb, app/helpers/investigations_helper.rb, app/models/audit_activity/investigation/update_batch_number.rb, app/services/change_batch_number.rb, app/views/investigation_products/batch_numbers/edit.html.erb, app/views/investigations/activities/investigation/_update_batch_number.html.erb, app/views/investigations/tabs/_overview.html.erb, config/routes.rb, spec/features/case_specific_information_spec.rb, spec/support/features/page_expectations.rb
=> Edit batch numbers logic

app/assets/stylesheets/opss/_opss-shared.scss, app/controllers/comments_controller.rb, app/decorators/product_decorator.rb, app/helpers/investigations_helper.rb, app/policies/investigation_policy.rb, app/views/investigations/_actions.html.erb, app/views/investigations/_navigable_case_nav.html.erb, app/views/investigations/activities/show.html.erb, app/views/investigations/show.html.erb, app/views/investigations/tabs/_overview.html.erb, app/views/products/case_product_info_tabs/_details.html.erb, spec/features/add_activity_entry_spec.rb, spec/features/change_case_status_spec.rb, spec/requests/add_comment_spec.rb
https://trello.com/c/7F9pazdx/1525-closing-a-case-the-html-page-design-changes-cap012
- Design updates around how a case page looks when it is closed
- Design updates to a case's products list
- Permissions changes
- Nobody can edit a closed case
- Nobody can comment on a closed case
- Only the case owner team - or added team with editing rights - can reopen a case
=> Design updates to closed cases

config/application.rb
Add time to the permitted classes to safe load yaml
=> Add time to yaml classes

app/assets/stylesheets/opss/_opss-psd.scss, app/assets/stylesheets/opss/_opss-shared.scss, app/decorators/investigation_product_decorator.rb, app/decorators/product_decorator.rb, app/helpers/investigations_helper.rb, app/policies/investigation_product_policy.rb, app/views/investigations/tabs/_products.html.erb, app/views/products/case_product_info_tabs/_details.html.erb, app/views/products/case_product_info_tabs/_images.html.erb, app/views/products/show.html.erb, spec/decorators/investigation_product_decorator_spec.rb, spec/decorators/product_decorator_spec.rb, spec/features/change_case_status_spec.rb, spec/features/remove_product_from_a_case_spec.rb, spec/features/safe_and_compliant_products_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1174
- Provides links to a product's owning team on a case's products list
- Interim update on the product page to make the metadata consistent
=> Design changes for metadata on a case's products page

app/decorators/product_decorator.rb, app/models/product.rb, app/views/investigations/tabs/_products.html.erb, app/views/products/case_product_info_tabs/_cases.html.erb, spec/decorators/product_decorator_spec.rb, spec/features/add_product_to_case_spec.rb, spec/features/case_products_tab_spec.rb, spec/features/sort_products_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1165
Changes to the cases section of the case product page.
- Do not show the current case on the products case tab.
- Order products cases by most recently created to least recently created.
- Copy change
=> Cases for products page

app/views/layouts/application.html.erb
https://regulatorydelivery.atlassian.net/browse/PSD-1095
- Changes the feedback link to a new URL
=> Update the service feedback link

doc/deployment.md
Fix to doc around deployments - review deploy URL was incorrect
=> Fix review deploy URL in docs

app/decorators/product_decorator.rb, app/views/create_a_case_page/index.html.erb, app/views/investigations/products/new.html.erb, spec/features/add_product_to_case_spec.rb, spec/features/product_versioning_spec.rb, spec/features/retired_products_spec.rb, spec/features/update_product_details_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1303
- Makes some small formatting and copy changes to the following pages:
- The "Create a Case" page
- The "Find/Add Product" page
- The Product and Case's Products pages
=> Copy and formatting changes

config/constants/whitelisted_emails.yml
Adds Department of Justice Northern Ireland as per[ this support request](https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1346).
=> Whitelist justice-ni.gov.uk

app/assets/stylesheets/_psd_header.scss
Added Darren's CSS to fix menu drop down bug for mobile views
New PR for `master` instead of feature branch
https://regulatorydelivery.atlassian.net/browse/PSD-1298
=> Fix menu dropdown for mobiles

app/decorators/investigation_product_decorator.rb, app/decorators/product_decorator.rb, app/views/products/_sub_nav.html.erb, app/views/products/show.html.erb, spec/features/retired_products_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1163
Changes to the ui on retired product pages as outlined in the above ticket.
=> Retired product UI changes

app/services/add_product_to_case.rb, db/seeds.rb
Clears up the TODO items we introduced as transitional steps during development.
=> Resolve new-case-creation-flow-phase-2 TODOs

app/javascript/investigations/attachment_description.js, app/javascript/investigations/sort_dropdown.js, app/javascript/investigations/ts_investigations/which_businesses.js, app/views/investigations/creation_flow/allegation_details.html.erb, package.json, yarn.lock
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1368
* Removes jQuery dependency from all JavaScript files below `app/javascript`
* Updates some syntax
* Removes jQuery
=> Remove jQuery (part 2)

doc/using-cloud-foundry.md
Some docs for how to copy staging data into a review app on cloudfoundry
=> CF docs, copying data from staging to review app

.github/workflows/review-apps.yml, Gemfile.lock, manifest.review.yml, smoke_test/cases_page_without_2fa_spec.rb
=> Remove 2fa step from review apps, separate smoke test

db/migrate/20230323103006_migrate_papertrail_to_json_blobs.rb
=> Safely create new version columns, migration breaking review apps

db/schema.rb
The schema.rb wasn't committed -
=> Commit schema change for PaperTrail revert PR

.github/workflows/deploy.yml
Another instance of the smoke test run without 2FA
=> duplicate smoke test

app/views/investigations/_create_a_case_link.html.erb, spec/features/create_allegation_as_opss_user_spec.rb, spec/features/create_enquiry_as_opss_user_spec.rb, spec/features/create_project_spec.rb, spec/features/opening_a_new_case_as_opss_user_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?modal=detail&selectedIssue=PSD-1436
Changes create a case link for OPSS users
=> change create a case link

.github/workflows/codeql.yml, .github/workflows/deploy-staging.yml
=> Added staging deploy config

.github/workflows/deploy-staging.yml, .github/workflows/review-apps.yml
=> Updated log URL

.github/workflows/deploy-production.yml
This is a deploy file for the production instance off main
=> Production deploy

.github/workflows/deploy-production.yml, manifest.yml
=> Upgrade redis

manifest.yml
=> Rename redis services

app/views/investigations/overseas_regulator/edit.html.erb
A quick text change om the notifying country form help text following feedback from the business.
=> removed GB from help text on notifying country

Gemfile, Gemfile.lock
Tech debt, removing unused gem
https://regulatorydelivery.atlassian.net/browse/PSD-1398
=> Remove unused jbuilder gem (PSD-1398)

app/decorators/investigation_decorator.rb, spec/decorators/investigation_decorator_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1709
=> Fix case link if user_title not given - PSD-1709

app/views/investigations/_restricted_table_body.html.erb
=> add safe operator

app/models/concerns/investigation_opensearch.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1493
Added the user provided case reference `complainant_reference` to index for search - uses exact match only for more accuracy
=> Index case's user provided reference - PSD-1493

app/controllers/investigations/businesses_controller.rb, app/views/investigations/_restricted_table_body.html.erb
* https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/pull/2439
* https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/pull/2459
=> Merge hotfixes into develop

app/controllers/investigations/risk_assessments_controller.rb, spec/features/view_a_risk_assessment_spec.rb
Cherry-picked the hotfix into main to keep develop updated
https://regulatorydelivery.atlassian.net/browse/PSD-1770
=> Bugfix: Risk assessments controller

app/models/user.rb, app/views/products/show.html.erb
=> Hide product recall

app/models/user.rb
This is a small PR to allow demo with the team and make changes
=> allow all users to see the recall tool - temp

config/constants/product_constants.yml, lib/tasks/august_data.rake
https://regulatorydelivery.atlassian.net/browse/PSD-1836
=> Develop PR - Data reporting updates

app/decorators/investigation_decorator.rb, spec/decorators/investigation_decorator_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-1892
Remove 'case restricted' from title on Product page.
=> Removed restricted title

prism/app/controllers/prism/tasks/evaluate_controller.rb, prism/app/helpers/prism/tasks/evaluate_helper.rb, prism/app/helpers/prism/tasks_helper.rb, prism/app/javascript/locales/en.json, prism/app/models/prism/risk_assessment.rb, prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_evaluation.html.erb, prism/app/views/prism/tasks/view_submitted_assessment.html.erb, prism/config/initializers/constants.rb, prism/config/locales/en.yml, spec/factories/prism/risk_assessment.rb, spec/features/prism/risk_assessment_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1919
Tweaks the existing workflow to accommodate serious risk evaluations.
N/A
=> PRISM: serious risk workflow

app/controllers/products/recalls_controller.rb, app/forms/product_recall_form.rb, app/services/generate_product_recall_pdf.rb, app/views/products/recalls/complete.html.erb, app/views/products/recalls/product-details.html.erb, config/brakeman.ignore
=> Product Recall Amends

prism/app/javascript/locales/en.json, prism/app/services/prism/risk_assessment_pdf_service.rb, prism/app/views/prism/tasks/create/add_steps_to_harm.html.erb, prism/app/views/prism/tasks/create/choose_hazard_type.html.erb, prism/app/views/prism/tasks/create/determine_severity_of_harm.html.erb, prism/app/views/prism/tasks/create/estimate_probability_of_harm.html.erb, prism/app/views/prism/tasks/create/identify_who_might_be_harmed.html.erb, prism/app/views/prism/tasks/define/add_details_about_products_in_use_and_safety.html.erb, prism/app/views/prism/tasks/evaluate/consider_perception_and_tolerability_of_the_risk.html.erb, prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_assessment.html.erb, prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_evaluation.html.erb, prism/app/views/prism/tasks/identify/add_a_number_of_hazards.html.erb, prism/app/views/prism/tasks/view_submitted_assessment.html.erb, prism/app/views/prism/triage/full_risk_assessment_required.html.erb, prism/app/views/prism/triage/index.html.erb, prism/app/views/prism/triage/perform_risk_triage.html.erb, prism/app/views/prism/triage/serious_risk.html.erb, prism/app/views/prism/triage/serious_risk_rebuttable.html.erb, prism/config/locales/en.yml, spec/features/prism/risk_assessment_spec.rb, spec/features/prism/triage_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1900
Makes a number of text changes to the PRISM workflow.
N/A
https://psd-pr-2580.london.cloudapps.digital/
https://psd-pr-2580-support.london.cloudapps.digital/
=> PRISM: text changes

app/models/business_export.rb, app/models/case_export.rb, app/models/product_export.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1915
Removes the 1000 record limit for all spreadsheet exports.
N/A
https://psd-pr-2603.london.cloudapps.digital/
https://psd-pr-2603-support.london.cloudapps.digital/
=> Fix export file limits

app/helpers/businesses_helper.rb, app/helpers/investigations_helper.rb, app/helpers/products_helper.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2031
The `includes(:...` for the initial eager load of records was duplicating the id for each, due to the inner joins. The `pluck(:id)` then just runs a select on the whole collection, which returns ID duplicates for each case. Adding a `.distinct` here then removes these duplicates at the query layer
```
ids = Investigation.not_deleted.includes(:owner_user, :owner_team, :creator_user, :creator_team, :collaboration_accesses, :activities).pluck(:id)
Investigation Pluck (4.8ms)  SELECT "investigations"."id" FROM "investigations" LEFT OUTER JOIN "collaborations" ON "collaborations"."collaborator_type" = $1 AND "collaborations"."investigation_id" = "investigations"."id" AND "collaborations"."type" = $2 LEFT OUTER JOIN "users" ON …
```
=> Fix duplicates for exports - PSD-2031

app/controllers/bulk_products_controller.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2113
Allows Excel file with product entries that don’t have barcodes to be uploaded and treated as new products.
N/A
https://psd-pr-2670.london.cloudapps.digital/
https://psd-pr-2670-support.london.cloudapps.digital/
=> Allow empty barcodes for bulk products uploads

.github/workflows/code-style.yml, .github/workflows/codeql.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-research.yml, .github/workflows/deploy-staging.yml, .github/workflows/erd.yml, .github/workflows/publish-production-redacted-export.yml, .github/workflows/publish-staging-redacted-export.yml, .github/workflows/review-apps-delete-dangling.yml, .github/workflows/review-apps-delete.yml, .github/workflows/review-apps.yml, .github/workflows/rspec.yml, .github/workflows/security-warnings.yml, manifest.review.yml, manifest.yml
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2121
Changes the production workflow to use release-based deployments.
Also updates all GitHub action versions and buildpacks.
N/A
https://psd-pr-2685.london.cloudapps.digital/
https://psd-pr-2685-support.london.cloudapps.digital/
=> Change to release-based deployment

app/decorators/investigation_business_decorator.rb
Fixes an issue where a missing business relationship fails.
N/A
https://psd-pr-2692.london.cloudapps.digital/
https://psd-pr-2692-support.london.cloudapps.digital/
=> Fix investigation decorator bug

doc/decisions/0000-template.md, doc/decisions/0001-use-erb-for-view-templates.md, doc/decisions/0002-searchkick-and-opensearch.md, doc/decisions/0003-use-github-releases-for-deployments-to-production.md, doc/deployment.md, doc/using-cloud-foundry.md
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2126
Documents the pre-prod and production release process and adds an ADR with the reasons behind the change.
N/A
https://psd-pr-2693.london.cloudapps.digital/
https://psd-pr-2693-support.london.cloudapps.digital/
=> Document release process

app/models/role.rb, app/models/user.rb, app/services/delete_user.rb, db/migrate/20231116112059_add_entity_to_paper_trail_versions.rb, db/schema.rb, spec/domain_helpers.rb, spec/features/support_portal/account_administration_spec.rb, spec/rails_helper.rb, support_portal/app/controllers/support_portal/account_administration_controller.rb, support_portal/app/controllers/support_portal/history_controller.rb, support_portal/app/helpers/support_portal/account_administration_helper.rb, support_portal/app/helpers/support_portal/date_helper.rb, support_portal/app/helpers/support_portal/history_helper.rb, support_portal/app/models/support_portal/invite_user_form.rb, support_portal/app/views/support_portal/account_administration/edit_email.html.erb, support_portal/app/views/support_portal/account_administration/edit_mobile_number.html.erb, support_portal/app/views/support_portal/account_administration/edit_name.html.erb, support_portal/app/views/support_portal/account_administration/edit_team_admin_role.html.erb, support_portal/app/views/support_portal/account_administration/index.html.erb, support_portal/app/views/support_portal/account_administration/invite_user.html.erb, support_portal/app/views/support_portal/account_administration/remove_user.html.erb, support_portal/app/views/support_portal/account_administration/search.html.erb, support_portal/app/views/support_portal/account_administration/search_results.html.erb, support_portal/app/views/support_portal/account_administration/show.html.erb, support_portal/app/views/support_portal/dashboard/index.html.erb, support_portal/app/views/support_portal/history/index.html.erb, support_portal/config/routes.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1849
Adds features to invite and delete users and change their name, email address, mobile number and team admin status.
Also adds a change history log for changes to users and roles.
https://psd-pr-2708.london.cloudapps.digital/
https://psd-pr-2708-support.london.cloudapps.digital/
=> OSU Support Portal: account administration

app/models/test.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2130
- Added additional fields to the redacted exports for test information.
=> Add additional fields to redacted_export

app/jobs/generate_and_upload_redacted_export_csv_job.rb, app/services/redacted_csv_exporter.rb, config/sidekiq.yml, lib/tasks/redacted_export_csv.rake
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-1860
Schedules a Sidekiq job to export redacted CSV files and upload them to S3. Also provides an interactive rake task to do the same on demand.
N/A
https://psd-pr-2714.london.cloudapps.digital/
https://psd-pr-2714-support.london.cloudapps.digital/
=> Schedule redacted export CSV job

app/helpers/investigations_helper.rb, app/models/case_export.rb
Use scroll api to fetch 10k+ results in notification search
https://psd-pr-2715.london.cloudapps.digital/
https://psd-pr-2715-support.london.cloudapps.digital/
=> use scroll api for 10k+ queries

app/helpers/products_helper.rb, app/models/product_export.rb
Refactors the product search so that the export no longer requires two queries.
https://psd-pr-2727.london.cloudapps.digital/
https://psd-pr-2727-support.london.cloudapps.digital/
=> refactor product export

app/helpers/businesses_helper.rb, app/models/business_export.rb
Refactor business export so it no longer uses two queries
https://regulatorydelivery.atlassian.net/browse/PSD-2070
https://psd-pr-2728.london.cloudapps.digital/
https://psd-pr-2728-support.london.cloudapps.digital/
=> refactor businesses export and search

db/migrate/20231124151736_add_more_fields_to_prism_evaluations.prism.rb, db/schema.rb, prism/app/controllers/prism/tasks/evaluate_controller.rb, prism/app/controllers/prism/tasks/outcome_controller.rb, prism/app/helpers/prism/tasks/evaluate_helper.rb, prism/app/javascript/locales/en.json, prism/app/models/prism/evaluation.rb, prism/app/models/prism/risk_assessment.rb, prism/app/services/prism/risk_assessment_pdf_service.rb, prism/app/views/prism/tasks/evaluate/consider_perception_and_tolerability_of_the_risk.html.erb, prism/app/views/prism/tasks/evaluate/consider_the_nature_of_the_risk.html.erb, prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_assessment.html.erb, prism/app/views/prism/tasks/evaluate/review_and_submit_results_of_the_evaluation.html.erb, prism/app/views/prism/tasks/outcome/confirm_overall_product_risk.html.erb, prism/app/views/prism/tasks/view_submitted_assessment.html.erb, prism/app/views/prism/triage/perform_risk_triage.html.erb, prism/config/locales/en.yml, prism/db/migrate/20231124151610_add_more_fields_to_prism_evaluations.rb, spec/features/prism/risk_assessment_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2165
Updates text and adds new fields.
N/A
https://psd-pr-2740.london.cloudapps.digital/
https://psd-pr-2740-support.london.cloudapps.digital/
=> PRISM updates

support_portal/app/controllers/support_portal/account_administration_controller.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2248
Hides the `super_user` role to prevent it being granted.
N/A
https://psd-pr-2752.london.cloudapps.digital/
https://psd-pr-2752-support.london.cloudapps.digital/
=> OSU Support Portal: hide super user role

app/models/case_export.rb, spec/models/case_export_spec.rb, spec/requests/export_cases_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?assignee=6411e6661273131f2ae0b4b2&selectedIssue=PSD-2237
Remove columns from data extract
https://psd-pr-2753.london.cloudapps.digital/
https://psd-pr-2753-support.london.cloudapps.digital/
=> remove columns from notification export

app/services/csv_exporter.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2266
Excludes sensitive fields such as passwords and tokens from the CSV export.
N/A
https://psd-pr-2757.london.cloudapps.digital/
https://psd-pr-2757-support.london.cloudapps.digital/
=> Exclude sensitive fields from CSV export

app/models/case_export.rb, spec/models/case_export_spec.rb, spec/requests/export_cases_spec.rb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?assignee=6411e6661273131f2ae0b4b2&selectedIssue=PSD-2239
Change column header in notification export
https://psd-pr-2763.london.cloudapps.digital/
https://psd-pr-2763-support.london.cloudapps.digital/
=> change column header in export

app/decorators/test/result_decorator.rb, app/models/audit_activity/investigation/change_overseas_regulator.rb
Add safe operators to helper/decorator methods.
https://psd-pr-2768.london.cloudapps.digital/
https://psd-pr-2768-support.london.cloudapps.digital/
=> add safe operators to decorator methods

app/controllers/collaborators_controller.rb, app/controllers/investigations/investigation_products_controller.rb, app/mailers/notify_mailer.rb, app/services/delete_team.rb, app/services/remove_product_from_notification.rb, app/services/remove_team_from_notification.rb, config/locales/en.yml, spec/mailers/notify_mailer_spec.rb, spec/models/product_spec.rb, spec/services/delete_team_spec.rb, spec/services/remove_product_from_notification_spec.rb, spec/services/remove_team_from_notification_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2306
https://regulatorydelivery.atlassian.net/browse/PSD-2307
Refactor RemoveProductFromCase -> RemoveProductFromNotification
Refactor RemoveTeamFromCase -> RemoveTeamFromNotification
=> Refactor remove product & team from case - PSD-2306

app/controllers/collaborators_controller.rb, app/forms/edit_notification_collaborator_form.rb, app/mailers/notify_mailer.rb, app/services/change_notification_permission_level_for_team.rb, app/views/collaboration/access/edits/_edit.erb, app/views/collaboration/access/read_onlies/_read_only.erb, app/views/collaborators/edit.html.erb, config/locales/en.yml, spec/features/add_team_to_notification_spec.rb, spec/features/change_team_permission_on_case_spec.rb, spec/forms/edit_notification_collaborator_form_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/requests/edit_collaborator_spec.rb, spec/services/change_notification_permission_level_for_team_spec.rb, spec/services/delete_team_spec.rb, spec/support/features/page_expectations.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2315
Refactors collaboration service & form
=> Refactor change case permission - PSD-2135

app/controllers/bulk_products_controller.rb, app/controllers/investigations/corrective_actions_controller.rb, app/controllers/investigations/risk_assessments_controller.rb, app/services/add_corrective_action_to_notification.rb, app/services/add_risk_assessment_to_notification.rb, db/seeds.rb, spec/features/add_corrective_action_spec.rb, spec/features/remove_business_from_a_notification_spec.rb, spec/models/audit_activity/corrective_action/add_spec.rb, spec/models/audit_activity/risk_assessment/risk_assessment_updated_spec.rb, spec/services/add_corrective_action_to_notification_spec.rb, spec/services/add_risk_assessment_to_notification_spec.rb, spec/services/add_test_result_to_investigation_spec.rb, spec/services/remove_business_from_notification_spec.rb, spec/support/features/page_expectations.rb, spec/support/shared_contexts/add_corrective_action_context.rb, spec/support/shared_contexts/entities_to_notify.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2335
Refactors both service to use notification param
=> Refactor AddRiskAssessmentToCase & AddCorrectiveActionToCase- PSD-2335

app/models/case_export.rb
Rename spreadsheet export
https://psd-pr-2838.london.cloudapps.digital/
https://psd-pr-2838-support.london.cloudapps.digital/
=> rename spreadsheet export

app/controllers/investigations/products_controller.rb, app/controllers/notifications/create_controller.rb, app/services/add_product_to_notification.rb, app/services/create_bulk_products_upload_products.rb, app/services/create_notification.rb, db/seeds.rb, spec/models/product_spec.rb, spec/policies/product_policy_spec.rb, spec/services/add_product_to_notification_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2336
=> Refactor add product to case - PSD-2336

app/controllers/investigation_products/batch_numbers_controller.rb, app/controllers/notifications/create_controller.rb, app/services/change_notification_batch_number.rb, app/services/change_notification_summary.rb, spec/features/case_specific_information_spec.rb, spec/support/features/page_expectations.rb
refactoring Class name and its usages
=> Refactor ChangeBatchNumber to ChangeNotificationBatchNumber

app/controllers/investigations/visibility_controller.rb, app/forms/change_notification_visibility_form.rb, app/services/change_notification_visibility.rb, app/views/investigations/visibility/_form.html.erb, app/views/investigations/visibility/restrict.html.erb, app/views/investigations/visibility/unrestrict.html.erb, spec/forms/change_notification_visibility_form_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2340
Refactor service and form to ChangeNotificationVisibility
=> Refactor change case visibility- PSD-2340

config/routes.rb, report_portal/app/controllers/concerns/secondary_authentication_concern.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2387
Fixes concern file inclusion & route constraints
=> Fix 2fa routes for report engine - PSD-2837

app/controllers/notifications/create_controller.rb, app/helpers/notifications/create_helper.rb, app/models/investigation_product.rb, app/views/notifications/create/check_notification_details_and_submit.html.erb, spec/features/notification_task_list_spec.rb
JIRA ticket: https://regulatorydelivery.atlassian.net/browse/PSD-2124
Adds the “check the notification details and submit” task.
https://psd-pr-2871.london.cloudapps.digital/
https://psd-pr-2871-support.london.cloudapps.digital/
https://psd-pr-2871-report.london.cloudapps.digital/
=> Notification task list: check details and submit

app/controllers/businesses_controller.rb, app/views/businesses/_search_statement.html.erb, app/views/businesses/index.html.erb
Provides accurate count and wording for businesses found using search and filters
https://psd-pr-2873.london.cloudapps.digital/
https://psd-pr-2873-support.london.cloudapps.digital/
https://psd-pr-2873-report.london.cloudapps.digital/
=> provide accurate count for businesses

spec/services/task_list_service_spec.rb
Adds automated tests for the `TaskListService`.
N/A
https://psd-pr-2882.london.cloudapps.digital/
https://psd-pr-2882-support.london.cloudapps.digital/
https://psd-pr-2882-report.london.cloudapps.digital/
=> Add tests for TaskListService

app/views/help/privacy_notice.html.erb, app/views/help/terms_and_conditions.html.erb
Updates the terms and conditions and privacy policy to refer to DBT rather than BEIS.
N/A
https://psd-pr-2897.london.cloudapps.digital/
https://psd-pr-2897-support.london.cloudapps.digital/
https://psd-pr-2897-report.london.cloudapps.digital/
=> Change BEIS to DBT in policies

db/migrate/20240207112516_add_extra_infomation_to_teams.rb, db/schema.rb, lib/tasks/data_migrations.rake
https://regulatorydelivery.atlassian.net/browse/PSD-2198
A two step PR - this is the first to add the columns & migrate the data over from the JSON file on production.
The next step we can remove the file & this new rake task
=> Add team-mappings.json info into db - PSD-2198

app/controllers/active_storage/representations/proxy_controller.rb, app/decorators/audit_activity/corrective_action/add_decorator.rb, app/decorators/audit_activity/corrective_action/update_decorator.rb, app/models/risk_assessment.rb, config/initializers/pagy.rb
* Rescue ActiveStorage file not found errors with 404
* Only run `to_sentence` on arrays
* Allow risk assessment deletion to also delete product associations
* Show last page when pagination asks for further pages
N/A
https://psd-pr-2903.london.cloudapps.digital/
https://psd-pr-2903-support.london.cloudapps.digital/
https://psd-pr-2903-report.london.cloudapps.digital/
=> Fix Sentry errors

app/controllers/api/v1/notifications_controller.rb, app/views/api/v1/notifications/_notification.json.jbuilder, app/views/api/v1/notifications/show.json.jbuilder, config/routes.rb, spec/requests/api/v1/notifications_controller_spec.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2414
Adds notification#show endpoint for the new API
=> Notification show API - PSD-2414

Procfile.dev, config/initializers/rswag_api.rb, config/initializers/rswag_ui.rb, spec/requests/api/v1/auths_controller_spec.rb, spec/requests/api/v1/notifications_controller_spec.rb, spec/requests/api/v1/products_controller_spec.rb, spec/swagger_helper.rb, swagger/v1/swagger.yaml
- moves schemas into helper
- removes deprecation warnings
- regenerates schema
=> Use serializers & refactor API - PSD-2423

.github/workflows/deploy-production.yml
Adds deployment reporting to Sentry to allow exceptions to be tracked to individual deployments.
N/A
https://psd-pr-2916.london.cloudapps.digital/
https://psd-pr-2916-support.london.cloudapps.digital/
https://psd-pr-2916-report.london.cloudapps.digital/
=> Add deployment reporting to Sentry

app/controllers/api/v1/notifications_controller.rb, app/controllers/api/v1/products_controller.rb, config/routes.rb, spec/requests/api/v1/notifications_controller_spec.rb, spec/requests/api/v1/products_controller_spec.rb, spec/swagger_helper.rb, swagger/v1/swagger.yaml
Adds API for product creation, plus enum schemas for creation
=> Create product API - PSD-2073

app/controllers/api/v1/products_controller.rb, app/helpers/products_helper.rb, spec/requests/api/v1/products_controller_spec.rb, swagger/v1/swagger.yaml
- Adds searching for `product_code` in PSD product search (UI and API)
- Adds more params and docs for product search
=> Product search changes - PSD-2428

app/controllers/api/v1/products_controller.rb, app/helpers/products_helper.rb, app/views/api/v1/products/_product.json.jbuilder, spec/requests/api/v1/notifications_controller_spec.rb, spec/requests/api/v1/products_controller_spec.rb
- New product search helper for API - searches on barcode & not description
- Use unformatted descriptions for product in API (no html tags)
=> Diverge API product search - PSD-2436

config/initializers/sentry.rb, prism/test/test_helper.rb, report_portal/test/test_helper.rb, spec/rails_helper.rb, support_portal/test/test_helper.rb
N/A
https://psd-pr-2929.london.cloudapps.digital/
https://psd-pr-2929-support.london.cloudapps.digital/
https://psd-pr-2929-report.london.cloudapps.digital/
=> Fix deprecations

app/controllers/api/v1/notification_products_controller.rb, config/routes.rb, spec/requests/api/v1/notification_products_controller_spec.rb, spec/swagger_helper.rb, swagger/v1/swagger.yaml
Last endpoint in API - adding a product to a notification
=> Add product to notification - PSD-2429

config/initializers/ahoy.rb
https://regulatorydelivery.atlassian.net/browse/PSD-2451
Fixes Ahoy tracking - tested on review app & events and visits are being tracked
=> Fix ahoy tracking - PSD-2451

config/locales/en.yml
Rename add business details page
=> rename add details page

app/controllers/notifications/create_controller.rb, app/views/notifications/create/search_for_or_add_a_business.html.erb
- redirect existing business to confirm business details
- 
=> redirect existing business to confirm business details

.github/workflows/deploy-production.yml, config/sidekiq.yml
* Increase RAM from 2GB to 4GB in production to allow for large file exports
* Run jobs from the `active_storage_purge` queue
N/A
https://psd-pr-2967.london.cloudapps.digital/
https://psd-pr-2967-support.london.cloudapps.digital/
https://psd-pr-2967-report.london.cloudapps.digital/
=> Fix Sidekiq issues

app/forms/add_business_roles_form.rb
Fixes validation on form by rejecting empty values on roles.
=> fix validation for online marketplaces on add roles form

app/helpers/products_helper.rb, spec/requests/api/v1/products_controller_spec.rb, swagger/v1/swagger.yaml
https://regulatorydelivery.atlassian.net/browse/PSD-2471
Fuzzy match product code/identifiers for API search, codes can be hidden in text field
=> Fuzzy match product code for api named search - PSD-2471

app/models/product_export.rb, spec/features/export_products_spec.rb, spec/models/product_export_spec.rb
Rearrange columns in product extract
=> rearrange columns in product extract

app/views/notifications/create/check_notification_details_and_submit.html.erb, spec/features/notification_task_list_spec.rb
N/A
N/A
https://psd-pr-3000.london.cloudapps.digital/
https://psd-pr-3000-support.london.cloudapps.digital/
https://psd-pr-3000-report.london.cloudapps.digital/
=> Remove name from TODO comments

app/views/notifications/show.html.erb
https://regulatorydelivery.atlassian.net/jira/software/c/projects/PSD/boards/57?assignee=712020%3A6867618a-8e2f-4b5d-b582-d11f7621b554&selectedIssue=PSD-2541
Screen-shots
Before
After
=> PSD-2541:Corrective action - date added missing from PSD 2.0 view

app/controllers/notifications/create_controller.rb, app/controllers/notifications/edit_controller.rb
Description
I Altered Business search function to prevent it from matching Business search results to the Business addresses.
=> PSD-2545: Restrict Business search to business names, Postcode and Company's house number

app/controllers/investigations/ts_investigations_controller.rb, app/forms/edit_why_reporting_form.rb, app/helpers/investigations/ts_investigations_helper.rb, app/views/investigations/_why_reporting_form_unsafe_details.html.erb, app/views/investigations/case_names/_form.html.erb, app/views/investigations/case_names/edit.html.erb, app/views/investigations/reported_reason/edit.html.erb, app/views/investigations/safety_and_compliance/edit.html.erb, app/views/investigations/ts_investigations/case_name.html.erb, app/views/investigations/ts_investigations/reason_for_concern.html.erb, app/views/investigations/ts_investigations/reason_for_creating.html.erb, app/views/investigations/ts_investigations/reference_number.html.erb, spec/features/change_notification_name_spec.rb, spec/features/change_notification_safety_and_compliance_spec.rb, spec/features/create_case_spec.rb
Description
This pull request makes changes to the PSD 1.0 case creation journey to use the GOVUKSystemDesignFormBuilder as the default builder for the forms, it also makes changes to the specs to reflect the HTML changes caused by the new form builder.
=> refactor/PSD-2829 -investigations _ts _investigations_form

app/controllers/notifications/create_controller.rb, app/forms/add_test_reports_form.rb, app/views/notifications/create/add_test_reports.html.erb
Description
Created new form model to allow html form to display errors, added handling for new form parameters in create controller
=> chore/PSD-2866:notification-task-list-add-test-reports-page

app/views/investigations/investigation_products/remove.html.erb, app/views/investigations/products/confirm.html.erb, app/views/investigations/products/new.html.erb, spec/features/add_product_to_notification_spec.rb, spec/features/product_versioning_spec.rb, spec/features/remove_product_from_a_notification_spec.rb
Description
Refactored PSD 1.0 and PSD 2.0 add product journey to use GOVUKSystemDesignFormBuilder, made changes to spec test to reflect the html changes caused by new form
=> refactor/PSD-2987:Update_to_investigation_products

app/controllers/document_uploads_controller.rb, app/models/document_upload.rb, app/views/document_uploads/edit.html.erb, app/views/document_uploads/new.html.erb, app/views/document_uploads/remove.html.erb
Description
Updated forms to use GOVUKSystemFormBuilder, made changes to controller to retain file during document upload creation journey
=> refactor/PSD-3001:Update_to_document_uploads_form

app/views/investigations/prism_risk_assessments/new.html.erb, app/views/prism_risk_assessments/add_to_case.html.erb, app/views/prism_risk_assessments/index.html.erb, prism/app/views/prism/triage/serious_risk.html.erb, prism/app/views/prism/triage/serious_risk_rebuttable.html.erb
Description
Refactored prism users risk assessment forms
=> refactor/PSD-3008:Update_to_prism_risk_assessment_form

app/controllers/investigations/prism_risk_assessments_controller.rb, app/forms/select_product_for_prism_form.rb, app/views/investigation_products/number_of_affected_units/edit.html.erb, app/views/investigations/prism_risk_assessments/choose_product.html.erb, app/views/investigations/update_case_risk_level_from_risk_assessment/show.html.erb, spec/features/case_specific_information_spec.rb, spec/support/features/page_expectations.rb
Description
Refactored the last 3 forms still using Application form builder, created new form model to display errors in one of the forms, made changes to the controller to handle the new parameters.
=> refactor/PSD-3010:Update_to_final_forms

app/controllers/products_controller.rb, app/policies/product_policy.rb, app/views/products/_form.html.erb, app/views/products/edit.html.erb, spec/features/edit_a_product_spec.rb, spec/features/update_product_details_spec.rb
Description
Made the product category field editable for users on the edit side of products, made changes to controller to allow category parameter to pass through, made changes to spec to not check for if the category field is editable.
=> refactor/PSD-2530:Update_to_product_form

app/controllers/notifications/create_controller.rb, app/forms/add_another_risk_assessment_form.rb, app/views/notifications/create/add_risk_assessments.html.erb
Created new form model to allow error summary to be displayed
=> chore/PSD-3030:Update_to_NTL_risk_assessments_form

app/controllers/account_name_controller.rb, app/views/account/confirmation.html.erb, config/routes.rb, spec/features/your_account_spec.rb, spec/support/features/page_expectations.rb
Description
Changed name change notification journey to include a confirmation page after the user changes his name, made spec changes to reflect the new journey
=>  chore/PSD-1088-Add_confirmation_page_to_your_account_page

app/controllers/notifications/create_controller.rb, app/controllers/notifications/edit_controller.rb, app/forms/add_business_roles_form.rb, spec/forms/add_business_roles_form_spec.rb
clicking away from the Business role page , does not add business, and some validation changes to make role mandatory, as the previous validation was not working
=> [PSD-2734] - not adding business until role is selected

app/views/investigations/activities/test/_result.html.erb
prevented errors from happening on activity page if investigation product is nil
=> chore/PSD-2776:Update_to_activity_test_result_display

app/views/help/accessibility.html.erb
update to the Accessibility statement
=> [PSD-3323] - update the Accessibility statement

app/helpers/products_helper.rb
Description
Merged multiple if statements about the same parameter into one conditional, removed compact_blank statement method from @search.countries, manually tested every single country and there will never be a blank entry to the list, made NOTIFICATION_TYPES list into a hash
=> refactor/PSD-3240:Update-to-product-export-helper

app/controllers/bulk_products_controller.rb
Description
Made sure that the notification state is submitted at the end of bulk product uploads journey
=> refactor/PSD-2874:Update_to_bulk_product_upload_journey 

app/controllers/products/recalls_controller.rb, app/forms/product_recall_form.rb, app/services/generate_product_recall_pdf.rb, app/views/products/recalls/product-details.html.erb, spec/services/generate_product_recall_pdf_spec.rb
enhancing the OMP information based on a new radio button
=> [PSD-3151] - enhance OMP info by adding more information

app/views/products/recalls/product-details.html.erb, spec/features/product_recall_spec.rb
(https://regulatorydelivery.atlassian.net/browse/PSD-3561)
As an IMT user can select one from additional Notified By options and these appear in the PDF and the Markdown text.
=> Applied change to product recall form (additional IMT options)

app/controllers/products/recalls_controller.rb, app/forms/product_recall_form.rb, app/models/product.rb, app/services/generate_product_recall_pdf.rb, app/views/products/recalls/product-details.html.erb, app/views/products/recalls/select-images.html.erb, spec/features/product_recall_spec.rb
ability to select Notification images and add them to Product recall PDF
=> [PSD-2092] - give ability to select Notification images for the Product Recall

app/forms/add_business_details_form.rb, app/models/business.rb
used squish method instead of strip , to remove any spaces between words as well
=> PSD-3634 -  reduce spaces in between words

app/views/notifications/show.html.erb
Also update Reported by Overseas regulator to show UK for No
=> PSD-3886 - remove Notifying country from summary

app/controllers/notifications/create_controller.rb
when there is no another form parameter , the object was throwing a Nil class exception which I have fixed
=> PSD-3357 - added null safe check 

app/controllers/pingdom/check_controller.rb, config/routes.rb, spec/controller/pingdom/check_controller_spec.rb, spec/rails_helper.rb
code migration preparation , implementing pingdom check
=> PSD-2687 - code migration preparation , implementing pingdom check

prism/app/controllers/prism/triage_controller.rb, prism/app/views/prism/triage/serious_risk.html.erb, prism/app/views/prism/triage/serious_risk_rebuttable.html.erb
removed the changes which are not needed and code changes to retain the product id value during validation error
=> PSD-3121 - changes to retain the product id during validation error

app/helpers/investigations_helper.rb
noticed we are not preventing the deleted Notifications to be loaded , added code to load active Notifications
=> PSD-4068  preventing_deleted_notifications_to_be_loaded

app/views/businesses/_table_row.html.erb, app/views/investigations/_full_table_body.html.erb, app/views/notifications/your_notifications.html.erb, spec/features/businesses_navigation_spec.rb
accessibility fix for the Business and Notification screens
=> PSD-3859 accessibility fix show not_provided where data is nil in tables

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Update to the staging and prod deployment to fix the deployment issues.
=> fix/PSD-4245-deployment_issues - stating/production

app/views/notifications/show.html.erb, spec/features/add_and_remove_a_testreport_edit_notification_spec.rb
text_change_to_keep_it_alligned to other links
=> PSD-3908 text_change_to_keep_it_alligned to other links

db/migrate/20241220122808_submit_notification_reminder.rb, db/schema.rb
Implemented Flipper flag to enable and disable features related to the epic PSD-3041.
This flag allows enabling and disabling of features (see PSD-4383 for implementation instructions).
=> Implemented Flipper flag

app/helpers/investigations_helper.rb
to remove condition to return notifications where my team is added with access for the filter owner, it should return only where me and My team is the owner
=> PSD-3873 update_the_notification_owner_filter

db/seeds.rb
updating the seeds file to activate the seed_user
=> updating the seeds file to activate the seed_user

app/views/businesses/_filters.html.erb, app/views/businesses/_secondary_nav.html.erb, app/views/investigations/_filters.html.erb, app/views/investigations/_sub_nav.html.erb, app/views/layouts/application.html.erb, app/views/notifications/_filters.html.erb, app/views/prism_risk_assessments/_secondary_nav.html.erb, app/views/products/_filters.html.erb, app/views/products/_secondary_nav.html.erb, app/views/products/_sub_nav.html.erb, spec/features/skip_links_spec.rb
=> PSD-3667_skip_to_main_content_link_misplaced

app/mailers/notify_mailer.rb
created a fix to update the url to make the user land in the Notification task list page
=> PSD-4023 - updating the investigation URl to the draft notification ask list URL

app/views/notifications/show.html.erb, app/views/notifications/your_notifications.html.erb, spec/features/notification_home_page_spec.rb, spec/features/notification_summary_spec.rb
new submitted date field being added to notification home page and summary screen
=> PSD-4467, PSD4472 - adding submitted date to Notification home page 

app/mailers/notify_mailer.rb
added Notification_id to reflect the changes asked by business, changes have been done in the gov notify template
=> adding the Notification_id to the personalization

app/controllers/notifications/create_controller.rb
match the product search in product tab to search the same products in notification add or remove product task list
=> allign product search to match the in the notification tasklist

app/views/notifications/show.html.erb, spec/features/notification_summary_spec.rb
reword Submitted date to Submitted on screen
=> update to notification summary screen to have Submitted instead of Submitted Date

app/views/products/_sub_nav.html.erb
update the notification count in product page accordion to display count without drafts
=> update the notification count in product page accordion

app/controllers/document_uploads_controller.rb, app/controllers/documents_controller.rb, app/controllers/image_uploads_controller.rb, app/forms/document_form.rb, app/models/document_upload.rb, app/models/image_upload.rb, app/models/product.rb, app/views/bulk_products/upload_products_file.html.erb, app/views/document_uploads/_document_preview.html.erb, app/views/documents/_document_preview.html.erb, app/views/image_uploads/_image_preview.html.erb, app/views/investigations/tabs/_images.html.erb, prism/app/helpers/prism/tasks/create_helper.rb, prism/app/services/prism/risk_assessment_pdf_service.rb, prism/app/views/prism/application/_attachment.html.erb
during Testing of virus image handling we found we need some nil safe checks to be implemented
=> fix/PSD-4770 _nil_safe_checks_added_to_image_handling

app/models/product_export.rb, spec/models/product_export_spec.rb
omitting the draft notifications from product export
=> PSD-4571 omitting drafts from product export

app/models/investigation/notification.rb, app/views/investigations/prism_risk_assessments/new.html.erb, app/views/investigations/risk_assessments/show.html.erb, app/views/notifications/show.html.erb, spec/factories/image_uploads.rb, spec/models/investigation/notification_spec.rb
added nil safe checks for virus image handling
=> PSD-4770 some more virus image nil safe handling

app/views/investigations/prism_risk_assessments/new.html.erb, app/views/notifications/create/add_risk_assessments_prism_or_legacy.html.erb, spec/factories/prism/risk_assessment.rb, spec/features/add_risk_assessment_from_notification_summary_spec.rb
changes to fix the PRISM journey from submitted notification flow and associated rspec
=> psd 4674 500 error while adding a prism risk assessment to a notification

app/models/business_export.rb, spec/features/businesses_spec.rb, spec/models/business_export_spec.rb
code changes to not to include Draft Notifications in Business Export
=> PSD-4853-Omit_drafts_from_business_export

spec/jobs/delete_unsafe_files_job_spec.rb
i have added an rspec to existing oe to check sidekiq specifically using the Job
=> PSD 5656 Add_a_spec_to_test_sidekiq
